# vi:filetype=python:expandtab:tabstop=2:shiftwidth=2

# file SConscript
#
# This file is part of LyX, the document processor.
# Licence details can be found in the file COPYING.
# 
# \author Bo Peng
# Full author contact details are available in file CREDITS.

Import('boostenv')

print 'Entering boost/libs/iostreams/src...'

iostreams = boostenv.StaticLibrary(
  target = '$LOCALLIBPATH/boost_iostreams',
  source = Split('''
    file_descriptor.cpp
    mapped_file.cpp
    zlib.cpp
  ''')
)

# Return the library
Return('iostreams')
