#!/bin/bash

TARGET_DIR=$(pwd)
SOURCE_DIR=$(dirname $(dirname $(dirname $TARGET_DIR/$0 | sed -e 's:/[^/]*/\.\.::'))) 

echo "Setting SOURCE_DIR ${SOURCE_DIR}"
echo "Setting TARGET_DIR ${TARGET_DIR}"

qmake	-set BUILD_BASE_SOURCE_DIR ${SOURCE_DIR}
qmake	-set BUILD_BASE_TARGET_DIR ${TARGET_DIR}

qmake -r "$@" ${SOURCE_DIR}/development/qmake/lyx.pro 

