#!/bin/sh

retval=0
for i in ${srcdir}/../lib/layouts/*.layout
do
	echo Testing $i...
	dn=`dirname $i`
	bn=`basename $i .layout`
	./check_layout ${dn}/${bn}
	if [ $? -ne 0 ]; then
		retval=1
	fi
done
exit $retval
