#!/bin/sh

retval=0
for i in ${srcdir}/../lib/layouts/*.layout
do
	echo Testing $i...
	dn=`dirname $i`
	bn=`basename $i .layout`
	if ! ./check_layout ${dn}/${bn}; then
		retval=1
	fi
done
exit $retval
