# vi:filetype=python:expandtab:tabstop=2:shiftwidth=2

# file SConscript
#
# This file is part of LyX, the document processor.
# Licence details can be found in the file COPYING.
# 
# \author Bo Peng
# Full author contact details are available in file CREDITS.

Import('env')

print "Entering src/frontends"

frontends = env.StaticLibrary( 
  target = '$LOCALLIBPATH/frontends',
  source = Split('''
    Alert.C 
    Dialogs.C 
    LyXView.C 
    Painter.C 
    Timeout.C 
    Toolbars.C 
    guiapi.C 
    nullpainter.C 
    screen.C 
    screen.h
  ''')
)

# return the library
Return('frontends')
