

EXECUTE_PROCESS(COMMAND ${KDE_UIC_EXECUTABLE}
${KDE_UIC_FILE}
OUTPUT_VARIABLE _uic_CONTENTS
ERROR_QUIET
)
set(KDE_UIC_CPP_FILE ${KDE_UIC_H_FILE})


FILE(WRITE ${KDE_UIC_CPP_FILE} "${_uic_CONTENTS}\n")

