# vi:filetype=python:expandtab:tabstop=2:shiftwidth=2

# file SConscript
#
# This file is part of LyX, the document processor.
# Licence details can be found in the file COPYING.
# 
# \author Bo Peng
# Full author contact details are available in file CREDITS.

Import('boostenv')

print 'Entering boost/libs/signals/src...'

signals = boostenv.StaticLibrary(
  target = '$LOCALLIBPATH/boost_signals',
  source = Split('''
    connection.cpp
    named_slot_map.cpp
    signal_base.cpp
    slot.cpp
    trackable.cpp
  ''')
)

# Return the library
Return('signals')
