# vi:filetype=python:expandtab:tabstop=2:shiftwidth=2

# file SConscript
#
# This file is part of LyX, the document processor.
# Licence details can be found in the file COPYING.
# 
# \author Bo Peng
# Full author contact details are available in file CREDITS.

Import('env')

print "Entering src/frontends/controllers"

controllers = env.StaticLibrary(
  target = '$LOCALLIBPATH/controllers',
  source = Split('''
    Dialog.C 
    Kernel.C 
    biblio.C 
    character.C 
    frnt_lang.C 
    tex_helpers.C 
    BCView.C 
    ButtonController.C 
    ButtonPolicies.C 
    ControlAboutlyx.C 
    ControlBibtex.C 
    ControlBox.C 
    ControlBranch.C 
    ControlCharacter.C 
    ControlChanges.C 
    ControlCitation.C 
    ControlCommand.C 
    ControlCommandBuffer.C 
    ControlDocument.C 
    ControlErrorList.C 
    ControlERT.C 
    ControlExternal.C 
    ControlFloat.C 
    ControlGraphics.C 
    ControlInclude.C 
    ControlLog.C 
    ControlViewSource.C 
    ControlMath.C 
    ControlNote.C 
    ControlParagraph.C 
    ControlPreamble.C 
    ControlPrefs.C 
    ControlPrint.C 
    ControlRef.C 
    ControlSearch.C 
    ControlSendto.C 
    ControlShowFile.C 
    ControlSpellchecker.C 
    ControlTabular.C 
    ControlTabularCreate.C 
    ControlTexinfo.C 
    ControlThesaurus.C 
    ControlToc.C 
    ControlVSpace.C 
    ControlWrap.C 
    helper_funcs.C 
    helper_funcs.h
  ''')
)

#return the library
Return('controllers')
