/*
 * \file configIncludes.h
 * This file is part of LyX, the document processor.
 * Licence details can be found in the file COPYING.
 *
 * This is the compilation configuration file for LyX.
 * It was generated by cmake.
 * You might want to change some of the defaults if something goes wrong
 * during the compilation.
 */

#ifndef _CONFIG_INCLUDES_H
#define _CONFIG_INCLUDES_H

${Include_Defines}

#endif
