/*
 * \file lyx_date.h
 * This file is part of LyX, the document processor.
 * Licence details can be found in the file COPYING.
 *
 * This is the compilation configuration file for LyX.
 * It was generated by cmake.
 * You might want to change some of the defaults if something goes wrong
 * during the compilation.
 */

#ifndef _LYX_DATE_H
#define _LYX_DATE_H

#cmakedefine LYX_DATE "${LYX_DATE}"

#endif

