# vi:filetype=python:expandtab:tabstop=2:shiftwidth=2

# file SConscript
#
# This file is part of LyX, the document processor.
# Licence details can be found in the file COPYING.
# 
# \author Bo Peng
# Full author contact details are available in file CREDITS.


Import('env')

print "Entering src/frontends/qt4"

qtenv = env.Copy()

# local qt4 toolset from 
# http://www.iua.upf.es/~dgarcia/Codders/sconstools.html
#
# NOTE: I have to patch qt4.py since it does not automatically
# process .C file!!! (add to cxx_suffixes )
# 
qtenv.Tool('qt4', ['$TOP_SRC_DIR/config'])
qtenv.EnableQt4Modules(env['QT_LIB'], debug = False)

qtenv.Append(CPPPATH = [
  '#$BUILDDIR', 
  '#$BUILDDIR/frontends', 
  '#$BUILDDIR/images', 
  '#$BUILDDIR/frontends/controllers',
  '$QT_INC_PATH',
  '$QT_INC_PATH/Qt', 
  '$QT_INC_PATH/QtCore', 
  '$QT_INC_PATH/QtGui', 
  '$QT_INC_PATH/Qt3Support', 
  '.']
)

# FIXME: replace by something from pkg_config
qtenv.Append(CCFLAGS = [
  '-DHAVE_CONFIG_H',
  '-DQT_CLEAN_NAMESPACE',
  '-DQT_GENUINE_STR',
  '-DQT_NO_STL',
  '-DQT3_SUPPORT',
  '-Winvalid-pch']
)

ui_files = Split('''
  BiblioUi
  BranchesUi
  BulletsUi
  TextLayoutUi
  LanguageUi
  LaTeXUi
  MarginsUi
  NumberingUi
  MathsUi
  PageLayoutUi
  PreambleUi
  QAboutUi
  QAskForTextUi
  QBibitemUi
  QBibtexUi
  QBibtexAddUi
  QBoxUi
  QBranchUi
  QChangesUi
  QCharacterUi
  QCitationUi
  QCitationFindUi
  QDelimiterUi
  QDocumentUi
  QErrorListUi
  QERTUi
  QExternalUi
  QFloatUi
  QGraphicsUi
  QIncludeUi
  QIndexUi
  QLogUi
  QViewSourceUi
  QMathUi
  QMathMatrixUi
  QNoteUi
  QParagraphUi
  QPrefAsciiUi
  QPrefColorsUi
  QPrefConvertersUi
  QPrefCopiersUi
  QPrefCygwinPathUi
  QPrefDateUi
  QPrefDisplayUi
  QPrefFileformatsUi
  QPrefIdentityUi
  QPrefKeyboardUi
  QPrefLanguageUi
  QPrefLatexUi
  QPrefPathsUi
  QPrefPrinterUi
  QPrefScreenFontsUi
  QPrefsUi
  QPrefSpellcheckerUi
  QPrefUi
  QPrintUi
  QRefUi
  QSearchUi
  QSendtoUi
  QShowFileUi
  QSpellcheckerUi
  QTabularCreateUi
  QTabularUi
  QTexinfoUi
  QThesaurusUi
  QTocUi
  QURLUi
  QVSpaceUi
  QWrapUi
''')

moc_files = Split('''
  BulletsModule.C
  emptytable.C
  FileDialog_private.C
  floatplacement.C
  iconpalette.C
  lengthcombo.C
  panelstack.C
  QAboutDialog.C
  QBibitemDialog.C
  QBibtexDialog.C
  QBoxDialog.C
  QBranchDialog.C
  QBranches.C
  QChangesDialog.C
  QCharacterDialog.C
  QCitationDialog.C
  QCommandBuffer.C
  QCommandEdit.C
  QDelimiterDialog.C
  QDocumentDialog.C
  QErrorListDialog.C
  QERTDialog.C
  QExternalDialog.C
  QFloatDialog.C
  QGraphicsDialog.C
  QIncludeDialog.C
  QIndexDialog.C
  QLAction.C
  QLogDialog.C
  QViewSourceDialog.C
  QViewSource.C
  QLMenubar.C
  QLPopupMenu.C
  QLPrintDialog.C
  QMathDialog.C
  QMathMatrixDialog.C
  QNoteDialog.C
  QParagraphDialog.C
  QPrefsDialog.C
  QRefDialog.C
  QSearchDialog.C
  QSendtoDialog.C
  qsetborder.C
  QShowFileDialog.C
  QSpellcheckerDialog.C
  QDialogView.C
  QTabularCreateDialog.C
  QTabularDialog.C
  QTexinfoDialog.C
  QThesaurusDialog.C
  TocModel.C
  QTocDialog.C
  QtView.C
  QURLDialog.C
  QVSpaceDialog.C
  QWorkArea.C
  QWrapDialog.C
  QLToolbar.C
  socket_callback.C
  validators.C
''')

#
# Compile resources
#
resources = [qtenv.Uic4('ui/' + x) for x in ui_files]

source_files = Split('''
  QDialogView.C 
  Alert_pimpl.C 
  Dialogs.C 
  FileDialog.C 
  LyXKeySymFactory.C 
  LyXScreenFactory.C 
  QLMenubar.C
  qtTimeout.C
  QAbout.C
  QBibitem.C
  QBibtex.C
  QBox.C
  QBranch.C
  QBranches.C
  QChanges.C
  QCharacter.C
  QCitation.C
  QDocument.C
  QErrorList.C
  QERT.C
  QExternal.C
  QFloat.C
  QGraphics.C
  QInclude.C
  QIndex.C
  QLAction.C
  QLImage.C
  QLog.C
  QViewSource.C
  QLPainter.C
  QLyXKeySym.C
  QMath.C
  QNote.C
  QParagraph.C
  QPrefs.C
  QPrint.C
  QRef.C
  QSearch.C
  QSendto.C
  QShowFile.C
  QSpellchecker.C
  QTabular.C
  QTabularCreate.C
  QTexinfo.C
  QThesaurus.C
  QToc.C
  QURL.C
  QVSpace.C
  QWorkArea.C
  QWrap.C
  Qt2BC.C
  WorkAreaFactory.C 
  checkedwidgets.C
  lyx_gui.C 
  lcolorcache.C 
  panelstack.C 
  qfontexample.C 
  qfont_loader.C 
  qfont_metrics.C 
  qscreen.C 
  qt_helpers.C 
''')

qt4 = qtenv.StaticLibrary(
  target = '$LOCALLIBPATH/qt4',
  LIBS = qtenv['QT_LIB'],
  source = source_files + moc_files
)

# return the library
Return('qt4')    
