# vi:filetype=python:expandtab:tabstop=2:shiftwidth=2

# file SConscript
#
# This file is part of LyX, the document processor.
# Licence details can be found in the file COPYING.
# 
# \author Bo Peng
# Full author contact details are available in file CREDITS.

Import('env')

print "Entering src/frontends/qt3"

qtenv = env.Copy()

# load qt3 tools
qtenv.Tool('qt')

qtenv.Append(CPPPATH = [
  '#$BUILDDIR', 
  '#$BUILDDIR/frontends', 
  '#$BUILDDIR/images', 
  '#$BUILDDIR/frontends/controllers',
  '$QT_INC_DIR', 
  '.']
)

ui_files = Split('''
  BiblioModuleBase.ui 
  BranchesModuleBase.ui 
  BulletsModuleBase.ui 
  TextLayoutModuleBase.ui 
  LanguageModuleBase.ui 
  LaTeXModuleBase.ui 
  MarginsModuleBase.ui 
  NumberingModuleBase.ui 
  MathsModuleBase.ui 
  PageLayoutModuleBase.ui 
  PreambleModuleBase.ui 
  QAboutDialogBase.ui 
  QAskForTextDialog.ui 
  QBibitemDialogBase.ui 
  QBibtexDialogBase.ui 
  QBibtexAddDialogBase.ui 
  QBoxDialogBase.ui 
  QBranchDialogBase.ui 
  QChangesDialogBase.ui 
  QCharacterDialogBase.ui 
  QCitationDialogBase.ui 
  QCitationFindDialogBase.ui 
  QDelimiterDialogBase.ui 
  QDocumentDialogBase.ui 
  QErrorListDialogBase.ui 
  QERTDialogBase.ui 
  QExternalDialogBase.ui 
  QFloatDialogBase.ui 
  QGraphicsDialogBase.ui 
  QIncludeDialogBase.ui 
  QIndexDialogBase.ui 
  QLogDialogBase.ui 
  QViewSourceDialogBase.ui 
  QMathDialogBase.ui 
  QMathMatrixDialogBase.ui 
  QNoteDialogBase.ui 
  QParagraphDialogBase.ui 
  QPrefAsciiModule.ui 
  QPrefColorsModule.ui 
  QPrefConvertersModule.ui 
  QPrefCopiersModule.ui 
  QPrefCygwinPathModule.ui 
  QPrefDateModule.ui 
  QPrefDisplayModule.ui 
  QPrefFileformatsModule.ui 
  QPrefIdentityModule.ui 
  QPrefKeyboardModule.ui 
  QPrefLanguageModule.ui 
  QPrefLatexModule.ui 
  QPrefPathsModule.ui 
  QPrefPrinterModule.ui 
  QPrefScreenFontsModule.ui 
  QPrefsDialogBase.ui 
  QPrefSpellcheckerModule.ui 
  QPrefUIModule.ui 
  QPrintDialogBase.ui 
  QRefDialogBase.ui 
  QSearchDialogBase.ui 
  QSendtoDialogBase.ui 
  QShowFileDialogBase.ui 
  QSpellcheckerDialogBase.ui 
  QTabularCreateDialogBase.ui 
  QTabularDialogBase.ui 
  QTexinfoDialogBase.ui 
  QThesaurusDialogBase.ui 
  QTocDialogBase.ui 
  QURLDialogBase.ui 
  QVSpaceDialogBase.ui 
  QWrapDialogBase.ui
''')
  
moc_files = Split('''
  BulletsModule.C
  emptytable.C
  FileDialog_private.C
  floatplacement.C
  iconpalette.C
  lengthcombo.C
  panelstack.C
  QAboutDialog.C
  QBibitemDialog.C
  QBibtexDialog.C
  QBoxDialog.C
  QBranchDialog.C
  QBrowseBox.C
  QChangesDialog.C
  QCharacterDialog.C
  QCitationDialog.C
  QCommandBuffer.C
  QCommandEdit.C
  QContentPane.C
  QDelimiterDialog.C
  QDocumentDialog.C
  QErrorListDialog.C
  QERTDialog.C
  QExternalDialog.C
  QFloatDialog.C
  QGraphicsDialog.C
  QIncludeDialog.C
  QIndexDialog.C
  QLogDialog.C
  QViewSourceDialog.C
  QLPopupMenu.C
  QLPrintDialog.C
  QMathDialog.C
  QMathMatrixDialog.C
  QNoteDialog.C
  QParagraphDialog.C
  QPrefsDialog.C
  QRefDialog.C
  QSearchDialog.C
  QSendtoDialog.C
  qsetborder.C
  QShowFileDialog.C
  QSpellcheckerDialog.C
  QDialogView.C
  QTabularCreateDialog.C
  QTabularDialog.C
  QTexinfoDialog.C
  QThesaurusDialog.C
  QTocDialog.C
  qttableview.C
  QtView.C
  QURLDialog.C
  QVSpaceDialog.C
  QWrapDialog.C
  QLToolbar.C
  socket_callback.C
  validators.C
''')
  
qt3 = qtenv.StaticLibrary(
  target = '$LOCALLIBPATH/qt3',
  source = Split('''
    QDialogView.C 
    Alert_pimpl.C 
    Dialogs.C 
    FileDialog.C 
    LyXKeySymFactory.C 
    LyXScreenFactory.C 
    QLMenubar.C
    qtTimeout.C
    QAbout.C
    QBibitem.C
    QBibtex.C
    QBox.C
    QBranch.C
    QChanges.C
    QCharacter.C
    QCitation.C
    QDocument.C
    QErrorList.C
    QERT.C
    QExternal.C
    QFloat.C
    QGraphics.C
    QInclude.C
    QIndex.C
    QLImage.C
    QLog.C
    QViewSource.C
    QLPainter.C
    QLyXKeySym.C
    QMath.C
    QNote.C
    QParagraph.C
    QPrefs.C
    QPrint.C
    QRef.C
    QSearch.C
    QSendto.C
    QShowFile.C
    QSpellchecker.C
    QTabular.C
    QTabularCreate.C
    QTexinfo.C
    QThesaurus.C
    QToc.C
    QURL.C
    QVSpace.C
    QWorkArea.C 
    QWrap.C
    Qt2BC.C
    WorkAreaFactory.C 
    checkedwidgets.C 
    lyx_gui.C 
    lcolorcache.C 
    panelstack.C 
    qcoloritem.C 
    qfontexample.C 
    qfont_loader.C 
    qfont_metrics.C 
    qscreen.C 
    qt_helpers.C 
  ''') +
  moc_files + 
  ['ui/' + x for x in ui_files]
)

# return the library
Return('qt3')
