# vi:filetype=python:expandtab:tabstop=2:shiftwidth=2

# file SConscript
#
# This file is part of LyX, the document processor.
# Licence details can be found in the file COPYING.
# 
# \author Bo Peng
# Full author contact details are available in file CREDITS.

Import('env')

print "Entering src/supports"

env.Append(CPPPATH = ['.'])

env['SUBST_KEYS'] = ['LYX_DIR', 'LOCALEDIR', 'TOP_SRCDIR', 'PROGRAM_SUFFIX']
env.substFile('package.C', 'package.C.in')

supports = env.StaticLibrary(
  target = '$LOCALLIBPATH/supports',
  source = Split('''
    FileMonitor.C 
    abort.C 
    chdir.C 
    convert.C 
    copy.C 
    environment.C 
    filefilterlist.C 
    filename.C 
    filetools.C 
    forkedcall.C 
    forkedcallqueue.C 
    forkedcontr.C 
    fs_extras.C 
    getcwd.C 
    kill.C 
    lstrings.C 
    lyxtime.C 
    lyxsum.C 
    mkdir.C 
    os.C 
    path.C 
    package.C 
    rename.C 
    socktools.C 
    systemcall.C 
    tempname.C 
    userinfo.C 
    unlink.C
  ''')
)

# return the library
Return('supports')

