# vi:filetype=python:expandtab:tabstop=2:shiftwidth=2

# file SConscript
#
# This file is part of LyX, the document processor.
# Licence details can be found in the file COPYING.
# 
# \author Bo Peng
# Full author contact details are available in file CREDITS.

Import('boostenv')

print 'Entering boost/libs/regex/src...'

regex = boostenv.StaticLibrary(
  target = '$LOCALLIBPATH/boost_regex',
  source = Split('''
    cpp_regex_traits.cpp
    c_regex_traits.cpp
    cregex.cpp
    fileiter.cpp
    instances.cpp
    regex.cpp
    regex_raw_buffer.cpp
    regex_traits_defaults.cpp
    w32_regex_traits.cpp
  ''')
)

# Return the library
Return('regex')
