#\DeclareLyXModule[algorithm2e.sty]{Algorithm2e}
#DescriptionBegin
# Use the algorithm2e package for algorithm floats rather
# than LyX's home-brewed algorithm floats.
#DescriptionEnd
#
#Author: Jürgen Spitzmüller

Format 59

Requires algorithm2e

Float
	Type                  algorithm
	GuiName               Algorithm
	Placement             tbp
	AllowedPlacement      !htbp
	AllowsSideways        0
	Extension             loa
	NumberWithin          none
	Style                 plain
	ListName              "List of Algorithms"
	IsPredefined          true
	UsesFloatPkg          false
	ListCommand           listofalgorithms
	RefPrefix             alg
End

