#\DeclareLyXModule[bicaption.sty]{Multilingual captions}
#DescriptionBegin
#Provides two styles to typeset multilingual captions.
#For a description see the file MultilingualCaptions.lyx in LyX's examples folder.
#DescriptionEnd
#Author: Uwe Stöhr <uwestoehr@web.de>

Format 43

Style "Caption setup"
	LatexType		command
	LatexName		captionsetup
	Category		FrontMatter
	Argument 1
		LabelString   "Caption Setup Options|S"
		Tooltip       "Options for the caption setup command (see bicaption manual)"
	EndArgument
	Margin			Dynamic
	LabelSep		xx
	ParSkip			0.0
	ItemSep			0.2
	TopSep			0.7
	BottomSep		0.7
	ParSep			0.3
	Align			Block
	AlignPossible		Block
	LabelType		Static
	LabelString		"Caption setup:"
	LabelFont
		Color		Green
	EndFont
	BabelPreamble
	\usepackage{bicaption} % for multilingual captions
	EndBabelPreamble
End


InsetLayout Caption:Bicaption
	LabelString          bilingual
	LaTeXType            command
	LatexName            bicaption
	Argument 1
		LabelString   "Main Language Caption Short Title"
		Tooltip       "A short title (for list of figures/tables) in the document language"
	EndArgument
	Argument 2
		Mandatory     1
		LabelString   "Main Language Caption Text|S"
		Tooltip       "The caption text in the document language"
	EndArgument
	Argument 3
		LabelString   "Second Language Caption Short Title"
		Tooltip       "A short title (for list of figures/tables) in the second language"
	EndArgument
	HTMLStyle
		div.float-caption {
			text-align: center;
			border: 2px solid black;
			padding: 1ex;
			margin: 1ex;
		}
	EndHTMLStyle
End
