#\DeclareLyXModule{Dropped Capitals}
#DescriptionBegin
#Define character style for dropped capitals.
#Hint: try to use math and its font styles for a different shape.
#DescriptionEnd

Format 16

InsetLayout CharStyle:DropCapital
	LyxType               charstyle
	LabelString           "Dropped Capital"
	LatexType             command
	LatexName             lettrine
	Font
	  Size               Large
	EndFont
	Requires              lettrine
	Preamble
		\usepackage{lettrine}
	EndPreamble
End


