#\DeclareLyXModule[changebar.sty]{Change Tracking Bars}
#\DeclareCategory{Annotation & Revision}
#
#DescriptionBegin
#Enables LyX to add vertical change bars in the margin of PDF output
#when Show Changes in Output is turned on and pdflatex output format is chosen.
#DescriptionEnd
#
#Author: Paul A. Rubin (rubin@msu.edu)
#Based on code proposed by Juergen Spitzmueller
#(http://comments.gmane.org/gmane.editors.lyx.general/66666).
#
# Note: the \providecommand statements are necessary to avoid
# error messages from the \renewcommand statements if change
# tracking is turned off in the document.
#

Format 80

AddToPreamble
  \usepackage{changebar}
  \providecommand{\lyxadded}[4][]{}
  \providecommand{\lyxdeleted}{}
  \renewcommand{\lyxadded}[4][]{
    {\protect\cbstart\color{lyxadded}{}#4\protect\cbend}
  }
  \renewcommand{\lyxdeleted}[4][]{%
    {\protect\cbstart\color{lyxdeleted}\sout{#4}\protect\cbend}
  }
EndPreamble
