# Author : José Matos <jamatos@lyx.org>
#          Martin Vermeer <martin.vermeer@hut.fi>

# This include file contains all the counters that are defined as standard
# in Docbook LyX layouts.

Format 35
Counter sect1
	Within               chapter
End

Counter sect2
	Within               sect1
End

Counter sect3
	Within               sect2
End

Counter sect4
	Within               sect3
End

Counter sect5
	Within               sect4
End

