# Textclass definition file for docbook.
# Author : José Abílio Oliveira Matos <jamatos@lyx.org>

# This file is the counterpart of stdstarsections.inc
# It is desireable, as far as possible, to have the same look and feeling for
# related layouts in latex and docbook.

# empty for now, it is possible to do it using bridgehead with attribute 
# renderas="part|chapter|sect1|sect2|sect3|sect4|sect5"