# Textclass definition file for docbook.
# Author : José Abílio Oliveira Matos <jamatos@lyx.org>

# This file is the counterpart of stdstruct.inc
# It is desireable, as far as possible, to have the same look and feeling for
# related layouts in latex and docbook.

Input stdstruct.inc

# Abstract style definition
Style Abstract
  LatexType		Environment
  LatexName		abstract
  LatexParam		para
End 

NoStyle Bibliography