#\DeclareLyXModule[endnotes.sty]{Endnote}
#DescriptionBegin
#Adds an endnote inset, in addition to footnotes. You will need to add 
#\theendnotes in TeX-code where you want the endnotes to appear.
#DescriptionEnd

Format 35

InsetLayout Flex:Endnote
   LyXType	custom
   LatexName	endnote
   LatexType	command
   Decoration classic
   Font
     Size	Small
   EndFont
   MultiPar true
   LabelString	endnote
   Requires	endnotes
End
