#\DeclareLyXModule[endnotes.sty]{Endnotes}
#\DeclareCategory{Foot- and Endnotes}
#DescriptionBegin
#Adds an endnote inset, in addition to footnotes. You will need to add an
#endnotes list (Insert > List/Contents/References > Endnotes) where you
#want the endnotes to appear.
#DescriptionEnd

Format 79

Counter endnotes
    PrettyFormat "Endnote ##"
End

InsetLayout Flex:Endnote
   LyXType     custom
   LatexName   endnote
   LatexType   command
   Counter     endnotes
   Decoration  classic
   Font
     Size Small
   EndFont
   MultiPar    true
   LabelString endnote
   Requires    endnotes
End

# We are only interested in the list
Float
   Type          endnote
   ListName      "Endnotes"
   IsPredefined  true
   UsesFloatPkg  false
   ListCommand   theendnotes
   Requires      endnotes
End
