#\DeclareLyXModule[enotez.sty]{Endnotes (Extended)}
#\DeclareCategory{Foot- and Endnotes}
#DescriptionBegin
#Adds an endnote inset, in addition to footnotes. This uses the enotez package
#which is more powerful and customizable than then endnotes package (module 'Endnotes (Basic)'),
#but requires a fairly modern LaTeX distribution (with LaTeX3).
#You will need to add an endnotes list (Insert > List/Contents/References > Endnotes)
#where you want the endnotes to appear.
#DescriptionEnd
#Excludes: endnotes | foottoend

Format 82

Counter endnotes
	GuiName Endnotes
    PrettyFormat "Endnote ##"
End

InsetLayout Flex:Endnote
   LyXType     custom
   LatexName   endnote
   LatexType   command
   Counter     endnotes
   Decoration  classic
   Font
     Size Small
   EndFont
   MultiPar    true
   LabelString endnote
   Requires    enotez
End

# We are only interested in the list
Float
   Type          endnote
   ListName      "Endnotes"
   IsPredefined  true
   UsesFloatPkg  false
   ListCommand   printendnotes
   Requires      enotez
End
