#\DeclareLyXModule{Number Equations by Section}
#\DeclareCategory{Maths}
#DescriptionBegin
#Resets the equation number at section start and prepends
#the section number to the equation number, as in '(2.1)'.
#DescriptionEnd

Format 80

Requires amsmath

AddToPreamble
	\numberwithin{equation}{section}
EndPreamble

Counter equation
	GuiName Equation
	Within section
	LabelString "\thesection.\arabic{equation}"
End
