#\DeclareLyXModule{Fix Computer Modern Fonts}
#\DeclareCategory{Fixes & Hacks}
#DescriptionBegin
#Fix-cm improves the appearance of Computer Modern fonts and makes them
#available with arbitrary sizes. For details see the documentation
#of the fix-cm.sty package:
#http://tug.org/texmf-dist/doc/latex/base/fixltx2e.pdf
#DescriptionEnd

# Author : Patrick Atamaniuk <patrick-lyx@frobs.net>

Format 85

Requires fix-cm
