#\DeclareLyXModule{Fix LaTeX}
#DescriptionBegin
#Loads the LaTeX package fixltx2e which contains some bug fixes for LaTeX.
#Those fixes are not part of the LaTeX kernel because of backward compatibility.
#If you use this module your typeset document may look different
#when you process it with future LaTeX versions, because fixltx2e may provide
#more bugfixes in future versions.
#Note that the recent LaTeX kernel (2015/01/01) includes fixltx2e,
#so the fixltx2e module becomes obsolete as of TeXLive 2015.
#DescriptionEnd

# Author : Georg Baum <baum@lyx.org>

Format 60

Requires fixltx2e
