#\DeclareLyXModule[endnotes.sty]{Footnotes as Endnotes}
#\DeclareCategory{Foot- and Endnotes}
#DescriptionBegin
#Sets all footnotes as endnotes. You will need to add an
#endnotes list (Insert > List/Contents/References > Endnotes) where you
#want the endnotes to appear.
#DescriptionEnd

Format 79

Requires	endnotes

AddToPreamble
  \let\footnote=\endnote
EndPreamble

# We are only interested in the list
Float
   Type          endnote
   ListName      "Endnotes"
   IsPredefined  true
   UsesFloatPkg  false
   ListCommand   theendnotes
   Requires      endnotes
End
