#\DeclareLyXModule[enotez.sty]{Footnotes as Endnotes (Extended)}
#\DeclareCategory{Foot- and Endnotes}
#DescriptionBegin
#Sets all footnotes as endnotes. This uses the enotez package
#which is more powerful and customizable than then endnotes package
#(module 'Footnotes as Endnotes (Basic)'), but requires a fairly modern
#LaTeX distribution (with LaTeX3).You will need to add an
#endnotes list (Insert > List/Contents/References > Endnotes) where you
#want the endnotes to appear.
#DescriptionEnd
#Excludes: endnotes | foottoend

Format 84


InsetLayout Foot
	LabelString     Endnote
	LatexName       endnote
	Requires        enotez
End

# We are only interested in the list
Float
   Type          endnote
   ListName      "Endnotes"
   IsPredefined  true
   UsesFloatPkg  false
   ListCommand   printendnotes
   Requires      enotez
End
