#\DeclareLyXModule{Hanging}
#DescriptionBegin
#Adds an environment for hanging paragraphs. 
#Hanging paragraph is a paragraph in which the first line is set to the left margin, but all subsequent lines are indented.
#DescriptionEnd

#Author: Richard Heck

#Hanging paragraph code adapted from hanging.sty, available at:
# http://www.ctan.org/tex-archive/macros/latex/contrib/hanging/
#Copyright Peter R. Wilson.
#Released under the LaTeX Project Public License.

Format 35

Style Hanging
  LatexType Environment
  LatexName hangparagraphs
  Align Block
  Margin Static
  LeftMargin "MMMM"
  ParIndent "-MMMM"
  Requires	ifthen
  Preamble
    \newlength{\lyxhang}
    \IfFileExists{hanging.sty}{
      \usepackage{hanging}
      \newenvironment{hangparagraphs}
        {%
          \ifthenelse{\lengthtest{\parindent > 0pt}}%
            {\setlength{\lyxhang}{\parindent}}%
            {\setlength{\lyxhang}{2em}}%
          \par\begin{hangparas}{\lyxhang}{1}%
        }
        {\end{hangparas}}
    }{%else
      \newenvironment{hangparagraphs}
        {%
          \ifthenelse{\lengthtest{\parindent > 0pt}}%
            {\setlength{\lyxhang}{\parindent}}%
            {\setlength{\lyxhang}{2em}}%
          \begin{hangparas}%
        }
        {\end{hangparas}}
      \newcommand{\hangpara}{\hangindent \lyxhang \hangafter 1 \noindent}
      \newenvironment{hangparas}{\setlength{\parindent}{\z@}
      \everypar={\hangpara}}{\par}
    }
  EndPreamble
End
