#\DeclareLyXModule{Initials}
#DescriptionBegin
#Define character style for initials.
#Hint: try to use math and its artistic font styles like Fractur or the Calligraphic one.
#DescriptionEnd
#Category: charstyles
# Author: Pavel Sanda and Uwe Stöhr

Format 35

AddToPreamble
	\@ifundefined{lettrine}{\usepackage{lettrine}}{}
EndPreamble

InsetLayout Flex:Initial
	LyxType			charstyle
	LabelString		"Initial"
	LatexType		command
	LatexName		lettrine
	Font
	  Size			Large
	EndFont
	Requires		lettrine
End

Style Initial
	Category		MainText
	LatexType		command
	LatexName		lettrine
	Margin			First_Dynamic
	LabelType		static
	LabelString		Initial
	OptionalArgs		1
	RequiredArgs		1
	LabelSep		x
	ParIndent		MMM
	ParSkip			0.4
	TopSep			0.7
	BottomSep		0.7
	ParSep			0.3
	Align			Left
	AlignPossible		Left
	LabelFont
	  Series		Bold
	EndFont
End

