#\DeclareLyXModule{Initials}
#DescriptionBegin
#Define a style for paragraphs with an initial.
#See the EmbeddedObjects manual for a detailed description.
#DescriptionEnd
#Authors: Pavel Sanda and Uwe Stöhr

Format 40

AddToPreamble
	\@ifundefined{lettrine}{\usepackage{lettrine}}{}
EndPreamble

InsetLayout Flex:Initial
	LyxType			charstyle
	LabelString		"Initial"
	LatexType		command
	LatexName		lettrine
	Font
	  Size			Large
	EndFont
	Requires		lettrine
End

Style Initial
	Category		MainText
	LatexType		command
	LatexName		lettrine
	Margin			First_Dynamic
	LabelType		static
	LabelString		Initial
	Argument option
		LabelString   "Initial Option"
		Tooltip       "Optional argument for initial (see lettrine manual)"
	EndArgument
	Argument inital
		Mandatory     1
		LabelString   "Initial"
		Tooltip       "Initial letter"
	EndArgument
	LabelSep		x
	ParIndent		MMM
	ParSkip			0.4
	TopSep			0.7
	BottomSep		0.7
	ParSep			0.3
	Align			Left
	AlignPossible		Left
	LabelFont
	  Series		Bold
	EndFont
End

