#\DeclareLyXModule{Landscape}
#DescriptionBegin
#Output parts of the document in landscape mode.
#DescriptionEnd
#
#Author: Jürgen Spitzmüller <spitz@lyx.org>

Format 71

InsetLayout Flex:Landscape
	LyXType		custom
	Decoration	classic
	ResetsFont	0
	MultiPar	1
	LabelString	Landscape
	LatexName	landscape
	LatexType	environment
	LabelFont
	  Family	Roman
	  Color		red
	EndFont
	Requires        lscape
End

InsetLayout Flex:Landscape_(Floating)
	CopyStyle	Flex:Landscape
	LatexType	none
	LabelString	"Landscape (floating)"
	LeftDelim	\afterpage{\begin{landscape}<br/>
	RightDelim	<br/>\end{landscape}}
	Requires        lscape,afterpage
End
