#\DeclareLyXModule[lilypond-book->latex]{LilyPond Book}
#DescriptionBegin
#This module adds an inset to enter LilyPond code directly into LyX.
#It will be processed in the output. See the lilypond.lyx example file.
#DescriptionEnd
#Excludes: sweave

# Author: Julien Rioux <jrioux@lyx.org>

Format 54
OutputFormat           lilypond-book

InsetLayout "Flex:LilyPond"
	LabelString           LilyPond
	LaTeXType             Environment
	LaTeXName             lilypond
	LyXType               Custom
	Decoration            Classic
	Font
	  Color               latex
	  Family              typewriter
	EndFont
	LabelFont
	  Color               latex
	  Size                Small
	EndFont
	MultiPar              true
	CustomPars            false
	ForcePlain            true
	FreeSpacing           true
	PassThru              true
	ParbreakIsNewline     true
	ForceLTR              true
	Spellcheck            false
	Argument 1
	  LabelString         "Options"
	  MenuString          "LilyPond Options"
	  Tooltip             "A comma-separated option list (see the LilyPond documentation for available options)."
	  Decoration          Conglomerate
	  Font
	    Color             black
	    Family            typewriter
	  EndFont
	  LabelFont
	    Color             black
	  EndFont
	EndArgument
End
