#\DeclareLyXModule{Minimalistic Insets}
#\DeclareCategory{Fixes & Hacks}
#DescriptionBegin
# Redefines several insets (Index, Branch, URL) as being Minimalistic. 
#DescriptionEnd

Format 93

InsetLayout Index
		Decoration   minimalistic
		Font
			Color               textlabel2
			Size                Small
		EndFont
		LabelFont
			Color               textlabel2
			Size                Small
		EndFont
End

InsetLayout Branch
  Decoration            minimalistic
End

InsetLayout URL
	Decoration            minimalistic
	LabelString           URL
End


