#\DeclareLyXModule[multicol.sty]{Multiple Columns}
#DescriptionBegin
#Adds 2 styles to begin and end text in multiple columns.
#The begin style contains the number of columns, the end style must be kept empty.
#See the Additional manual, section 'Multiple Text Columns', for a detailed
#description of multiple columns.
#DescriptionEnd
#Author: Uwe Stöhr

Format 44

AddToPreamble
 % used for multiple text columns
 \usepackage{multicol}

EndPreamble

Style "Begin Multiple Columns"
  Category		MainText
  Margin		First_Dynamic
  LatexType		command
  LabelType		Static
  LabelSep		xx
  LatexName	        begin{multicols}
  LabelString		"---Begin Multiple Columns---"
  Argument post:1
    LabelString		"Preface"
    Tooltip		"An optional preface"
  EndArgument
  Argument post:2
    LabelString		"Space Before Page Break"
    Tooltip		"Free space that needs to be on the page to start the multiple columns on this page"
  EndArgument
  KeepEmpty		1
  ParSkip		0
  TopSep		0
  BottomSep		0
  ParSep		0
  Font
    Color		Blue
  EndFont
  LabelFont
    Color		Green
  EndFont
End

Style "End Multiple Columns"
  CopyStyle		"Begin Multiple Columns"
  LatexName	        end{multicols}
  LabelString		"---End Multiple Columns---"
  ResetArgs		1
End

