#\DeclareLyXModule[natbib.sty,apacite.sty]{APA Style with Natbib}
#\DeclareCategory{Bibliography}
#DescriptionBegin 
#This module adds support for using natbib together with
#apacite (the bibliography style need not be apacite--it
#         could be apacite, apacitex, or any bibliography
#         that works with both the natbib and apacite
#         packages.)
#DescriptionEnd
#
# Author: Jacob Bishop <bishop.jacob@gmail.com>

Format 81

AddToPreamble
\usepackage[natbibapa]{apacite}
EndPreamble

Provides natbib 1
