#\DeclareLyXModule[literate->latex,noweb.sty]{Noweb}
#DescriptionBegin
#Allows to use Noweb as a literate programming tool.
#DescriptionEnd
#Category: literate

Format 35
OutputType              literate

# FIXME: Use the Chunk layout from the sweave module? 
Style Scrap
	Margin                First_Dynamic
	LatexType             Paragraph
	LatexName             dummy
	LeftMargin            MMM
	Align                 Left
	AlignPossible         Block,Left
	NewLine               0
	FreeSpacing           1
	PassThru              1
	ParbreakIsNewline     1
	Spellcheck	      0
	LabelType             Static
	LabelFont
	  Color               magenta
	EndFont
	TextFont
	  Color               latex
	  Family              Typewriter
	EndFont
End
