#\DeclareLyXModule{Ruby (Furigana)}
#\DeclareCategory{Annotation & Revision}
#DescriptionBegin
#Defines an inset to typeset reading aids (ruby, furigana) to Chinese
#characters. Uses the "okumakro", "luatexja-ruby", or "ruby" package
#(depending on the TeX engine) or a fallback definition.
#DescriptionEnd
#Requires
#Excludes

#Authors: Koji Yokota (original implementation as local layout),
#         Günter Milde <milde@lyx.org> (module)

# References:
# required packages
#   okumacro.sty:       https://ctan.org/pkg/jsclasses
#   luatexja-ruby.sty:  https://ctan.org/pkg/luatexja
#   ruby.sty:           https://www.ctan.org/pkg/cjk
# extended ruby support package (currently not used): 
#   https://ctan.org/pkg/pxrubrica
# W3W spec: 
#   https://www.w3.org/International/articles/ruby/markup.en.html

Format 90

InsetLayout Flex:Ruby
	LyxType		charstyle
	LatexType	command
	LatexName	ruby
	HTMLTag		ruby
	HTMLAttr	""
	HTMLInnerTag	rb
	HTMLInnerAttr	""
	BgColor		none
	LabelString	"Ruby"
	Decoration	Conglomerate
	Preamble
	  \ifdefined\kanjiskip
	    \IfFileExists{okumacro.sty}{\usepackage{okumacro}}{}
	  \else \ifdefined\luatexversion
	    \usepackage{luatexja-ruby}
	  \else \ifdefined\XeTeXversion
	    \usepackage{ruby}%
	  \fi\fi\fi
	  \providecommand{\ruby}[2]{\shortstack{\tiny #2\\#1}}
	EndPreamble
        # Fixme: Currently the ruby text is ignored in HTML
	Argument	post:1
		LabelString	"ruby text"
		MenuString	"Ruby Text|R"
		Tooltip		"Reading aid (ruby, furigana) for Chinese characters."
		Decoration	Conglomerate
		Font
		  Size		tiny
		EndFont
		LabelFont
		  Size		tiny
		EndFont
		Mandatory	1
	EndArgument
End
