# Textclass definition file for LaTeX.
# Author : Martin vermeer <amrtin.vermeer@hut.fi>
# Character Styles definition

Format 4
InsetLayout CharStyle:Noun
	LyxType               charstyle
	LabelString           noun
	LatexType             command
	LatexName             noun
	Font
	  Shape               Smallcaps
	EndFont
End


InsetLayout CharStyle:Emph
	LyxType               charstyle
	LabelString           emph
	LatexType             command
	LatexName             emph
	Font
	  Shape               Italic
	EndFont
End

