#\DeclareLyXModule{Theorems (Numbered by Chapter)}
#DescriptionBegin
#Numbers theorems and the like by chapter (i.e., the counter is reset at
#each chapter start). Use this module only with layouts that provide a chapter
#environment.
#DescriptionEnd
#Requires: theorems-std | theorems-ams
#Excludes: theorems-sec

# Author: Richard Heck <rgheck@comcast.net>
# Tweaked by Paul Rubin <rubin@msu.edu> June '09 (added theoremstyle)

Format 11

Counter theorem
	Within         chapter
End

Style Theorem
	Preamble
		\theoremstyle{plain}
		\ifx\thechapter\undefined
			\newtheorem{thm}{Theorem}
		\else
			\newtheorem{thm}{Theorem}[chapter]
		\fi
	EndPreamble
End
