#\DeclareLyXModule{Defines some theorem environments for use with non-AMS classes. The theorems are numbered within chapters of the document. NOTES: This module should therefore be used only with document classes that define a chapter environment. Only one of the theorem modules should be used at a time.}{Theorems (By Chapter)}

# Author: Richard Heck <rgheck@comcast.net>
# Adapted from amsmaths.inc

Format 5

Counter
	Name           theorem
	Within         chapter
End

Input theorems.inc
