#\DeclareLyXModule{Theorems (AMS)}
#DescriptionBegin
#Defines theorem environments and the proof environment using the extended 
#AMS machinery. Both numbered and unnumbered types are provided. By default, 
#the theorems are numbered consecutively throughout the document. This can be
#changed by loading one of the Theorems (Ordered By ...) modules.
#DescriptionEnd
#Excludes: Theorems | Theorems (Starred)

# Original Author : David L. Johnson <dlj0@lehigh.edu>
# Probably broken by Jean-Marc Lasgouttes <Jean-Marc.Lasgouttes@inria.fr>
# modified and modularized by Emmanuel GUREGHIAN <gureghia@boston.bertin.fr>
# Tinkered with Sep. '07 by Paul Rubin <rubin@msu.edu>
# Modularized Jan 08 by Richard Heck <rgheck@comcast.net>

Format 6

Requires	amsmath,amsthm

Counter
	Name theorem
End

Preamble
	\theoremstyle{plain}
EndPreamble

#Get the order right
Style Theorem
End

Style Theorem*
End

Style Corollary
End

Style Corollary*
End

Style Lemma
End

Style Lemma*
End

Style Proposition
End

Style Proposition*
End

Style Conjecture
End

Style Conjecture*
End

Style Definition
End

Style Definition*
End

Style Example
End

Style Example*
End

Style Problem
End

Style Problem*
End

Style Exercise
End

Style Exercise*
End

Style Remark
End

Style Remark*
End

Style Claim
End

Style Claim*
End

Input theorems.inc
Input theorems-starred.inc
Input theorems-proof.inc
