#\DeclareLyXModule{AMS Theorems (Numbered by Type)}
#\DeclareCategory{Maths}
#DescriptionBegin
#Defines theorem environments and the proof environment using the extended 
#AMS machinery. Both numbered and unnumbered types are provided. Contrary to the
#plain AMS Theorem module, the different theorem types provided here each have 
#a separate counter (e.g., theorem 1, theorem 2, lemma 1, proposition 1, theorem 3,
#lemma 2, ..., as opposed to theorem 1, theorem 2, lemma 3, proposition 4, ...).
#The numbering's scope is the whole document. For chapter- and section-wide numbering,
#use one of the 'within Sections'/'within Chapters' modules, respectively.
#DescriptionEnd
#Excludes: theorems-std | theorems-starred | theorems-ams | theorems-bytype

# Original Author : David L. Johnson <dlj0@lehigh.edu>
# Probably broken by Jean-Marc Lasgouttes <Jean-Marc.Lasgouttes@inria.fr>
# modified and modularized by Emmanuel GUREGHIAN <gureghia@boston.bertin.fr>
# Tinkered with Sep. '07 by Paul Rubin <rubin@msu.edu>
# Modularized Jan 08 by Richard Heck <rgheck@comcast.net>
# Hacked June '09 by Paul Rubin <rubin@msu.edu> to use separate counters

Format 80

Requires	amsmath,amsthm

# We need separate counters for each theorem-like style.
Counter theorem
	GuiName Theorem
End
Counter corollary
	GuiName Corollary
End
Counter lemma
	GuiName Lemma
End
Counter proposition
	GuiName Proposition
End
Counter conjecture
	GuiName Conjecture
End
Counter fact
	GuiName Fact
End
Counter definition
	GuiName Definition
End
Counter example
	GuiName Example
End
Counter solution
	GuiName Solution
End
Counter problem
	GuiName Problem
End
Counter exercise
	GuiName Exercise
End
Counter remark
	GuiName Remark
End
Counter claim
	GuiName Claim
End

Input theorems-order.inc
Input theorems-ams-bytype.inc
Input theorems-starred.inc
Input theorems-proof.inc
