#\DeclareLyXModule{Theorems (By Section)}
#DescriptionBegin
#Numbers theorems and the like by section.
#DescriptionEnd
#Requires: theorems-std | theorems-ams
#Excludes: theorems-chap

# Author: Richard Heck <rgheck@comcast.net>
# Tweaked by Paul Rubin <rubin@msu.edu> June '09 (added theoremstyle)

Format 11

Counter theorem
	Within         section
End

Style Theorem
	Preamble
		\theoremstyle{plain}
		\newtheorem{thm}{Theorem}[section]
	EndPreamble
End
