#\DeclareLyXModule{Theorems (By Section)}
#DescriptionBegin
#Numbers theorems and the like by section.
#DescriptionEnd
#Requires: theorems-std | theorems-ams
#Excludes: theorems-chap

# Author: Richard Heck <rgheck@comcast.net>

Format 14

Counter theorem
	Within         section
End

Style Theorem
	Preamble
		\newtheorem{thm}{\protect\theoremname}[section]
	EndPreamble
	LangPreamble
		\providecommand{\theoremname}{_(Theorem)}
	EndLangPreamble
	BabelPreamble
		\addto\captions$$lang{\renewcommand{\theoremname}{_(Theorem)}}
	EndBabelPreamble
End
