# Reference prefixes for theorem environments

Format 59

ModifyStyle Theorem
	RefPrefix thm
End

ModifyStyle Corollary
	RefPrefix cor
End

ModifyStyle Lemma
	RefPrefix lem
End

ModifyStyle Proposition
	RefPrefix prop
End

ModifyStyle Conjecture
	RefPrefix conj
End

ModifyStyle Definition
	RefPrefix def
End

ModifyStyle Example
	RefPrefix exa
End

ModifyStyle Problem
	RefPrefix prob
End

ModifyStyle Exercise
	RefPrefix exer
End

ModifyStyle Solution
	RefPrefix solu
End

ModifyStyle Remark
	RefPrefix rem
End

ModifyStyle Claim
	RefPrefix claim
End

ModifyStyle Fact
	RefPrefix fact
End

ModifyStyle Criterion
	RefPrefix cri
End

ModifyStyle Algorithm
	RefPrefix alg
End

ModifyStyle Axiom
	RefPrefix axm
End

ModifyStyle Condition
	RefPrefix cond
End

ModifyStyle Note
	RefPrefix note
End

ModifyStyle Notation
	RefPrefix nota
End

ModifyStyle Summary
	RefPrefix sum
End

ModifyStyle Acknowledgement
	RefPrefix ack
End

ModifyStyle Conclusion
	RefPrefix conc
End

ModifyStyle Assumption
	RefPrefix assu
End


ModifyStyle Question
	RefPrefix que
End
