#\DeclareLyXModule{AMS Theorems}
#\DeclareCategory{Maths}
#DescriptionBegin
#Defines theorem environments and the proof environment using the extended 
#AMS machinery. Both numbered and unnumbered types are provided. By default, 
#the theorems are numbered consecutively throughout the document. This can be
#changed by loading one of the 'Theorems (Numbered by ...)' modules.
#DescriptionEnd
#Excludes: theorems-std | theorems-bytype | theorems-ams-bytype

# Original Author : David L. Johnson <dlj0@lehigh.edu>
# Probably broken by Jean-Marc Lasgouttes <Jean-Marc.Lasgouttes@inria.fr>
# modified and modularized by Emmanuel GUREGHIAN <gureghia@boston.bertin.fr>
# Tinkered with Sep. '07 by Paul Rubin <rubin@msu.edu>
# Modularized Jan 08 by Richard Kimberly Heck <rikiheck@lyx.org>
# Edited sep '22 by Udi Fogiel <udifoglle@gmail.com>

Format 99

Counter theorem
	GuiName Theorem
	LaTeXName thm
End

Input theorems.inc
Input theorems-proof.inc

Style Theorem
	Requires              amsthm
End

Style Theorem*
	Requires              amsthm
End
