# Independent label counters for "Numbered By Type" theorem modules

ModifyStyle Corollary
	LabelString           "Corollary \thecorollary."
	LabelCounter          corollary
End


ModifyStyle Lemma
	LabelString           "Lemma \thelemma."
	LabelCounter          lemma
End


ModifyStyle Proposition
	LabelString           "Proposition \theproposition."
	LabelCounter          proposition
End


ModifyStyle Conjecture
	LabelString           "Conjecture \theconjecture."
	LabelCounter          conjecture
End


ModifyStyle Fact
	LabelString           "Fact \thefact."
	LabelCounter          fact
End


ModifyStyle Definition
	LabelString           "Definition \thedefinition."
	LabelCounter          definition
End


ModifyStyle Example
	LabelString           "Example \theexample."
	LabelCounter          example
End


ModifyStyle Problem
	LabelString           "Problem \theproblem."
	LabelCounter          problem
End


ModifyStyle Exercise
	LabelString           "Exercise \theexercise."
	LabelCounter          exercise
End


ModifyStyle Solution
	LabelString           "Solution \thesolution."
	LabelCounter          solution
End


ModifyStyle Remark
	LabelString           "Remark \theremark."
	LabelCounter          remark
End


ModifyStyle Claim
	LabelString           "Claim \theclaim."
	LabelCounter          claim
End

ModifyStyle Criterion
	LabelString           "Criterion \thecriterion."
	LabelCounter          criterion
End

ModifyStyle Algorithm
	LabelString           "Algorithm \thealgorithm."
	LabelCounter          algorithm
End


ModifyStyle Axiom
	LabelString           "Axiom \theaxiom."
	LabelCounter          axiom
End


ModifyStyle Condition
	LabelString           "Condition \thecondition."
	LabelCounter          condition
End


ModifyStyle Note
	LabelString           "Note \thenote."
	LabelCounter          note
End


ModifyStyle Notation
	LabelString           "Notation \thenotation."
	LabelCounter          notation
End


ModifyStyle Summary
	LabelString           "Summary \thesummary."
	LabelCounter          summary
End


ModifyStyle Acknowledgement
	LabelString           "Acknowledgement \theacknowledgement."
	LabelCounter          acknowledgement
End


ModifyStyle Conclusion
	LabelString           "Conclusion \theconclusion."
	LabelCounter          conclusion
End


ModifyStyle Assumption
	LabelString           "Assumption \theassumption."
	LabelCounter          assumption
End


ModifyStyle Question
	LabelString           "Question \thequestion."
	LabelCounter          question
End