#\DeclareLyXModule{Theorems (By Section)}
#DescriptionBegin
#Defines some theorem environments for use with non-AMS classes. The theorems are 
#numbered by section. 
#DescriptionEnd
#Excludes: Theorems (AMS, By Section) | Theorems (AMS) | Theorems (By Chapter) | Theorems

# Author: Richard Heck <rgheck@comcast.net>
# Adapted from amsmaths.inc

Format 6

Counter
	Name           theorem
	Within         section
End

Input theorems.inc
