# Theorem-like counters, extended, separately for each type of theorem

Format 90
Counter criterion
	GuiName Criterion
End
Counter algorithm
	GuiName Algorithm
	LaTeXName lyxalgorithm
End
Counter axiom
	GuiName Axiom
	LaTeXName ax
End
Counter condition
	GuiName Condition
End
Counter note
	GuiName Note
End
Counter notation
	GuiName Notation
End
Counter summary
	GuiName Summary
End
Counter acknowledgement
	GuiName Acknowledgement
End
Counter conclusion
	GuiName Conclusion
End
Counter assumption
	GuiName Assumption
End
Counter question
	GuiName Question
End
