# Sets the order of the main theorem environments
# Author: Richard Heck

Format 7

Style Theorem
	CopyStyle Theorem*
End

Style Corollary
	CopyStyle Corollary*
End

Style Lemma
	CopyStyle Lemma*
End

Style Proposition
	CopyStyle Proposition*
End

Style Conjecture
	CopyStyle Conjecture*
End

Style Definition
	CopyStyle Definition*
End

Style Example
	CopyStyle Example*
End

Style Problem
	CopyStyle Problem*
End

Style Exercise
	CopyStyle Exercise*
End

Style Remark
	CopyStyle Remark*
End

Style Claim
	CopyStyle Claim*
End
