#\DeclareLyXModule{AMS Theorems (Extended, Numbered by Type)}
#\DeclareCategory{Maths}
#DescriptionBegin
#Defines some additional theorem environments for use with the
#AMS theorems packages. Includes Criterion, Algorithm, Axiom,
#Condition, Note, Notation, Summary, Acknowledgement, Conclusion,
#Assumption, and Case, in both numbered and non-numbered forms.
#Contrary to the plain AMS-Extended module, the different theorem 
#types provided here each have a separate counter (e.g., criterion 1,
#criterion 2, axiom 1, assumption 1, criterion 3, ...,
#as opposed to criterion 1, criterion 2, axiom 3, assumption 4, ...).
#DescriptionEnd
#Requires: theorems-ams-bytype

# Original Author : David L. Johnson <dlj0@lehigh.edu>
# Probably broken by Jean-Marc Lasgouttes <Jean-Marc.Lasgouttes@inria.fr>
# modified and modularized by Emmanuel GUREGHIAN <gureghia@boston.bertin.fr>
# Tinkered with Sep. '07 by Paul Rubin <rubin@msu.edu>
# Modularized Jan 08 by Richard Heck <rgheck@comcast.net>
# Hacked June '09 by Paul Rubin <rubin@msu.edu> to use separate counters

Format 89

Requires	amsmath

# The environnements defined (regular and starred) are :
# - Criterion
# - Algorithm
# - Axiom
# - Condition
# - Note
# - Notation
# - Summary
# - Acknowledgement
# - Conclusion
# - Assumption
# - Question

# We need separate counters for each theorem-like style.
Counter criterion
	GuiName Criterion
End
Counter algorithm
	GuiName Algorithm
	LaTeXName lyxalgorithm
End
Counter axiom
	GuiName Axiom
	LaTeXName ax
End
Counter condition
	GuiName Condition
End
Counter note
	GuiName Note
End
Counter notation
	GuiName Notation
End
Counter summary
	GuiName Summary
End
Counter acknowledgement
	GuiName Acknowledgement
End
Counter conclusion
	GuiName Conclusion
End
Counter assumption
	GuiName Assumption
End
Counter question
	GuiName Question
End


Style Criterion
	CopyStyle             Theorem
	LatexName             criterion
	LabelString           "Criterion \thecriterion."
	Preamble
	  \theoremstyle{plain}
	  \newtheorem{criterion}{\protect\criterionname}
	EndPreamble
	LangPreamble
	  \providecommand{\criterionname}{_(Criterion)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\criterionname}{_(Criterion)}}
	EndBabelPreamble
	LabelCounter          criterion
	DocBookTag            para
	DocBookAttr           role='criterion'
	DocBookItemTag        ""
End

Style Criterion*
	CopyStyle             Theorem*
	LatexName             criterion*
	LabelString           "Criterion."
	Preamble
	  \theoremstyle{plain}
	  \newtheorem*{criterion*}{\protect\criterionname}
	EndPreamble
	LangPreamble
	  \providecommand{\criterionname}{_(Criterion)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\criterionname}{_(Criterion)}}
	EndBabelPreamble
	DocBookTag            para
	DocBookAttr           role='criterion'
	DocBookItemTag        ""
End


Style Algorithm
	CopyStyle             Theorem
	LatexName             lyxalgorithm
	LabelString           "Algorithm \thealgorithm."
	Preamble
	  \theoremstyle{plain}
	  \newtheorem{lyxalgorithm}{\protect\algorithmname}
	EndPreamble
	LangPreamble
	  \providecommand{\algorithmname}{_(Algorithm)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\algorithmname}{_(Algorithm)}}
	EndBabelPreamble
	LabelCounter          algorithm
	DocBookTag            para
	DocBookAttr           role='algorithm'
	DocBookItemTag        ""
End


Style Algorithm*
	CopyStyle             Theorem*
	LatexName             lyxalgorithm*
	LabelString           "Algorithm."
	Preamble
	  \theoremstyle{plain}
	  \newtheorem*{lyxalgorithm*}{\protect\algorithmname}
	EndPreamble
	LangPreamble
	  \providecommand{\algorithmname}{_(Algorithm)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\algorithmname}{_(Algorithm)}}
	EndBabelPreamble
	DocBookTag            para
	DocBookAttr           role='algorithm'
	DocBookItemTag        ""
End


Style Axiom
	CopyStyle             Theorem
	LatexName             ax
	LabelString           "Axiom \theaxiom."
	Preamble
	  \theoremstyle{plain}
	  \newtheorem{ax}{\protect\axiomname}
	EndPreamble
	LangPreamble
	  \providecommand{\axiomname}{_(Axiom)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\axiomname}{_(Axiom)}}
	EndBabelPreamble
	LabelCounter          axiom
	DocBookTag            para
	DocBookAttr           role='axiom'
	DocBookItemTag        ""
End


Style Axiom*
	CopyStyle             Theorem*
	LatexName             ax*
	LabelString           "Axiom."
	Preamble
	  \theoremstyle{plain}
	  \newtheorem*{ax*}{\protect\axiomname}
	EndPreamble
	LangPreamble
	  \providecommand{\axiomname}{_(Axiom)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\axiomname}{_(Axiom)}}
	EndBabelPreamble
	DocBookTag            para
	DocBookAttr           role='axiom'
	DocBookItemTag        ""
End


Style Condition
	CopyStyle             Definition
	LatexName             condition
	LabelString           "Condition \thecondition."
	Preamble
	  \theoremstyle{definition}
	  \newtheorem{condition}{\protect\conditionname}
	EndPreamble
	LangPreamble
	  \providecommand{\conditionname}{_(Condition)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\conditionname}{_(Condition)}}
	EndBabelPreamble
	LabelCounter          condition
	DocBookTag            para
	DocBookAttr           role='condition'
	DocBookItemTag        ""
End


Style Condition*
	CopyStyle             Definition*
	LatexName             condition*
	LabelString           "Condition."
	Preamble
	  \theoremstyle{definition}
	  \newtheorem*{condition*}{\protect\conditionname}
	EndPreamble
	LangPreamble
	  \providecommand{\conditionname}{_(Condition)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\conditionname}{_(Condition)}}
	EndBabelPreamble
	DocBookTag            para
	DocBookAttr           role='condition'
	DocBookItemTag        ""
End


Style Note
	CopyStyle             Remark
	LatexName             note
	LabelString           "Note \thenote."
	Preamble
	  \theoremstyle{remark}
	  \newtheorem{note}{\protect\notename}
	EndPreamble
	LangPreamble
	  \providecommand{\notename}{_(Note)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\notename}{_(Note)}}
	EndBabelPreamble
	LabelCounter          note
	DocBookTag            note
	DocBookItemTag        para
End


Style Note*
	CopyStyle             Remark*
	LatexName             note*
	LabelString           "Note."
	Preamble
	  \theoremstyle{remark}
	  \newtheorem*{note*}{\protect\notename}
	EndPreamble
	LangPreamble
	  \providecommand{\notename}{_(Note)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\notename}{_(Note)}}
	EndBabelPreamble
	DocBookTag            note
	DocBookItemTag        para
End


Style Notation
	CopyStyle             Remark
	LatexName             notation
	LabelString           "Notation \thenotation."
	Preamble
	  \theoremstyle{remark}
	  \newtheorem{notation}{\protect\notationname}
	EndPreamble
	LangPreamble
	  \providecommand{\notationname}{_(Notation)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\notationname}{_(Notation)}}
	EndBabelPreamble
	LabelCounter          notation
	DocBookTag            para
	DocBookAttr           role='notation'
	DocBookItemTag        ""
End


Style Notation*
	CopyStyle             Remark*
	LatexName             notation*
	LabelString           "Notation."
	Preamble
	  \theoremstyle{remark}
	  \newtheorem*{notation*}{\protect\notationname}
	EndPreamble
	LangPreamble
	  \providecommand{\notationname}{_(Notation)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\notationname}{_(Notation)}}
	EndBabelPreamble
	DocBookTag            para
	DocBookAttr           role='notation'
	DocBookItemTag        ""
End


Style Summary
	CopyStyle             Remark
	LatexName             summary
	LabelString           "Summary \thesummary."
	Preamble
	  \theoremstyle{remark}
	  \newtheorem{summary}{\protect\summaryname}
	EndPreamble
	LangPreamble
	  \providecommand{\summaryname}{_(Summary)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\summaryname}{_(Summary)}}
	EndBabelPreamble
	LabelCounter          summary
	DocBookTag            para
	DocBookAttr           role='summary'
	DocBookItemTag        ""
End


Style Summary*
	CopyStyle             Remark*
	LatexName             summary*
	LabelString           "Summary."
	Preamble
	  \theoremstyle{remark}
	  \newtheorem*{summary*}{\protect\summaryname}
	EndPreamble
	LangPreamble
	  \providecommand{\summaryname}{_(Summary)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\summaryname}{_(Summary)}}
	EndBabelPreamble
	DocBookTag            para
	DocBookAttr           role='summary'
	DocBookItemTag        ""
End


Style Acknowledgement
	CopyStyle             Remark
	LatexName             acknowledgement
	LabelString           "Acknowledgement \theacknowledgement."
	Preamble
	  \theoremstyle{remark}
	  \newtheorem{acknowledgement}{\protect\acknowledgementname}
	EndPreamble
	LangPreamble
	  \providecommand{\acknowledgementname}{_(Acknowledgement)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\acknowledgementname}{_(Acknowledgement)}}
	EndBabelPreamble
	LabelCounter          acknowledgement
	DocBookTag            para
	DocBookAttr           role='acknowledgement'
	DocBookItemTag        ""
End


Style Acknowledgement*
	CopyStyle             Remark*
	LatexName             acknowledgement*
	LabelString           "Acknowledgement."
	Preamble
	  \theoremstyle{remark}
	  \newtheorem*{acknowledgement*}{\protect\acknowledgementname}
	EndPreamble
	LangPreamble
	  \providecommand{\acknowledgementname}{_(Acknowledgement)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\acknowledgementname}{_(Acknowledgement)}}
	EndBabelPreamble
	DocBookTag            para
	DocBookAttr           role='acknowledgement'
	DocBookItemTag        ""
End


Style Conclusion
	CopyStyle             Remark
	LatexName             conclusion
	LabelString           "Conclusion \theconclusion."
	Preamble
	  \theoremstyle{remark}
	  \newtheorem{conclusion}{\protect\conclusionname}
	EndPreamble
	LangPreamble
	  \providecommand{\conclusionname}{_(Conclusion)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\conclusionname}{_(Conclusion)}}
	EndBabelPreamble
	LabelCounter          conclusion
	DocBookTag            para
	DocBookAttr           role='conclusion'
	DocBookItemTag        ""
End


Style Conclusion*
	CopyStyle             Remark*
	LatexName             conclusion*
	LabelString           "Conclusion."
	Preamble
	  \theoremstyle{remark}
	  \newtheorem*{conclusion*}{\protect\conclusionname}
	EndPreamble
	LangPreamble
	  \providecommand{\conclusionname}{_(Conclusion)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\conclusionname}{_(Conclusion)}}
	EndBabelPreamble
	DocBookTag            para
	DocBookAttr           role='conclusion'
	DocBookItemTag        ""
End


Style Assumption
	CopyStyle             Theorem
	LatexName             assumption
	LabelString           "Assumption \theassumption."
	Preamble
	  \theoremstyle{plain}
	  \newtheorem{assumption}{\protect\assumptionname}
	EndPreamble
	LangPreamble
	  \providecommand{\assumptionname}{_(Assumption)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\assumptionname}{_(Assumption)}}
	EndBabelPreamble
	LabelCounter          assumption
	DocBookTag            para
	DocBookAttr           role='assumption'
	DocBookItemTag        ""
End


Style Assumption*
	CopyStyle             Theorem*
	LatexName             assumption*
	LabelString           "Assumption."
	Preamble
	  \theoremstyle{plain}
	  \newtheorem*{assumption*}{\protect\assumptionname}
	EndPreamble
	LangPreamble
	  \providecommand{\assumptionname}{_(Assumption)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\assumptionname}{_(Assumption)}}
	EndBabelPreamble
	DocBookTag            para
	DocBookAttr           role='assumption'
	DocBookItemTag        ""
End

Style Question
	CopyStyle             Theorem
	DependsOn             Theorem
	LatexName             question
	LabelString           "Question \thequestion."
	Preamble
	  \theoremstyle{plain}
	  \newtheorem{question}{\protect\questionname}
	EndPreamble
	LangPreamble
	  \providecommand{\questionname}{_(Question)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\questionname}{_(Question)}}
	EndBabelPreamble
	LabelCounter          question
	DocBookTag            para
	DocBookAttr           role='question'
	DocBookItemTag        ""
End

Style Question*
	CopyStyle             Theorem*
	LatexName             question*
	LabelString           "Question."
	Preamble
	  \theoremstyle{plain}
	  \newtheorem*{question*}{\protect\questionname}
	EndPreamble
	LangPreamble
	  \providecommand{\questionname}{_(Question)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\questionname}{_(Question)}}
	EndBabelPreamble
	DocBookTag            para
	DocBookAttr           role='question'
	DocBookItemTag        ""
End

Input theorems-refprefix.inc
