#\DeclareLyXModule{AMS Theorems (Extended, Numbered by Type)}
#\DeclareCategory{Maths}
#DescriptionBegin
#Defines some additional theorem environments for use with the
#AMS theorems packages. Includes Criterion, Algorithm, Axiom,
#Condition, Note, Notation, Summary, Acknowledgement, Conclusion,
#Assumption, and Case, in both numbered and non-numbered forms.
#Contrary to the plain AMS-Extended module, the different theorem 
#types provided here each have a separate counter (e.g., criterion 1,
#criterion 2, axiom 1, assumption 1, criterion 3, ...,
#as opposed to criterion 1, criterion 2, axiom 3, assumption 4, ...).
#DescriptionEnd
#Requires: theorems-ams-bytype

# Original Author : David L. Johnson <dlj0@lehigh.edu>
# Probably broken by Jean-Marc Lasgouttes <Jean-Marc.Lasgouttes@inria.fr>
# modified and modularized by Emmanuel GUREGHIAN <gureghia@boston.bertin.fr>
# Tinkered with Sep. '07 by Paul Rubin <rubin@msu.edu>
# Modularized Jan 08 by Richard Kimberly Heck <rikiheck@lyx.org>
# Hacked June '09 by Paul Rubin <rubin@msu.edu> to use separate counters
# Edited sep '22 by Udi Fogiel <udifoglle@gmail.com>

Format 99

# The environnements defined (regular and starred) are :
# - Criterion
# - Algorithm
# - Axiom
# - Condition
# - Note
# - Notation
# - Summary
# - Acknowledgement
# - Conclusion
# - Assumption
# - Question

Input theorems-counters-extended-bytype.inc
Input theorems-extended.inc
Input theorems-labels.inc