#\DeclareLyXModule{Standard Theorems (Numbered by Section)}
#\DeclareCategory{Maths}
#DescriptionBegin
#Numbers theorems and the like by section (i.e., the counter is reset at
#each section start).
#DescriptionEnd
#Requires: theorems-std | theorems-ams
#Excludes: theorems-chap

# Author: Richard Kimberly Heck <rikiheck@lyx.org>

Format 95

Counter theorem
	GuiName Theorem
	Within section
	LaTeXName thm
End

Style Theorem
	Preamble
		\theoremstyle{plain}
		\newtheorem{thm}{\protect\theoremname}[section]
	EndPreamble
End
