#\DeclareLyXModule{Defines some theorem environments for use with non-AMS classes. The theorems are numbered within chapters of the document. This module should therefore be used only with document classes that define a chapter environment.}{Theorems (By Chapter)}

# Author: Richard Heck <rgheck@comcast.net>
# Adapted from amsmaths.inc

# The environnements defined are :
# - Theorem
# - Corollary
# - Lemma
# - Proposition
# - Conjecture
# - Definition
# - Example
# - Exercise
# - Remark
# - Note
# - Claim
# - Case
# - Conclusion
# - Fact

Format 5

Counter
	Name           theorem
	Within         chapter
End


Style Theorem
	Margin                First_Dynamic
	LatexType             Environment
	LatexName             thm
	NextNoIndent          1
	LabelSep              xx
	ParIndent             MMM
	ParSkip               0.4
	ItemSep               0.2
	TopSep                0.7
	BottomSep             0.7
	ParSep                0.3
	Align                 Block
	AlignPossible         Block, Left
	LabelType             Counter
	LabelCounter          theorem
	LabelString           "Theorem \thechapter.\thetheorem."
	Font
	  Shape               Italic
	  Size                Normal
	EndFont
	LabelFont
	  Shape               Up
	  Series              Bold
	EndFont
	Preamble
		\newtheorem{thm}{Theorem}[chapter]
	EndPreamble
End

Style Corollary
	CopyStyle             Theorem
	LatexName             cor
	LabelString           "Corollary \thechapter.\thetheorem."
	Preamble
	  \newtheorem{cor}[thm]{Corollary}
	EndPreamble
End

Style Lemma
	CopyStyle             Theorem
	LatexName             lem
	LabelString           "Lemma \thechapter.\thetheorem."
	Preamble
	  \newtheorem{lem}[thm]{Lemma}
	EndPreamble
End

Style Proposition
	CopyStyle             Theorem
	LatexName             prop
	LabelString           "Proposition \thechapter.\thetheorem."
	Preamble
	  \newtheorem{prop}[thm]{Proposition}
	EndPreamble
End

Style Conjecture
	CopyStyle             Theorem
	LatexName             conjecture
	LabelString           "Conjecture \thechapter.\thetheorem."
	Preamble
	  \newtheorem{conjecture}[thm]{Conjecture}
	EndPreamble
End

Style Fact
	CopyStyle             Theorem
	LatexName             fact
	LabelString           "Fact \thechapter.\thetheorem."
	Preamble
	  \newtheorem{fact}[thm]{Fact}
	EndPreamble
End

Style Definition
	CopyStyle             Theorem
	LatexName             defn
	LabelString           "Definition \thechapter.\thetheorem."
	Font
	  Shape               Up
	EndFont
	LabelFont
	  Shape               Up
	  Series              Bold
	EndFont
	Preamble
	  \newtheorem{defn}[thm]{Definition}
	EndPreamble
End


Style Example
	CopyStyle             Definition
	LatexName             example
	LabelString           "Example \thechapter.\thetheorem."
	Preamble
	  \newtheorem{example}[thm]{Example}
	EndPreamble
End


Style Exercise
	CopyStyle             Definition
	LatexName             xca
	LabelString           "Exercise \thechapter.\thetheorem."
	Preamble
	  \newtheorem{xca}{Exercise}
	EndPreamble
End


Style Remark
	CopyStyle             Theorem
	LatexName             rem
	LabelString           "Remark \thechapter.\thetheorem."
	Font
	  Shape               Up
	  Size                Normal
	EndFont
	LabelFont
	  Series              Medium
	  Shape               Italic
	EndFont
	Preamble
	  \newtheorem{rem}[thm]{Remark}
	EndPreamble
End


Style Claim
	CopyStyle             Remark
	LatexName             claim
	LabelString           "Claim \thechapter.\thetheorem."
	Preamble
	  \newtheorem{claim}[thm]{Claim}
	EndPreamble
End

Style Case
	CopyStyle             Remark
	LatexName             case
	LabelString           "Case \thechapter.\thetheorem."
	Preamble
	  \newtheorem{case}[thm]{Case}
	EndPreamble
End


Style Conclusion
	CopyStyle             Remark
	LatexName             conclusion
	LabelString           "Conclusion \thechapter.\thetheorem."
	Preamble
	  \newtheorem{conclusion}[thm]{Conclusion}
	EndPreamble
End

