#\DeclareLyXModule{Theorems (Order By Chapter)}
#DescriptionBegin
#Numbers theorems and the like by chapter. Use this module only with
#layouts that provide a chapter environment.
#DescriptionEnd
#Requires: theorems-std | theorems-ams

# Author: Richard Heck <rgheck@comcast.net>

Format 7

Counter
	Name           theorem
	Within         chapter
End

Style Theorem
	Preamble
		\ifx\thechapter\undefined
			\newtheorem{thm}{Theorem}
		\else
			\newtheorem{thm}{Theorem}[chapter]
		\fi
		
	EndPreamble
End
