#\DeclareLyXModule{Theorems (AMS, By Section)}
#DescriptionBegin
#Defines theorem environments and the proof environment for use with 
#non-AMS classes, using the extended AMS machinery. The theorems are 
#numbered within sections. 
#DescriptionEnd
#Excludes: Theorems (AMS) | Theorems | Theorems (By Chapter) | Theorems (By Section)

# Author: Richard Heck <rgheck@comcast.net>
# Adapted from amsdefs.inc and amsmaths.inc

Format 6

Requires	amsmath

Preamble
  \theoremstyle{plain}
  \newtheorem{thm}{Theorem}[section]
EndPreamble


Counter
	Name                 theorem
	Within               section
End


Input theorems-ams.inc
