#\DeclareLyXModule{Theorems}
#DescriptionBegin
#Defines some theorem environments for use with non-AMS classes. The theorems are 
#numbered consecutively throughout the document. 
#DescriptionEnd
#Excludes: Theorems (AMS, By Section) | Theorems (AMS) | Theorems (By Chapter) | Theorems (By Section)

# Author: Richard Heck <rgheck@comcast.net>
# Adapted from amsmaths.inc

Format 6

Counter
	Name                 theorem
End

Input theorems.inc

