#\DeclareLyXModule{Theorems (By Chapter)}
#DescriptionBegin
#Numbers theorems and the like by chapter. Use this module only with
#layouts that provide a chapter environment.
#DescriptionEnd
#Requires: theorems-std | theorems-ams
#Excludes: theorems-sec

# Author: Richard Heck <rgheck@comcast.net>

Format 10

Counter theorem
	Within         chapter
End

Style Theorem
	Preamble
		\ifx\thechapter\undefined
			\newtheorem{thm}{Theorem}
		\else
			\newtheorem{thm}{Theorem}[chapter]
		\fi
		
	EndPreamble
End
