# Theorem-like counters, separately for each type of theorem

Format 92
Counter theorem
	GuiName Theorem
	LaTeXName thm
End
Counter corollary
	GuiName Corollary
	LaTeXName cor
End
Counter lemma
	GuiName Lemma
	LaTeXName lem
End
Counter proposition
	GuiName Proposition
	LaTeXName prop
End
Counter conjecture
	GuiName Conjecture
End
Counter fact
	GuiName Fact
End
Counter definition
	GuiName Definition
	LaTeXName defn
End
Counter example
	GuiName Example
End
Counter problem
	GuiName Problem
End
Counter exercise
	GuiName Exercise
	LaTeXName xca
End
Counter solution
	GuiName Solution
	LaTeXName sol
End
Counter remark
	GuiName Remark
	LaTeXName rem
End
Counter claim
	GuiName Claim
End
