# Reference prefixes for theorem environments

Format 53

IfStyle Theorem
	RefPrefix thm
End

IfStyle Corollary
	RefPrefix cor
End

IfStyle Lemma
	RefPrefix lem
End

IfStyle Proposition
	RefPrefix prop
End

IfStyle Conjecture
	RefPrefix conj
End

IfStyle Definition
	RefPrefix def
End

IfStyle Example
	RefPrefix exa
End

IfStyle Problem
	RefPrefix prob
End

IfStyle Exercise
	RefPrefix exer
End

IfStyle Remark
	RefPrefix rem
End

IfStyle Claim
	RefPrefix claim
End

IfStyle Fact
	RefPrefix fact
End

IfStyle Criterion
	RefPrefix cri
End

IfStyle Algorithm
	RefPrefix alg
End

IfStyle Axiom
	RefPrefix axm
End

IfStyle Condition
	RefPrefix cond
End

IfStyle Note
	RefPrefix note
End

IfStyle Notation
	RefPrefix nota
End

IfStyle Summary
	RefPrefix sum
End

IfStyle Acknowledgement
	RefPrefix ack
End

IfStyle Conclusion
	RefPrefix conc
End

IfStyle Assumption
	RefPrefix assu
End
