#\DeclareLyXModule[amsmath.sty]{Defines theorem environments and the proof environment for use with non-AMS classes, using the extended AMS machinery. The theorems are numbered within sections.}{Theorems (AMS, By Section)}

# Author: Richard Heck <rgheck@comcast.net>
# Adapted from amsdefs.inc and amsmaths.inc

Format 5
Preamble
	\usepackage{amsmath}
  \theoremstyle{plain}
	\newtheorem{thm}{Theorem}[section]
EndPreamble


Counter
	Name                 theorem
	Within               section
End


Input theorems-ams.inc
