#\DeclareLyXModule{Defines some theorem environments for use with non-AMS classes. The theorems are numbered within chapters of the document. This module should therefore be used only with document classes that define a chapter environment.}{Theorems (By Chapter)}

# Author: Richard Heck <rgheck@comcast.net>
# Adapted from amsmaths.inc

Format 5

Counter
	Name           theorem
	Within         chapter
End

Input theorems.inc
