#\DeclareLyXModule{AMS Theorems (Extended, Numbered by Type within Chapters)}
#\DeclareCategory{Theorems}
#DescriptionBegin
#Defines some additional theorem environments for use with the
#AMS theorems packages. Includes Criterion, Algorithm, Axiom,
#Condition, Note, Notation, Summary, Acknowledgement, Conclusion,
#Assumption, and Case, in both numbered and non-numbered forms.
#Contrary to the plain AMS-Extended module, the different theorem
#types provided here each have a separate counter, restarted with each
#new chapter (e.g., criterion 1.1, criterion 1.2, axiom 1.1, assumption 1.1, #criterion 2.1, criterion 2.2, axiom 2.1..., as opposed to criterion 1,
#criterion 2, axiom 3, assumption 4...)
#DescriptionEnd
#Requires: theorems-ams-chap-bytype

# Original Author : David L. Johnson <dlj0@lehigh.edu>
# Probably broken by Jean-Marc Lasgouttes <Jean-Marc.Lasgouttes@inria.fr>
# modified and modularized by Emmanuel GUREGHIAN <gureghia@boston.bertin.fr>
# Tinkered with Sep. '07 by Paul Rubin <rubin@msu.edu>
# Modularized Jan 08 by Richard Heck <rgheck@comcast.net>
# Hacked June '09 by Paul Rubin <rubin@msu.edu> to use separate counters
# Chapter dependence added Oct '16 by Andrew Parsloe <aparsloe@clear.net.nz>

Format 72

Requires	amsmath

# The environnements defined (regular and starred) are :
# - Criterion
# - Algorithm
# - Axiom
# - Condition
# - Note
# - Notation
# - Summary
# - Acknowledgement
# - Conclusion
# - Assumption
# - Question

# We need separate counters for each theorem-like style.
Counter criterion
End
Counter algorithm
End
Counter axiom
End
Counter condition
End
Counter note
End
Counter notation
End
Counter summary
End
Counter acknowledgement
End
Counter conclusion
End
Counter assumption
End
Counter question
End


# additional (AMS-extended) environments

Style Criterion
	CopyStyle             Theorem
	LatexName             criterion
	LabelString           "Criterion \thechapter.\thecriterion."
	Preamble
	  \theoremstyle{plain}
    \ifx\thechapter\undefined
      \newtheorem{criterion}{\protect\criterionname}
    \else
      \newtheorem{criterion}{\protect\criterionname}[chapter]
    \fi
	EndPreamble
	LangPreamble
	  \providecommand{\criterionname}{_(Criterion)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\criterionname}{_(Criterion)}}
	EndBabelPreamble
	LabelCounter          criterion
End


Style Criterion*
	CopyStyle             Theorem*
	LatexName             criterion*
	LabelString           "Criterion."
	Preamble
	  \theoremstyle{plain}
	  \newtheorem*{criterion*}{\protect\criterionname}
	EndPreamble
	LangPreamble
	  \providecommand{\criterionname}{_(Criterion)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\criterionname}{_(Criterion)}}
	EndBabelPreamble
End


Style Algorithm
	CopyStyle             Theorem
	LatexName             lyxalgorithm
	LabelString           "Algorithm \thechapter.\thealgorithm."
	Preamble
	  \theoremstyle{plain}
    \ifx\thechapter\undefined
      \newtheorem{lyxalgorithm}{\protect\algorithmname}
    \else
      \newtheorem{lyxalgorithm}{\protect\algorithmname}[chapter]
    \fi
	EndPreamble
	LangPreamble
	  \providecommand{\algorithmname}{_(Algorithm)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\algorithmname}{_(Algorithm)}}
	EndBabelPreamble
	LabelCounter          algorithm
End


Style Algorithm*
	CopyStyle             Theorem*
	LatexName             lyxalgorithm*
	LabelString           "Algorithm."
	Preamble
	  \theoremstyle{plain}
	  \newtheorem*{lyxalgorithm*}{\protect\algorithmname}
	EndPreamble
	LangPreamble
	  \providecommand{\algorithmname}{_(Algorithm)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\algorithmname}{_(Algorithm)}}
	EndBabelPreamble
End


Style Axiom
	CopyStyle             Theorem
	LatexName             ax
	LabelString           "Axiom \thechapter.\theaxiom."
	Preamble
	  \theoremstyle{plain}
    \ifx\thechapter\undefined
      \newtheorem{ax}{\protect\axiomname}
    \else
      \newtheorem{ax}{\protect\axiomname}[chapter]
    \fi
	EndPreamble
	LangPreamble
	  \providecommand{\axiomname}{_(Axiom)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\axiomname}{_(Axiom)}}
	EndBabelPreamble
	LabelCounter          axiom
End


Style Axiom*
	CopyStyle             Theorem*
	LatexName             ax*
	LabelString           "Axiom."
	Preamble
	  \theoremstyle{plain}
	  \newtheorem*{ax*}{\protect\axiomname}
	EndPreamble
	LangPreamble
	  \providecommand{\axiomname}{_(Axiom)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\axiomname}{_(Axiom)}}
	EndBabelPreamble
End


Style Condition
	CopyStyle             Definition
	LatexName             condition
	LabelString           "Condition \thechapter.\thecondition."
	Preamble
	  \theoremstyle{definition}
    \ifx\thechapter\undefined
      \newtheorem{condition}{\protect\conditionname}
    \else
      \newtheorem{condition}{\protect\conditionname}[chapter]
    \fi
	EndPreamble
	LangPreamble
	  \providecommand{\conditionname}{_(Condition)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\conditionname}{_(Condition)}}
	EndBabelPreamble
	LabelCounter          condition
End


Style Condition*
	CopyStyle             Definition*
	LatexName             condition*
	LabelString           "Condition."
	Preamble
	  \theoremstyle{definition}
	  \newtheorem*{condition*}{\protect\conditionname}
	EndPreamble
	LangPreamble
	  \providecommand{\conditionname}{_(Condition)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\conditionname}{_(Condition)}}
	EndBabelPreamble
End


Style Note
	CopyStyle             Remark
	LatexName             note
	LabelString           "Note \thechapter.\thenote."
	Preamble
	  \theoremstyle{remark}
    \ifx\thechapter\undefined
      \newtheorem{note}{\protect\notename}
    \else
      \newtheorem{note}{\protect\notename}[chapter]
    \fi
	EndPreamble
	LangPreamble
	  \providecommand{\notename}{_(Note)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\notename}{_(Note)}}
	EndBabelPreamble
	LabelCounter          note
End


Style Note*
	CopyStyle             Remark*
	LatexName             note*
	LabelString           "Note."
	Preamble
	  \theoremstyle{remark}
	  \newtheorem*{note*}{\protect\notename}
	EndPreamble
	LangPreamble
	  \providecommand{\notename}{_(Note)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\notename}{_(Note)}}
	EndBabelPreamble
End


Style Notation
	CopyStyle             Remark
	LatexName             notation
	LabelString           "Notation \thechapter.\thenotation."
	Preamble
	  \theoremstyle{remark}
    \ifx\thechapter\undefined
      \newtheorem{notation}{\protect\notationname}
    \else
      \newtheorem{notation}{\protect\notationname}[chapter]
    \fi
	EndPreamble
	LangPreamble
	  \providecommand{\notationname}{_(Notation)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\notationname}{_(Notation)}}
	EndBabelPreamble
	LabelCounter          notation
End


Style Notation*
	CopyStyle             Remark*
	LatexName             notation*
	LabelString           "Notation."
	Preamble
	  \theoremstyle{remark}
	  \newtheorem*{notation*}{\protect\notationname}
	EndPreamble
	LangPreamble
	  \providecommand{\notationname}{_(Notation)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\notationname}{_(Notation)}}
	EndBabelPreamble
End


Style Summary
	CopyStyle             Remark
	LatexName             summary
	LabelString           "Summary \thechapter.\thesummary."
	Preamble
	  \theoremstyle{remark}
    \ifx\thechapter\undefined
      \newtheorem{summary}{\protect\summaryname}
    \fi
    \else
      \newtheorem{summary}{\protect\summaryname}[chapter]
    \fi
	EndPreamble
	LangPreamble
	  \providecommand{\summaryname}{_(Summary)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\summaryname}{_(Summary)}}
	EndBabelPreamble
	LabelCounter          summary
End


Style Summary*
	CopyStyle             Remark*
	LatexName             summary*
	LabelString           "Summary."
	Preamble
	  \theoremstyle{remark}
	  \newtheorem*{summary*}{\protect\summaryname}
	EndPreamble
	LangPreamble
	  \providecommand{\summaryname}{_(Summary)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\summaryname}{_(Summary)}}
	EndBabelPreamble
End


Style Acknowledgement
	CopyStyle             Remark
	LatexName             acknowledgement
	LabelString           "Acknowledgement \thechapter.\theacknowledgement."
	Preamble
	  \theoremstyle{remark}
    \ifx\thechapter\undefined
      \newtheorem{acknowledgement}{\protect\acknowledgementname}
    \else
      \newtheorem{acknowledgement}{\protect\acknowledgementname}[chapter]
    \fi
	EndPreamble
	LangPreamble
	  \providecommand{\acknowledgementname}{_(Acknowledgement)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\acknowledgementname}{_(Acknowledgement)}}
	EndBabelPreamble
	LabelCounter          acknowledgement
End


Style Acknowledgement*
	CopyStyle             Remark*
	LatexName             acknowledgement*
	LabelString           "Acknowledgement."
	Preamble
	  \theoremstyle{remark}
	  \newtheorem*{acknowledgement*}{\protect\acknowledgementname}
	EndPreamble
	LangPreamble
	  \providecommand{\acknowledgementname}{_(Acknowledgement)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\acknowledgementname}{_(Acknowledgement)}}
	EndBabelPreamble
End


Style Conclusion
	CopyStyle             Remark
	LatexName             conclusion
	LabelString           "Conclusion \thechapter.\theconclusion."
	Preamble
	  \theoremstyle{remark}
    \ifx\thechapter\undefined
      \newtheorem{conclusion}{\protect\conclusionname}
    \else
      \newtheorem{conclusion}{\protect\conclusionname}[chapter]
    \fi
	EndPreamble
	LangPreamble
	  \providecommand{\conclusionname}{_(Conclusion)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\conclusionname}{_(Conclusion)}}
	EndBabelPreamble
	LabelCounter          conclusion
End


Style Conclusion*
	CopyStyle             Remark*
	LatexName             conclusion*
	LabelString           "Conclusion."
	Preamble
	  \theoremstyle{remark}
	  \newtheorem*{conclusion*}{\protect\conclusionname}
	EndPreamble
	LangPreamble
	  \providecommand{\conclusionname}{_(Conclusion)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\conclusionname}{_(Conclusion)}}
	EndBabelPreamble
End


Style Assumption
	CopyStyle             Theorem
	LatexName             assumption
	LabelString           "Assumption \thechapter.\theassumption."
	Preamble
	  \theoremstyle{plain}
    \ifx\thechapter\undefined
      \newtheorem{assumption}{\protect\assumptionname}
    \else
      \newtheorem{assumption}{\protect\assumptionname}[chapter]
    \fi
	EndPreamble
	LangPreamble
	  \providecommand{\assumptionname}{_(Assumption)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\assumptionname}{_(Assumption)}}
	EndBabelPreamble
	LabelCounter          assumption
End


Style Assumption*
	CopyStyle             Theorem*
	LatexName             assumption*
	LabelString           "Assumption."
	Preamble
	  \theoremstyle{plain}
	  \newtheorem*{assumption*}{\protect\assumptionname}
	EndPreamble
	LangPreamble
	  \providecommand{\assumptionname}{_(Assumption)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\assumptionname}{_(Assumption)}}
	EndBabelPreamble
End

Style Question
	CopyStyle             Theorem
	DependsOn             Theorem
	LatexName             question
	LabelString           "Question \thechapter.\thequestion."
	Preamble
	  \theoremstyle{plain}
    \ifx\thechapter\undefined
      \newtheorem{question}{\protect\questionname}
    \else
      \newtheorem{question}{\protect\questionname}[chapter]
    \fi
	EndPreamble
	LangPreamble
	  \providecommand{\questionname}{_(Question)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\questionname}{_(Question)}}
	EndBabelPreamble
	LabelCounter          question
End

Style Question*
	CopyStyle             Theorem*
	LatexName             question*
	LabelString           "Question."
	Preamble
	  \theoremstyle{plain}
	  \newtheorem*{question*}{\protect\questionname}
	EndPreamble
	LangPreamble
	  \providecommand{\questionname}{_(Question)}
	EndLangPreamble
	BabelPreamble
	  \addto\captions$$lang{\renewcommand{\questionname}{_(Question)}}
	EndBabelPreamble
End

Input theorems-refprefix.inc
