# Sets the order of the main theorem environments
# Author: Richard Heck

Format 35

Style Theorem
	CopyStyle	Theorem*
	DependsOn	Theorem*
	Preamble
	EndPreamble
End

Style Corollary
	CopyStyle	Corollary*
	DependsOn	Corollary*
	Preamble
	EndPreamble
End

Style Lemma
	CopyStyle	Lemma*
	DependsOn	Lemma*
	Preamble
	EndPreamble
End

Style Proposition
	CopyStyle	Proposition*
	DependsOn	Proposition*
	Preamble
	EndPreamble
End

Style Conjecture
	CopyStyle	Conjecture*
	DependsOn	Conjecture*
	Preamble
	EndPreamble
End

Style Definition
	CopyStyle	Definition*
	DependsOn	Definition*
	Preamble
	EndPreamble
End

Style Example
	CopyStyle	Example*
	DependsOn	Example*
	Preamble
	EndPreamble
End

Style Problem
	CopyStyle	Problem*
	DependsOn	Problem*
	Preamble
	EndPreamble
End

Style Exercise
	CopyStyle	Exercise*
	DependsOn	Exercise*
	Preamble
	EndPreamble
End

Style Remark
	CopyStyle	Remark*
	DependsOn	Remark*
	Preamble
	EndPreamble
End

Style Claim
	CopyStyle	Claim*
	DependsOn	Claim*
	Preamble
	EndPreamble
End
