#\DeclareLyXModule{Standard Theorems}
#\DeclareCategory{Maths}
#DescriptionBegin
#Defines some theorem environments for use with non-AMS classes. By default, 
#the theorems are numbered consecutively throughout the document. This can be
#changed by loading one of the 'Theorems (Numbered by ...)' modules.
#DescriptionEnd
#Excludes: theorems-ams | theorems-starred

# Author: Richard Heck <rgheck@comcast.net>

Format 82

Counter theorem
	GuiName Theorem
End

Input theorems.inc
Input theorems-proof.inc
Input theorems-proof-std.inc
