/**********************************************************************

	--- Qt Architect generated file ---

	File: formprintdialogdata.h
	Last generated: Fri Oct 6 13:10:28 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef FormPrintDialogData_included
#define FormPrintDialogData_included

#include <qwidget.h>
#include <qlabel.h>
#include <qradiobutton.h>
#include <qcheckbox.h>
#include <qpushbutton.h>
#include <qgroupbox.h>
#include <keditcl.h>
#include <qlineedit.h>
#include <qbuttongroup.h>

class FormPrintDialogData : public QWidget
{
    Q_OBJECT

public:

    FormPrintDialogData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~FormPrintDialogData();

public slots:


protected slots:

    virtual void clickedCancel();
    virtual void clickedBrowse();
    virtual void clickedPrint();

protected:
    QGroupBox* pagesGroupBox;
    QButtonGroup* pagesRadioGroup;
    QGroupBox* copies;
    QGroupBox* printToGroupBox;
    QButtonGroup* printToRadioGroup;
    QPushButton* print;
    QPushButton* cancel;
    QRadioButton* allpages;
    QRadioButton* evenpages;
    KIntLineEdit* from;
    QLabel* fromLabel;
    QLabel* toLabel;
    QRadioButton* oddpages;
    QRadioButton* toprinter;
    QRadioButton* tofile;
    QLineEdit* printername;
    QCheckBox* reverse;
    QLineEdit* filename;
    QCheckBox* sort;
    QPushButton* browse;
    KIntLineEdit* count;
    QLabel* countLabel;
    KIntLineEdit* to;

};

#endif // FormPrintDialogData_included
