/**********************************************************************

	--- Qt Architect generated file ---

	File: formindexdialogdata.h
	Last generated: Tue Oct 3 16:28:36 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef FormIndexDialogData_included
#define FormIndexDialogData_included

#include <qwidget.h>
#include <qlabel.h>
#include <qpushbutton.h>
#include <qlineedit.h>

class FormIndexDialogData : public QWidget
{
    Q_OBJECT

public:

    FormIndexDialogData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~FormIndexDialogData();

public slots:


protected slots:

    virtual void clickedCancel();
    virtual void clickedOK();

protected:
    QLabel* labelindex;
    QLineEdit* index;
    QPushButton* buttonOk;
    QPushButton* buttonCancel;

};

#endif // FormIndexDialogData_included
