# vi:filetype=python:expandtab:tabstop=2:shiftwidth=2

# file SConscript
#
# This file is part of LyX, the document processor.
# Licence details can be found in the file COPYING.
# 
# \author Bo Peng
# Full author contact details are available in file CREDITS.

Import('env')

print "Entering src/tex2lyx"

tex2lyx_env = env.Copy()
# the order is important here.
#tex2lyx_env.Prepend(CPPPATH = ['.', '#$BUILDDIR'])
tex2lyx_env.Append(LIBPATH = ['#$LOCALLIBPATH'])

tex2lyx_env.fileCopy('FloatList.C', '#$BUILDDIR/FloatList.C')
tex2lyx_env.fileCopy('Floating.C', '#$BUILDDIR/Floating.C')
tex2lyx_env.fileCopy('counters.C', '#$BUILDDIR/counters.C')
tex2lyx_env.fileCopy('lyxlex.C', '#$BUILDDIR/lyxlex.C')
tex2lyx_env.fileCopy('lyxlex_pimpl.C', '#$BUILDDIR/lyxlex_pimpl.C')
# for some reason I do not know, I have to copy the header files as well.
tex2lyx_env.fileCopy('lyxlayout.h', '#$BUILDDIR/lyxlayout.h')
tex2lyx_env.fileCopy('lyxlayout.C', '#$BUILDDIR/lyxlayout.C')
tex2lyx_env.fileCopy('lyxtextclass.h', '#$BUILDDIR/lyxtextclass.h')
tex2lyx_env.fileCopy('lyxtextclass.C', '#$BUILDDIR/lyxtextclass.C')

tex2lyx = tex2lyx_env.Program(
  target = 'tex2lyx',
  LIBS = ['supports'] + env['BOOST_LIBRARIES'] + env['SYSTEM_LIBS'],
  source = Split('''
    FloatList.C 
    Floating.C 
    counters.C 
    lyxlayout.C 
    lyxtextclass.C 
    lyxlex.C 
    lyxlex_pimpl.C
    boost.C 
    context.C 
    gettext.C 
    lengthcommon.C 
    lyxfont.C 
    texparser.C 
    tex2lyx.C 
    preamble.C 
    math.C 
    table.C 
    text.C
  ''')
)

# Return the program
Return('tex2lyx')

