uic AboutUi.ui -o AboutUi.h
uic AskForTextUi.ui -o AskForTextUi.h
uic BibitemUi.ui -o BibitemUi.h
uic BiblioUi.ui -o BiblioUi.h
uic BibtexAddUi.ui -o BibtexAddUi.h
uic BibtexUi.ui -o BibtexUi.h
uic BoxUi.ui -o BoxUi.h
uic BranchesUi.ui -o BranchesUi.h
uic BranchUi.ui -o BranchUi.h
uic BulletsUi.ui -o BulletsUi.h
uic ChangesUi.ui -o ChangesUi.h
uic CharacterUi.ui -o CharacterUi.h
uic CitationUi.ui -o CitationUi.h
uic DelimiterUi.ui -o DelimiterUi.h
uic DocumentUi.ui -o DocumentUi.h
uic ErrorListUi.ui -o ErrorListUi.h
uic ERTUi.ui -o ERTUi.h
uic ExternalUi.ui -o ExternalUi.h
uic FloatUi.ui -o FloatUi.h
uic FontUi.ui -o FontUi.h
uic GraphicsUi.ui -o GraphicsUi.h
uic IncludeUi.ui -o IncludeUi.h
uic LanguageUi.ui -o LanguageUi.h
uic LaTeXUi.ui -o LaTeXUi.h
uic LogUi.ui -o LogUi.h
uic MarginsUi.ui -o MarginsUi.h
uic MathMatrixUi.ui -o MathMatrixUi.h
uic MathsUi.ui -o MathsUi.h
uic NoteUi.ui -o NoteUi.h
uic NumberingUi.ui -o NumberingUi.h
uic PageLayoutUi.ui -o PageLayoutUi.h
uic ParagraphUi.ui -o ParagraphUi.h
uic PDFSupportUi.ui -o PDFSupportUi.h
uic PreambleUi.ui -o PreambleUi.h
uic PrefColorsUi.ui -o PrefColorsUi.h
uic PrefConvertersUi.ui -o PrefConvertersUi.h
uic PrefDateUi.ui -o PrefDateUi.h
uic PrefDisplayUi.ui -o PrefDisplayUi.h
uic PrefFileformatsUi.ui -o PrefFileformatsUi.h
uic PrefIdentityUi.ui -o PrefIdentityUi.h
uic PrefLanguageUi.ui -o PrefLanguageUi.h
uic PrefLatexUi.ui -o PrefLatexUi.h
uic PrefPathsUi.ui -o PrefPathsUi.h
uic PrefPlaintextUi.ui -o PrefPlaintextUi.h
uic PrefPrinterUi.ui -o PrefPrinterUi.h
uic PrefScreenFontsUi.ui -o PrefScreenFontsUi.h
uic PrefSpellcheckerUi.ui -o PrefSpellcheckerUi.h
uic PrefsUi.ui -o PrefsUi.h
uic PrefUi.ui -o PrefUi.h
uic PrintUi.ui -o PrintUi.h
uic RefUi.ui -o RefUi.h
uic SearchUi.ui -o SearchUi.h
uic SendtoUi.ui -o SendtoUi.h
uic ShowFileUi.ui -o ShowFileUi.h
uic SpellcheckerUi.ui -o SpellcheckerUi.h
uic TabularCreateUi.ui -o TabularCreateUi.h
uic TabularUi.ui -o TabularUi.h
uic TexinfoUi.ui -o TexinfoUi.h
uic TextLayoutUi.ui -o TextLayoutUi.h
uic ThesaurusUi.ui -o ThesaurusUi.h
uic TocUi.ui -o TocUi.h
uic VSpaceUi.ui -o VSpaceUi.h
uic WrapUi.ui -o WrapUi.h

