uic BranchesUi.ui -o BranchesUi.h
uic LaTeXUi.ui -o LaTeXUi.h
uic MathsUi.ui -o MathsUi.h
uic PageLayoutUi.ui -o PageLayoutUi.h
uic QAskForTextUi.ui -o QAskForTextUi.h
uic QBibtexUi.ui -o QBibtexUi.h
uic QChangesUi.ui -o QChangesUi.h
uic QCitationFindUi.ui -o QCitationFindUi.h
uic QERTUi.ui -o QERTUi.h
uic QGraphicsUi.ui -o QGraphicsUi.h
uic QLogUi.ui -o QLogUi.h
uic QNoteUi.ui -o QNoteUi.h
uic QPrefColorsUi.ui -o QPrefColorsUi.h
uic QPrefCygwinPathUi.ui -o QPrefCygwinPathUi.h
uic QPrefFileformatsUi.ui -o QPrefFileformatsUi.h
uic QPrefLanguageUi.ui -o QPrefLanguageUi.h
uic QPrefPrinterUi.ui -o QPrefPrinterUi.h
uic QPrefSpellcheckerUi.ui -o QPrefSpellcheckerUi.h
uic QRefUi.ui -o QRefUi.h
uic QShowFileUi.ui -o QShowFileUi.h
uic QTabularUi.ui -o QTabularUi.h
uic QTocUi.ui -o QTocUi.h
uic QWrapUi.ui -o QWrapUi.h
uic BulletsUi.ui -o BulletsUi.h
uic PreambleUi.ui -o PreambleUi.h
uic QBibitemUi.ui -o QBibitemUi.h
uic QBoxUi.ui -o QBoxUi.h
uic QCharacterUi.ui -o QCharacterUi.h
uic QDelimiterUi.ui -o QDelimiterUi.h
uic QDocumentUi.ui -o QDocumentUi.h
uic QExternalUi.ui -o QExternalUi.h
uic QIncludeUi.ui -o QIncludeUi.h
uic QMathUi.ui -o QMathUi.h
uic QParagraphUi.ui -o QParagraphUi.h
uic QPrefConvertersUi.ui -o QPrefConvertersUi.h
uic QPrefDateUi.ui -o QPrefDateUi.h
uic QPrefIdentityUi.ui -o QPrefIdentityUi.h
uic QPrefLatexUi.ui -o QPrefLatexUi.h
uic QPrefScreenFontsUi.ui -o QPrefScreenFontsUi.h
uic QPrefUi.ui -o QPrefUi.h
uic QSearchUi.ui -o QSearchUi.h
uic QSpellcheckerUi.ui -o QSpellcheckerUi.h
uic QTexinfoUi.ui -o QTexinfoUi.h
uic QURLUi.ui -o QURLUi.h
uic TextLayoutUi.ui -o TextLayoutUi.h
uic BiblioUi.ui -o BiblioUi.h
uic LanguageUi.ui -o LanguageUi.h
uic MarginsUi.ui -o MarginsUi.h
uic NumberingUi.ui -o NumberingUi.h
uic QAboutUi.ui -o QAboutUi.h
uic QBibtexAddUi.ui -o QBibtexAddUi.h
uic QBranchUi.ui -o QBranchUi.h
uic QCitationUi.ui -o QCitationUi.h
uic QErrorListUi.ui -o QErrorListUi.h
uic QFloatUi.ui -o QFloatUi.h
uic QIndexUi.ui -o QIndexUi.h
uic QMathMatrixUi.ui -o QMathMatrixUi.h
uic QPrefAsciiUi.ui -o QPrefAsciiUi.h
uic QPrefCopiersUi.ui -o QPrefCopiersUi.h
uic QPrefDisplayUi.ui -o QPrefDisplayUi.h
uic QPrefKeyboardUi.ui -o QPrefKeyboardUi.h
uic QPrefPathsUi.ui -o QPrefPathsUi.h
uic QPrefsUi.ui -o QPrefsUi.h
uic QPrintUi.ui -o QPrintUi.h
uic QSendtoUi.ui -o QSendtoUi.h
uic QTabularCreateUi.ui -o QTabularCreateUi.h
uic QThesaurusUi.ui -o QThesaurusUi.h
uic QVSpaceUi.ui -o QVSpaceUi.h

