#!/bin/sh
#
# Attempt to build listerrors (see examples/Literate.lyx) at build-time
#
# Author: Kayvan Sylvan <kayvan@sylvan.com>
#
# Assume notangle is on the path

if [ -r ../src/lyx ]
then
    lyx=../src/lyx
else
    # Assumed to be on the path
    lyx=lyx 
fi

$lyx --export nw examples/Literate.lyx
mv examples/Literate.nw Literate.nw
notangle -Rbuild-script Literate.nw | sh
