# vi:filetype=python:expandtab:tabstop=2:shiftwidth=2

# file SConscript
#
# This file is part of LyX, the document processor.
# Licence details can be found in the file COPYING.
# 
# \author Bo Peng
# Full author contact details are available in file CREDITS.

Import('env')

print "Entering src/graphics"

graphics = env.StaticLibrary(
  target = '$LOCALLIBPATH/graphics',
  source = Split('''
    GraphicsCache.C 
    GraphicsCacheItem.C 
    GraphicsConverter.C 
    GraphicsImage.C 
    GraphicsLoader.C 
    GraphicsParams.C 
    LoaderQueue.C 
    GraphicsTypes.C 
    PreviewImage.C 
    PreviewLoader.C 
    Previews.C
  ''')
)

# return the library
Return('graphics')
