# vi:filetype=python:expandtab:tabstop=2:shiftwidth=2

# file SConscript
#
# This file is part of LyX, the document processor.
# Licence details can be found in the file COPYING.
# 
# \author Bo Peng
# Full author contact details are available in file CREDITS.

Import('boostenv')

print 'Entering boost/libs/filesystem/src...'

filesystem = boostenv.StaticLibrary(
  target = '$LOCALLIBPATH/boost_filesystem',
  source = Split('''
    convenience.cpp
    exception.cpp
    operations_posix_windows.cpp
    path_posix_windows.cpp
  ''')
)

# Return the library
Return('filesystem')
