//#include "libs/regex/src/cpp_regex_traits.cpp"
//#include "libs/regex/src/c_regex_traits.cpp"
#include "libs/regex/src/cregex.cpp"
#include "libs/regex/src/fileiter.cpp"
//#include "libs/regex/src/instances.cpp"
#include "libs/regex/src/regex.cpp"
#include "libs/regex/src/regex_raw_buffer.cpp"
#include "libs/regex/src/regex_traits_defaults.cpp"
#include "libs/regex/src/w32_regex_traits.cpp"
#include "libs/regex/src/posix_api.cpp"
#include "libs/regex/src/wide_posix_api.cpp"
#include "libs/regex/src/regex_debug.cpp"
#include "libs/regex/src/winstances.cpp"

#include "libs/signals/src/connection.cpp"
#include "libs/signals/src/named_slot_map.cpp"
#include "libs/signals/src/signal_base.cpp"
#include "libs/signals/src/slot.cpp"
#include "libs/signals/src/trackable.cpp"

