// This -*- C++ -*- file was created automatically.
// Don't change it!  [asierra18jan96]
// Why? [andre]

#ifndef SYMBOL_DEF
#define SYMBOL_DEF 

enum Math_Symbols_enum {
// Accents
	LM_acute          = '\'',
	LM_grave          =  '`',
	LM_hat            = '^',
	LM_tilde          = '~',
	LM_dot            = '.',
	LM_bar            = '-',

	LM_quad           = 4,
	LM_qquad          = 5,

/// Symbols that don't exist in X11 symbol font but that we fake
	LM_not            = 10,

// Symbols that do exist in X11 symbol font
	LM_Gamma          = 0x47,
	LM_Delta          = 0x44,
	LM_Theta          = 0x51,
	LM_Lambda         = 0x4c,
	LM_Xi             = 0x58,
	LM_Pi             = 0x50,
	LM_Sigma          = 0x53,
	//LM_Upsilon      = 0x55,
	LM_Upsilon        = 0xa1,
	LM_Phi            = 0x46,
	LM_Psi            = 0x59,
	LM_Omega          = 0x57,
	LM_alpha          = 0x61,
	LM_beta           = 0x62,
	LM_gamma          = 0x67,
	LM_delta          = 0x64,
	LM_varepsilon     = 0x65,
	LM_eta            = 0x68,
	LM_theta          = 0x71,
	LM_vartheta       = 0x4a,
	LM_iota           = 0x69,
	LM_kappa          = 0x6b,
	LM_lambda         = 0x6c,
	LM_mu             = 0x6d,
	LM_nu             = 0x6e,
	LM_xi             = 0x78,
	LM_pi             = 0x70,
	LM_varpi          = 0x76,
	LM_rho            = 0x72,
	LM_sigma          = 0x73,
	LM_tau            = 0x74,
	LM_varsigma       = 0x56,
	LM_zeta           = 0x7a,
	LM_upsilon        = 0x75,
	LM_phi            = 0x66,
	LM_varphi         = 0x6a,
	LM_chi            = 0x63,
	LM_psi            = 0x79,
	LM_omega          = 0x77,
	LM_downarrow      = 0xaf,
	LM_leftarrow      = 0xac,
	LM_Downarrow      = 0xdf,
	LM_Leftarrow      = 0xdc,
	LM_rightarrow     = 0xae,
	LM_uparrow        = 0xad,
	LM_Rightarrow     = 0xde,
	LM_Uparrow        = 0xdd,
	LM_Leftrightarrow = 0xdb,
	LM_leftrightarrow = 0xab,
	LM_leq            = 0xa3,
	LM_geq            = 0xb3,
	LM_equiv          = 0xba,
	LM_subset         = 0xcc,
	LM_supset         = 0xc9,
	LM_approx         = 0xbb,
	LM_subseteq       = 0xcd,
	LM_supseteq       = 0xca,
	LM_cong           = 0x40,
	LM_neq            = 0xb9,
	LM_in             = 0xce,
	LM_propto         = 0xb5,
	LM_pm             = 0xb1,
	LM_cap            = 0xc7,
	LM_diamond        = 0xe0,
	LM_oplus          = 0xc5,
	LM_cup            = 0xc8,
	LM_times          = 0xb4,
	LM_otimes         = 0xc4,
	LM_div            = 0xb8,
	LM_oslash         = 0xc6,
	LM_cdot           = 0xd7,
	LM_wedge          = 0xd9,
	LM_bullet         = 0xb7,
	LM_sum            = 0xe5,
	LM_int            = 0xf2,
	LM_prod           = 0xd5,
	LM_nabla          = 0xd1,
	LM_partial        = 0xb6,
	LM_infty          = 0xa5,
	LM_prime          = 0xa2,
	//LM_emptyset     = 0xc6,
	LM_exists         = 0x24,
	LM_forall         = 0x22,
	LM_Re             = 0xc2,
	LM_Im             = 0xc1,
	LM_aleph          = 0xc0,
	LM_wp             = 0xc3,
	LM_bot            = 0x5e,
	LM_neg            = 0xd8,
	LM_sharp          = 0x23,
	LM_surd           = 0xd6,
	LM_diamondsuit    = 0xa8,
	LM_heartsuit      = 0xa9,
	LM_clubsuit       = 0xa7,
	LM_spadesuit      = 0xaa,
	LM_langle         = 0xe1,
	LM_lceil          = 0xe9,
	LM_lfloor         = 0xeb,
	LM_rangle         = 0xf1,
	LM_rceil          = 0xf9,
	LM_rfloor         = 0xfb,
	LM_mid            = 0x7c,
	LM_angle          = 0xd0,
	LM_vee            = 0xda,
	//LM_backslash '\\'
		
/// Symbols that don't exist in X11 symbol font
	LM_NoFont          = 256,
	LM_epsilon,  
	LM_hookleftarrow,
	LM_hookrightarrow,
	LM_updownarrow,
	LM_leftharpoonup,
	LM_rightharpoonup,
	LM_rightleftharpoons,
	LM_Updownarrow,
	LM_leftharpoondown,
	LM_rightharpoondown,
	LM_mapsto,
	LM_Longleftarrow,
	LM_Longrightarrow,
	LM_Longleftrightarrow,
	LM_longleftrightarrow,
	LM_longleftarrow,
	LM_longrightarrow,
	LM_longmapsto,
	LM_nwarrow,
	LM_nearrow,
	LM_swarrow,
	LM_searrow,
	LM_models,
	LM_prec,
	LM_succ,
	LM_sim,
	LM_perp,
	LM_preceq,
	LM_succeq,
	LM_simeq,
	LM_ll,
	LM_gg,
	LM_asymp,
	LM_parallel,
	LM_smile,
	LM_frown,
	LM_sqsubseteq,
	LM_sqsupseteq,
	LM_doteq,
	LM_ni,
	LM_notin,
	LM_vdash,
	LM_dashv,
	LM_bowtie,
	LM_mp,
	LM_bigtriangleup,
	LM_ominus,
	LM_uplus,
	LM_bigtriangledown,
	LM_sqcap,
	LM_triangleright,
	LM_sqcup,
	LM_triangleleft,
	LM_odot,
	LM_star,
	LM_amalg,
	LM_bigcirc,
	LM_setminus,
	LM_dagger,
	LM_circ,
	LM_wr,
	LM_ddagger,
	LM_oint,
	LM_coprod,
	LM_bigsqcup,
	LM_bigotimes,
	LM_bigodot,
	LM_bigoplus,
	LM_bigcap,
	LM_bigcup,
	LM_biguplus,
	LM_bigvee,
	LM_bigwedge,
	LM_ell,
	LM_imath,
	LM_jmath,
	LM_hbar,
	LM_top,
	LM_Vert,
	LM_flat,
	LM_natural,
	LM_triangle,
	LM_widehat,
	LM_widetilde,
	LM_underline,
	LM_overline,
	LM_underbrace, 
	LM_overbrace,
	LM_overleftarrow,
	LM_overightarrow, 
	LM_ldots,
	LM_cdots,
	LM_vdots,
	LM_ddots,            
	LM_backslash,
	LM_emptyset,

/// Accents that don't exist in X11 symbol font
	LM_ddot,
	LM_check,
	LM_vec,
	LM_breve

};


#endif
