/**********************************************************************

	--- Qt Architect 1.4-6 generated file ---

	File: citationdlgdata.C
	Last generated: Tue Apr 3 00:57:49 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <gettext.h>

#include <qpixmap.h>
#include <qlayout.h>
#include "citationdlgdata.h"

#define Inherited QDialog

#include <qlabel.h>

CitationDialogData::CitationDialogData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, FALSE, 53248 )
{
	button_ok = new QPushButton( this, "button_ok" );
	button_ok->setGeometry( 51, 379, 47, 56 );
	button_ok->setMinimumSize( 0, 0 );
	button_ok->setMaximumSize( 32767, 32767 );
	connect( button_ok, SIGNAL(clicked()), SLOT(clicked_ok()) );
	button_ok->setFocusPolicy( QWidget::TabFocus );
	button_ok->setBackgroundMode( QWidget::PaletteBackground );
	button_ok->setFontPropagation( QWidget::NoChildren );
	button_ok->setPalettePropagation( QWidget::NoChildren );
	button_ok->setText( _("&OK") );
	button_ok->setAutoRepeat( false );
	button_ok->setAutoResize( false );
	button_ok->setToggleButton( false );
	button_ok->setDefault( false );
	button_ok->setAutoDefault( true );
	button_ok->setIsMenuButton( false );

	button_cancel = new QPushButton( this, "button_cancel" );
	button_cancel->setGeometry( 483, 379, 46, 56 );
	button_cancel->setMinimumSize( 0, 0 );
	button_cancel->setMaximumSize( 32767, 32767 );
	connect( button_cancel, SIGNAL(clicked()), SLOT(clicked_cancel()) );
	button_cancel->setFocusPolicy( QWidget::TabFocus );
	button_cancel->setBackgroundMode( QWidget::PaletteBackground );
	button_cancel->setFontPropagation( QWidget::NoChildren );
	button_cancel->setPalettePropagation( QWidget::NoChildren );
	button_cancel->setText( _("&Cancel") );
	button_cancel->setAutoRepeat( false );
	button_cancel->setAutoResize( false );
	button_cancel->setToggleButton( false );
	button_cancel->setDefault( false );
	button_cancel->setAutoDefault( false );
	button_cancel->setIsMenuButton( false );

	button_apply = new QPushButton( this, "button_apply" );
	button_apply->setGeometry( 195, 379, 46, 56 );
	button_apply->setMinimumSize( 0, 0 );
	button_apply->setMaximumSize( 32767, 32767 );
	connect( button_apply, SIGNAL(clicked()), SLOT(clicked_apply()) );
	button_apply->setFocusPolicy( QWidget::TabFocus );
	button_apply->setBackgroundMode( QWidget::PaletteBackground );
	button_apply->setFontPropagation( QWidget::NoChildren );
	button_apply->setPalettePropagation( QWidget::NoChildren );
	button_apply->setText( _("&Apply") );
	button_apply->setAutoRepeat( false );
	button_apply->setAutoResize( false );
	button_apply->setToggleButton( false );
	button_apply->setDefault( false );
	button_apply->setAutoDefault( true );
	button_apply->setIsMenuButton( false );

	button_restore = new QPushButton( this, "button_restore" );
	button_restore->setGeometry( 339, 379, 46, 56 );
	button_restore->setMinimumSize( 0, 0 );
	button_restore->setMaximumSize( 32767, 32767 );
	connect( button_restore, SIGNAL(clicked()), SLOT(clicked_restore()) );
	button_restore->setFocusPolicy( QWidget::TabFocus );
	button_restore->setBackgroundMode( QWidget::PaletteBackground );
	button_restore->setFontPropagation( QWidget::NoChildren );
	button_restore->setPalettePropagation( QWidget::NoChildren );
	button_restore->setText( _("&Restore") );
	button_restore->setAutoRepeat( false );
	button_restore->setAutoResize( false );
	button_restore->setToggleButton( false );
	button_restore->setDefault( false );
	button_restore->setAutoDefault( true );
	button_restore->setIsMenuButton( false );

	list_chosen = new QListBox( this, "list_chosen" );
	list_chosen->setGeometry( 79, 5, 209, 233 );
	list_chosen->setMinimumSize( 0, 0 );
	list_chosen->setMaximumSize( 32767, 32767 );
	connect( list_chosen, SIGNAL(highlighted(const char*)), SLOT(highlight_chosen_adaptor(const char*)) );
	list_chosen->setFocusPolicy( QWidget::StrongFocus );
	list_chosen->setBackgroundMode( QWidget::PaletteBase );
	list_chosen->setFontPropagation( QWidget::SameFont );
	list_chosen->setPalettePropagation( QWidget::SameFont );
	list_chosen->setFrameStyle( 51 );
	list_chosen->setLineWidth( 2 );
	list_chosen->setMidLineWidth( 0 );
	list_chosen->QFrame::setMargin( 0 );
	list_chosen->setDragSelect( true );
	list_chosen->setAutoScroll( true );
	list_chosen->setScrollBar( false );
	list_chosen->setAutoScrollBar( true );
	list_chosen->setBottomScrollBar( false );
	list_chosen->setAutoBottomScrollBar( true );
	list_chosen->setSmoothScrolling( true );
	list_chosen->setMultiSelection( false );
	list_chosen->setAutoUpdate( true );

	list_available = new QListBox( this, "list_available" );
	list_available->setGeometry( 367, 5, 208, 233 );
	list_available->setMinimumSize( 0, 0 );
	list_available->setMaximumSize( 32767, 32767 );
	connect( list_available, SIGNAL(highlighted(const char*)), SLOT(highlight_available_adaptor(const char*)) );
	connect( list_available, SIGNAL(selected(const char*)), SLOT(select_available_adaptor(const char*)) );
	list_available->setFocusPolicy( QWidget::StrongFocus );
	list_available->setBackgroundMode( QWidget::PaletteBase );
	list_available->setFontPropagation( QWidget::SameFont );
	list_available->setPalettePropagation( QWidget::SameFont );
	list_available->setFrameStyle( 51 );
	list_available->setLineWidth( 2 );
	list_available->setMidLineWidth( 0 );
	list_available->QFrame::setMargin( 0 );
	list_available->setDragSelect( true );
	list_available->setAutoScroll( true );
	list_available->setScrollBar( false );
	list_available->setAutoScrollBar( true );
	list_available->setBottomScrollBar( false );
	list_available->setAutoBottomScrollBar( true );
	list_available->setSmoothScrolling( true );
	list_available->setMultiSelection( false );
	list_available->setAutoUpdate( true );

	button_down = new QPushButton( this, "button_down" );
	button_down->setGeometry( 5, 86, 69, 76 );
	button_down->setMinimumSize( 0, 0 );
	button_down->setMaximumSize( 32767, 32767 );
	connect( button_down, SIGNAL(clicked()), SLOT(clicked_down()) );
	button_down->setFocusPolicy( QWidget::TabFocus );
	button_down->setBackgroundMode( QWidget::PaletteBackground );
	button_down->setFontPropagation( QWidget::NoChildren );
	button_down->setPalettePropagation( QWidget::NoChildren );
	button_down->setText( _("&Down") );
	button_down->setAutoRepeat( false );
	button_down->setAutoResize( false );
	button_down->setToggleButton( false );
	button_down->setDefault( false );
	button_down->setAutoDefault( true );
	button_down->setIsMenuButton( false );

	button_remove = new QPushButton( this, "button_remove" );
	button_remove->setGeometry( 293, 66, 69, 56 );
	button_remove->setMinimumSize( 0, 0 );
	button_remove->setMaximumSize( 32767, 32767 );
	connect( button_remove, SIGNAL(clicked()), SLOT(clicked_remove()) );
	button_remove->setFocusPolicy( QWidget::TabFocus );
	button_remove->setBackgroundMode( QWidget::PaletteBackground );
	button_remove->setFontPropagation( QWidget::NoChildren );
	button_remove->setPalettePropagation( QWidget::NoChildren );
	button_remove->setText( _("&Remove") );
	button_remove->setAutoRepeat( false );
	button_remove->setAutoResize( false );
	button_remove->setToggleButton( false );
	button_remove->setDefault( false );
	button_remove->setAutoDefault( true );
	button_remove->setIsMenuButton( false );

	button_up = new QPushButton( this, "button_up" );
	button_up->setGeometry( 5, 5, 69, 76 );
	button_up->setMinimumSize( 0, 0 );
	button_up->setMaximumSize( 32767, 32767 );
	connect( button_up, SIGNAL(clicked()), SLOT(clicked_up()) );
	button_up->setFocusPolicy( QWidget::TabFocus );
	button_up->setBackgroundMode( QWidget::PaletteBackground );
	button_up->setFontPropagation( QWidget::NoChildren );
	button_up->setPalettePropagation( QWidget::NoChildren );
	button_up->setText( _("&Up") );
	button_up->setAutoRepeat( false );
	button_up->setAutoResize( false );
	button_up->setToggleButton( false );
	button_up->setDefault( false );
	button_up->setAutoDefault( true );
	button_up->setIsMenuButton( false );

	button_add = new QPushButton( this, "button_add" );
	button_add->setGeometry( 293, 5, 69, 56 );
	button_add->setMinimumSize( 0, 0 );
	button_add->setMaximumSize( 32767, 32767 );
	connect( button_add, SIGNAL(clicked()), SLOT(clicked_add()) );
	button_add->setFocusPolicy( QWidget::TabFocus );
	button_add->setBackgroundMode( QWidget::PaletteBackground );
	button_add->setFontPropagation( QWidget::NoChildren );
	button_add->setPalettePropagation( QWidget::NoChildren );
	button_add->setText( _("&Add") );
	button_add->setAutoRepeat( false );
	button_add->setAutoResize( false );
	button_add->setToggleButton( false );
	button_add->setDefault( false );
	button_add->setAutoDefault( true );
	button_add->setIsMenuButton( false );

	QLabel* qtarch_label_after;
	qtarch_label_after = new QLabel( this, "label_after" );
	qtarch_label_after->setGeometry( 5, 271, 283, 15 );
	qtarch_label_after->setMinimumSize( 0, 15 );
	qtarch_label_after->setMaximumSize( 32767, 15 );
	qtarch_label_after->setFocusPolicy( QWidget::NoFocus );
	qtarch_label_after->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_label_after->setFontPropagation( QWidget::NoChildren );
	qtarch_label_after->setPalettePropagation( QWidget::NoChildren );
	qtarch_label_after->setFrameStyle( 0 );
	qtarch_label_after->setLineWidth( 1 );
	qtarch_label_after->setMidLineWidth( 0 );
	qtarch_label_after->QFrame::setMargin( 0 );
	qtarch_label_after->setText( _("Text after : ") );
	qtarch_label_after->setAlignment( 289 );
	qtarch_label_after->setMargin( -1 );

	line_after = new QLineEdit( this, "line_after" );
	line_after->setGeometry( 293, 243, 282, 71 );
	line_after->setMinimumSize( 0, 0 );
	line_after->setMaximumSize( 32767, 32767 );
	connect( line_after, SIGNAL(textChanged(const char*)), SLOT(after_changed(const char*)) );
	line_after->setFocusPolicy( QWidget::StrongFocus );
	line_after->setBackgroundMode( QWidget::PaletteBase );
	line_after->setFontPropagation( QWidget::NoChildren );
	line_after->setPalettePropagation( QWidget::NoChildren );
	line_after->setText( "" );
	line_after->setMaxLength( 32767 );
	line_after->setFrame( QLineEdit::Normal );
	line_after->setFrame( true );

	line_details = new QMultiLineEdit( this, "line_details" );
	line_details->setGeometry( 5, 319, 570, 55 );
	line_details->setMinimumSize( 0, 0 );
	line_details->setMaximumSize( 32767, 32767 );
	line_details->setFocusPolicy( QWidget::StrongFocus );
	line_details->setBackgroundMode( QWidget::PaletteBase );
	line_details->setFontPropagation( QWidget::SameFont );
	line_details->setPalettePropagation( QWidget::SameFont );
	line_details->setFrameStyle( 51 );
	line_details->setLineWidth( 2 );
	line_details->setMidLineWidth( 0 );
	line_details->QFrame::setMargin( 0 );
	line_details->insertLine( "" );
	line_details->setReadOnly( true );
	line_details->setOverwriteMode( false );
	line_details->setAutoUpdate( true );

	button_search = new QPushButton( this, "button_search" );
	button_search->setGeometry( 293, 127, 69, 55 );
	button_search->setMinimumSize( 0, 0 );
	button_search->setMaximumSize( 32767, 32767 );
	connect( button_search, SIGNAL(clicked()), SLOT(clicked_search()) );
	button_search->setFocusPolicy( QWidget::TabFocus );
	button_search->setBackgroundMode( QWidget::PaletteBackground );
	button_search->setFontPropagation( QWidget::NoChildren );
	button_search->setPalettePropagation( QWidget::NoChildren );
	button_search->setText( _("&Search") );
	button_search->setAutoRepeat( false );
	button_search->setAutoResize( false );
	button_search->setToggleButton( false );
	button_search->setDefault( false );
	button_search->setAutoDefault( true );
	button_search->setIsMenuButton( false );

	if (button_ok->sizeHint().width()!=-1)
		button_ok->setMinimumWidth(button_ok->sizeHint().width());
	if (button_ok->sizeHint().height()!=-1)
		button_ok->setMinimumHeight(button_ok->sizeHint().height());
	if (button_ok->sizeHint().width()!=-1)
		button_ok->setMaximumWidth(button_ok->sizeHint().width());
	if (button_ok->sizeHint().height()!=-1)
		button_ok->setMaximumHeight(button_ok->sizeHint().height());
	if (button_cancel->sizeHint().width()!=-1)
		button_cancel->setMinimumWidth(button_cancel->sizeHint().width());
	if (button_cancel->sizeHint().height()!=-1)
		button_cancel->setMinimumHeight(button_cancel->sizeHint().height());
	if (button_cancel->sizeHint().width()!=-1)
		button_cancel->setMaximumWidth(button_cancel->sizeHint().width());
	if (button_cancel->sizeHint().height()!=-1)
		button_cancel->setMaximumHeight(button_cancel->sizeHint().height());
	if (button_apply->sizeHint().width()!=-1)
		button_apply->setMinimumWidth(button_apply->sizeHint().width());
	if (button_apply->sizeHint().height()!=-1)
		button_apply->setMinimumHeight(button_apply->sizeHint().height());
	if (button_apply->sizeHint().width()!=-1)
		button_apply->setMaximumWidth(button_apply->sizeHint().width());
	if (button_apply->sizeHint().height()!=-1)
		button_apply->setMaximumHeight(button_apply->sizeHint().height());
	if (button_restore->sizeHint().width()!=-1)
		button_restore->setMinimumWidth(button_restore->sizeHint().width());
	if (button_restore->sizeHint().height()!=-1)
		button_restore->setMinimumHeight(button_restore->sizeHint().height());
	if (button_restore->sizeHint().width()!=-1)
		button_restore->setMaximumWidth(button_restore->sizeHint().width());
	if (button_restore->sizeHint().height()!=-1)
		button_restore->setMaximumHeight(button_restore->sizeHint().height());
	if (list_chosen->sizeHint().width()!=-1)
		list_chosen->setMinimumWidth(list_chosen->sizeHint().width());
	if (list_chosen->sizeHint().height()!=-1)
		list_chosen->setMinimumHeight(list_chosen->sizeHint().height());
	if (list_available->sizeHint().width()!=-1)
		list_available->setMinimumWidth(list_available->sizeHint().width());
	if (list_available->sizeHint().height()!=-1)
		list_available->setMinimumHeight(list_available->sizeHint().height());
	if (button_down->sizeHint().width()!=-1)
		button_down->setMinimumWidth(button_down->sizeHint().width());
	if (button_down->sizeHint().height()!=-1)
		button_down->setMinimumHeight(button_down->sizeHint().height());
	if (button_down->sizeHint().width()!=-1)
		button_down->setMaximumWidth(button_down->sizeHint().width());
	if (button_down->sizeHint().height()!=-1)
		button_down->setMaximumHeight(button_down->sizeHint().height());
	if (button_remove->sizeHint().width()!=-1)
		button_remove->setMinimumWidth(button_remove->sizeHint().width());
	if (button_remove->sizeHint().height()!=-1)
		button_remove->setMinimumHeight(button_remove->sizeHint().height());
	if (button_remove->sizeHint().width()!=-1)
		button_remove->setMaximumWidth(button_remove->sizeHint().width());
	if (button_remove->sizeHint().height()!=-1)
		button_remove->setMaximumHeight(button_remove->sizeHint().height());
	if (button_up->sizeHint().width()!=-1)
		button_up->setMinimumWidth(button_up->sizeHint().width());
	if (button_up->sizeHint().height()!=-1)
		button_up->setMinimumHeight(button_up->sizeHint().height());
	if (button_up->sizeHint().width()!=-1)
		button_up->setMaximumWidth(button_up->sizeHint().width());
	if (button_up->sizeHint().height()!=-1)
		button_up->setMaximumHeight(button_up->sizeHint().height());
	if (button_add->sizeHint().width()!=-1)
		button_add->setMinimumWidth(button_add->sizeHint().width());
	if (button_add->sizeHint().height()!=-1)
		button_add->setMinimumHeight(button_add->sizeHint().height());
	if (button_add->sizeHint().width()!=-1)
		button_add->setMaximumWidth(button_add->sizeHint().width());
	if (button_add->sizeHint().height()!=-1)
		button_add->setMaximumHeight(button_add->sizeHint().height());
	if (qtarch_label_after->sizeHint().width()!=-1)
		qtarch_label_after->setMinimumWidth(qtarch_label_after->sizeHint().width());
	if (qtarch_label_after->sizeHint().height()!=-1)
		qtarch_label_after->setMinimumHeight(qtarch_label_after->sizeHint().height());
	if (qtarch_label_after->sizeHint().width()!=-1)
		qtarch_label_after->setMaximumWidth(qtarch_label_after->sizeHint().width());
	if (qtarch_label_after->sizeHint().height()!=-1)
		qtarch_label_after->setMaximumHeight(qtarch_label_after->sizeHint().height());
	if (line_after->sizeHint().width()!=-1)
		line_after->setMinimumWidth(line_after->sizeHint().width());
	if (line_after->sizeHint().height()!=-1)
		line_after->setMinimumHeight(line_after->sizeHint().height());
	if (line_after->sizeHint().height()!=-1)
		line_after->setMaximumHeight(line_after->sizeHint().height());
	if (line_details->sizeHint().width()!=-1)
		line_details->setMinimumWidth(line_details->sizeHint().width());
	if (line_details->sizeHint().height()!=-1)
		line_details->setMinimumHeight(line_details->sizeHint().height());
	if (line_details->sizeHint().height()!=-1)
		line_details->setMaximumHeight(line_details->sizeHint().height());
	if (button_search->sizeHint().width()!=-1)
		button_search->setMinimumWidth(button_search->sizeHint().width());
	if (button_search->sizeHint().height()!=-1)
		button_search->setMinimumHeight(button_search->sizeHint().height());
	if (button_search->sizeHint().width()!=-1)
		button_search->setMaximumWidth(button_search->sizeHint().width());
	if (button_search->sizeHint().height()!=-1)
		button_search->setMaximumHeight(button_search->sizeHint().height());
	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	QBoxLayout* qtarch_layout_1_1 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_1, 4 );
	qtarch_layout_1_1->addStrut( 0 );
	QBoxLayout* qtarch_layout_1_1_1 = new QBoxLayout( QBoxLayout::TopToBottom, 5, NULL );
	qtarch_layout_1_1->addLayout( qtarch_layout_1_1_1, 1 );
	qtarch_layout_1_1_1->addStrut( 0 );
	qtarch_layout_1_1_1->addWidget( button_up, 1, 36 );
	qtarch_layout_1_1_1->addWidget( button_down, 1, 36 );
	qtarch_layout_1_1_1->addStretch( 1 );
	QBoxLayout* qtarch_layout_1_1_2 = new QBoxLayout( QBoxLayout::TopToBottom, 5, NULL );
	qtarch_layout_1_1->addLayout( qtarch_layout_1_1_2, 3 );
	qtarch_layout_1_1_2->addStrut( 0 );
	qtarch_layout_1_1_2->addWidget( list_chosen, 1, 36 );
	QBoxLayout* qtarch_layout_1_1_3 = new QBoxLayout( QBoxLayout::TopToBottom, 5, NULL );
	qtarch_layout_1_1->addLayout( qtarch_layout_1_1_3, 1 );
	qtarch_layout_1_1_3->addStrut( 0 );
	qtarch_layout_1_1_3->addWidget( button_add, 1, 36 );
	qtarch_layout_1_1_3->addWidget( button_remove, 1, 36 );
	qtarch_layout_1_1_3->addWidget( button_search, 1, 36 );
	qtarch_layout_1_1_3->addStretch( 1 );
	QBoxLayout* qtarch_layout_1_1_4 = new QBoxLayout( QBoxLayout::TopToBottom, 5, NULL );
	qtarch_layout_1_1->addLayout( qtarch_layout_1_1_4, 3 );
	qtarch_layout_1_1_4->addStrut( 0 );
	qtarch_layout_1_1_4->addWidget( list_available, 1, 36 );
	QBoxLayout* qtarch_layout_1_2 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2, 1 );
	qtarch_layout_1_2->addStrut( 0 );
	qtarch_layout_1_2->addWidget( qtarch_label_after, 1, 36 );
	qtarch_layout_1_2->addWidget( line_after, 1, 36 );
	QBoxLayout* qtarch_layout_1_3 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_3, 1 );
	qtarch_layout_1_3->addStrut( 0 );
	qtarch_layout_1_3->addWidget( line_details, 1, 36 );
	QBoxLayout* qtarch_layout_1_4 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_4, 1 );
	qtarch_layout_1_4->addStrut( 0 );
	qtarch_layout_1_4->addStretch( 1 );
	qtarch_layout_1_4->addWidget( button_ok, 1, 36 );
	qtarch_layout_1_4->addStretch( 2 );
	qtarch_layout_1_4->addWidget( button_apply, 1, 36 );
	qtarch_layout_1_4->addStretch( 2 );
	qtarch_layout_1_4->addWidget( button_restore, 1, 36 );
	qtarch_layout_1_4->addStretch( 2 );
	qtarch_layout_1_4->addWidget( button_cancel, 1, 36 );
	qtarch_layout_1_4->addStretch( 1 );
	resize( 580,440 );
	setMinimumSize( 200, 65 );
	setMaximumSize( 32767, 65 );
}


CitationDialogData::~CitationDialogData()
{
}
void CitationDialogData::clicked_ok()
{
}
void CitationDialogData::clicked_cancel()
{
}
void CitationDialogData::clicked_apply()
{
}
void CitationDialogData::clicked_restore()
{
}
void CitationDialogData::highlight_chosen_adaptor(const char*)
{
}
void CitationDialogData::highlight_available_adaptor(const char*)
{
}
void CitationDialogData::select_available_adaptor(const char*)
{
}
void CitationDialogData::clicked_down()
{
}
void CitationDialogData::clicked_remove()
{
}
void CitationDialogData::clicked_up()
{
}
void CitationDialogData::clicked_add()
{
}
void CitationDialogData::after_changed(const char*)
{
}
void CitationDialogData::clicked_search()
{
}
