/**********************************************************************

	--- Qt Architect 1.4-6 generated file ---

	File: copyrightdlgdata.C
	Last generated: Sat Mar 31 22:09:01 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <gettext.h>

#include <qpixmap.h>
#include <qlayout.h>
#include "copyrightdlgdata.h"

#define Inherited QDialog


CopyrightDialogData::CopyrightDialogData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 53248 )
{
	button_cancel = new QPushButton( this, "button_cancel" );
	button_cancel->setGeometry( 157, 343, 151, 107 );
	button_cancel->setMinimumSize( 0, 0 );
	button_cancel->setMaximumSize( 32767, 32767 );
	connect( button_cancel, SIGNAL(clicked()), SLOT(clickedOK()) );
	button_cancel->setFocusPolicy( QWidget::TabFocus );
	button_cancel->setBackgroundMode( QWidget::PaletteBackground );
	button_cancel->setFontPropagation( QWidget::NoChildren );
	button_cancel->setPalettePropagation( QWidget::NoChildren );
	button_cancel->setText( _("&Close") );
	button_cancel->setAutoRepeat( false );
	button_cancel->setAutoResize( false );
	button_cancel->setToggleButton( false );
	button_cancel->setDefault( true );
	button_cancel->setAutoDefault( true );
	button_cancel->setIsMenuButton( false );

	label_copyright = new QLabel( this, "label_copyright" );
	label_copyright->setGeometry( 5, 5, 455, 108 );
	label_copyright->setMinimumSize( 0, 0 );
	label_copyright->setMaximumSize( 32767, 32767 );
	label_copyright->setFocusPolicy( QWidget::NoFocus );
	label_copyright->setBackgroundMode( QWidget::PaletteBackground );
	label_copyright->setFontPropagation( QWidget::NoChildren );
	label_copyright->setPalettePropagation( QWidget::NoChildren );
	label_copyright->setFrameStyle( 50 );
	label_copyright->setLineWidth( 1 );
	label_copyright->setMidLineWidth( 0 );
	label_copyright->QFrame::setMargin( 1 );
	label_copyright->setText( "" );
	label_copyright->setAlignment( 1316 );
	label_copyright->setMargin( -1 );

	label_licence = new QLabel( this, "label_licence" );
	label_licence->setGeometry( 5, 118, 455, 107 );
	label_licence->setMinimumSize( 0, 0 );
	label_licence->setMaximumSize( 32767, 32767 );
	label_licence->setFocusPolicy( QWidget::NoFocus );
	label_licence->setBackgroundMode( QWidget::PaletteBackground );
	label_licence->setFontPropagation( QWidget::NoChildren );
	label_licence->setPalettePropagation( QWidget::NoChildren );
	label_licence->setFrameStyle( 50 );
	label_licence->setLineWidth( 1 );
	label_licence->setMidLineWidth( 0 );
	label_licence->QFrame::setMargin( 1 );
	label_licence->setText( "" );
	label_licence->setAlignment( 1316 );
	label_licence->setMargin( -1 );

	label_disclaimer = new QLabel( this, "label_disclaimer" );
	label_disclaimer->setGeometry( 5, 230, 455, 108 );
	label_disclaimer->setMinimumSize( 0, 0 );
	label_disclaimer->setMaximumSize( 32767, 32767 );
	label_disclaimer->setFocusPolicy( QWidget::NoFocus );
	label_disclaimer->setBackgroundMode( QWidget::PaletteBackground );
	label_disclaimer->setFontPropagation( QWidget::NoChildren );
	label_disclaimer->setPalettePropagation( QWidget::NoChildren );
	label_disclaimer->setFrameStyle( 50 );
	label_disclaimer->setLineWidth( 1 );
	label_disclaimer->setMidLineWidth( 0 );
	label_disclaimer->QFrame::setMargin( 1 );
	label_disclaimer->setText( "" );
	label_disclaimer->setAlignment( 1316 );
	label_disclaimer->setMargin( -1 );

	if (button_cancel->sizeHint().width()!=-1)
		button_cancel->setMinimumWidth(button_cancel->sizeHint().width());
	if (button_cancel->sizeHint().height()!=-1)
		button_cancel->setMinimumHeight(button_cancel->sizeHint().height());
	if (button_cancel->sizeHint().width()!=-1)
		button_cancel->setMaximumWidth(button_cancel->sizeHint().width());
	if (button_cancel->sizeHint().height()!=-1)
		button_cancel->setMaximumHeight(button_cancel->sizeHint().height());
	if (label_copyright->sizeHint().width()!=-1)
		label_copyright->setMinimumWidth(label_copyright->sizeHint().width());
	if (label_copyright->sizeHint().height()!=-1)
		label_copyright->setMinimumHeight(label_copyright->sizeHint().height());
	if (label_licence->sizeHint().width()!=-1)
		label_licence->setMinimumWidth(label_licence->sizeHint().width());
	if (label_licence->sizeHint().height()!=-1)
		label_licence->setMinimumHeight(label_licence->sizeHint().height());
	if (label_disclaimer->sizeHint().width()!=-1)
		label_disclaimer->setMinimumWidth(label_disclaimer->sizeHint().width());
	if (label_disclaimer->sizeHint().height()!=-1)
		label_disclaimer->setMinimumHeight(label_disclaimer->sizeHint().height());
	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	qtarch_layout_1->addWidget( label_copyright, 1, 36 );
	qtarch_layout_1->addWidget( label_licence, 1, 36 );
	qtarch_layout_1->addWidget( label_disclaimer, 1, 36 );
	QBoxLayout* qtarch_layout_1_4 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_4, 1 );
	qtarch_layout_1_4->addStrut( 0 );
	qtarch_layout_1_4->addStretch( 1 );
	qtarch_layout_1_4->addWidget( button_cancel, 1, 36 );
	qtarch_layout_1_4->addStretch( 1 );
	resize( 465,455 );
	setMinimumSize( 200, 65 );
	setMaximumSize( 32767, 65 );
}


CopyrightDialogData::~CopyrightDialogData()
{
}
void CopyrightDialogData::clickedOK()
{
}
