/**********************************************************************

	--- Qt Architect 1.4-6 generated file ---

	File: docbulletsdlgdata.C
	Last generated: Sat Mar 31 16:48:22 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <gettext.h>

#include <qpixmap.h>
#include <qlayout.h>
#include "docbulletsdlgdata.h"

#define Inherited QWidget


DocBulletsDialogData::DocBulletsDialogData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	resize( 545,460 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


DocBulletsDialogData::~DocBulletsDialogData()
{
}
