/**********************************************************************

	--- Qt Architect 1.4-6 generated file ---

	File: docdlgdata.h
	Last generated: Sat Feb 10 21:28:59 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef DocDialogData_included
#define DocDialogData_included

#include <qdialog.h>
#include "tabstack.h"
#include <qpushbutton.h>

class DocDialogData : public QDialog
{
    Q_OBJECT

public:

    DocDialogData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~DocDialogData();

public slots:


protected slots:

    virtual void ok_adaptor();
    virtual void restore_adaptor();
    virtual void apply_adaptor();
    virtual void cancel_adaptor();

protected:
    QPushButton* ok;
    QPushButton* apply;
    QPushButton* restore;
    QPushButton* cancel;
    TabStack* tabstack;

};

#endif // DocDialogData_included
