/**********************************************************************

	--- Qt Architect 1.4-6 generated file ---

	File: docextradlgdata.C
	Last generated: Sat Feb 10 23:32:07 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <gettext.h>

#include <qpixmap.h>
#include <qlayout.h>
#include "docextradlgdata.h"

#define Inherited QWidget

#include <qlabel.h>
#include <qgroupbox.h>

DocExtraDialogData::DocExtraDialogData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QGroupBox* qtarch_placementBox;
	qtarch_placementBox = new QGroupBox( this, "placementBox" );
	qtarch_placementBox->setGeometry( 5, 5, 625, 378 );
	qtarch_placementBox->setMinimumSize( 25, 30 );
	qtarch_placementBox->setMaximumSize( 32767, 32767 );
	qtarch_placementBox->setFocusPolicy( QWidget::NoFocus );
	qtarch_placementBox->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_placementBox->setFontPropagation( QWidget::NoChildren );
	qtarch_placementBox->setPalettePropagation( QWidget::NoChildren );
	qtarch_placementBox->setFrameStyle( 49 );
	qtarch_placementBox->setLineWidth( 1 );
	qtarch_placementBox->setMidLineWidth( 0 );
	qtarch_placementBox->QFrame::setMargin( 0 );
	qtarch_placementBox->setTitle( _("Float Placement") );
	qtarch_placementBox->setAlignment( 1 );

	first = new QComboBox( FALSE, qtarch_placementBox, "first" );
	first->setGeometry( 315, 5, 150, 65 );
	first->setMinimumSize( 0, 0 );
	first->setMaximumSize( 32767, 32767 );
	first->setFocusPolicy( QWidget::StrongFocus );
	first->setBackgroundMode( QWidget::PaletteBackground );
	first->setFontPropagation( QWidget::AllChildren );
	first->setPalettePropagation( QWidget::AllChildren );
	first->setSizeLimit( 10 );
	first->setAutoResize( false );
	first->setMaxCount( 2147483647 );
	first->setAutoCompletion( false );

	second = new QComboBox( FALSE, qtarch_placementBox, "second" );
	second->setGeometry( 315, 75, 150, 66 );
	second->setMinimumSize( 0, 0 );
	second->setMaximumSize( 32767, 32767 );
	second->setFocusPolicy( QWidget::StrongFocus );
	second->setBackgroundMode( QWidget::PaletteBackground );
	second->setFontPropagation( QWidget::AllChildren );
	second->setPalettePropagation( QWidget::AllChildren );
	second->setSizeLimit( 10 );
	second->setAutoResize( false );
	second->setMaxCount( 2147483647 );
	second->setAutoCompletion( false );

	third = new QComboBox( FALSE, qtarch_placementBox, "third" );
	third->setGeometry( 315, 146, 150, 65 );
	third->setMinimumSize( 0, 0 );
	third->setMaximumSize( 32767, 32767 );
	third->setFocusPolicy( QWidget::StrongFocus );
	third->setBackgroundMode( QWidget::PaletteBackground );
	third->setFontPropagation( QWidget::AllChildren );
	third->setPalettePropagation( QWidget::AllChildren );
	third->setSizeLimit( 10 );
	third->setAutoResize( false );
	third->setMaxCount( 2147483647 );
	third->setAutoCompletion( false );

	fourth = new QComboBox( FALSE, qtarch_placementBox, "fourth" );
	fourth->setGeometry( 315, 216, 150, 65 );
	fourth->setMinimumSize( 0, 0 );
	fourth->setMaximumSize( 32767, 32767 );
	fourth->setFocusPolicy( QWidget::StrongFocus );
	fourth->setBackgroundMode( QWidget::PaletteBackground );
	fourth->setFontPropagation( QWidget::AllChildren );
	fourth->setPalettePropagation( QWidget::AllChildren );
	fourth->setSizeLimit( 10 );
	fourth->setAutoResize( false );
	fourth->setMaxCount( 2147483647 );
	fourth->setAutoCompletion( false );

	ignore = new QCheckBox( qtarch_placementBox, "ignore" );
	ignore->setGeometry( 5, 286, 615, 87 );
	ignore->setMinimumSize( 0, 0 );
	ignore->setMaximumSize( 32767, 32767 );
	ignore->setFocusPolicy( QWidget::TabFocus );
	ignore->setBackgroundMode( QWidget::PaletteBackground );
	ignore->setFontPropagation( QWidget::NoChildren );
	ignore->setPalettePropagation( QWidget::NoChildren );
	ignore->setText( _("Ignore LaTeX placement rules") );
	ignore->setAutoRepeat( false );
	ignore->setAutoResize( false );
	ignore->setChecked( false );

	QLabel* qtarch_labelsectiondepth;
	qtarch_labelsectiondepth = new QLabel( this, "labelsectiondepth" );
	qtarch_labelsectiondepth->setGeometry( 5, 388, 153, 58 );
	qtarch_labelsectiondepth->setMinimumSize( 0, 0 );
	qtarch_labelsectiondepth->setMaximumSize( 32767, 32767 );
	qtarch_labelsectiondepth->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelsectiondepth->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelsectiondepth->setFontPropagation( QWidget::NoChildren );
	qtarch_labelsectiondepth->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelsectiondepth->setFrameStyle( 0 );
	qtarch_labelsectiondepth->setLineWidth( 1 );
	qtarch_labelsectiondepth->setMidLineWidth( 0 );
	qtarch_labelsectiondepth->QFrame::setMargin( 0 );
	qtarch_labelsectiondepth->setText( _("Section number depth :") );
	qtarch_labelsectiondepth->setAlignment( 289 );
	qtarch_labelsectiondepth->setMargin( -1 );

	QLabel* qtarch_labeltocdepth;
	qtarch_labeltocdepth = new QLabel( this, "labeltocdepth" );
	qtarch_labeltocdepth->setGeometry( 5, 451, 153, 58 );
	qtarch_labeltocdepth->setMinimumSize( 0, 0 );
	qtarch_labeltocdepth->setMaximumSize( 32767, 32767 );
	qtarch_labeltocdepth->setFocusPolicy( QWidget::NoFocus );
	qtarch_labeltocdepth->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labeltocdepth->setFontPropagation( QWidget::NoChildren );
	qtarch_labeltocdepth->setPalettePropagation( QWidget::NoChildren );
	qtarch_labeltocdepth->setFrameStyle( 0 );
	qtarch_labeltocdepth->setLineWidth( 1 );
	qtarch_labeltocdepth->setMidLineWidth( 0 );
	qtarch_labeltocdepth->QFrame::setMargin( 0 );
	qtarch_labeltocdepth->setText( _("Table of Contents depth :") );
	qtarch_labeltocdepth->setAlignment( 289 );
	qtarch_labeltocdepth->setMargin( -1 );

	QLabel* qtarch_labelPSDriver;
	qtarch_labelPSDriver = new QLabel( this, "labelPSDriver" );
	qtarch_labelPSDriver->setGeometry( 5, 514, 153, 58 );
	qtarch_labelPSDriver->setMinimumSize( 0, 0 );
	qtarch_labelPSDriver->setMaximumSize( 32767, 32767 );
	qtarch_labelPSDriver->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelPSDriver->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelPSDriver->setFontPropagation( QWidget::NoChildren );
	qtarch_labelPSDriver->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelPSDriver->setFrameStyle( 0 );
	qtarch_labelPSDriver->setLineWidth( 1 );
	qtarch_labelPSDriver->setMidLineWidth( 0 );
	qtarch_labelPSDriver->QFrame::setMargin( 0 );
	qtarch_labelPSDriver->setText( _("PostScript driver :") );
	qtarch_labelPSDriver->setAlignment( 289 );
	qtarch_labelPSDriver->setMargin( -1 );

	sectiondepth = new QSpinBox( this, "sectiondepth" );
	sectiondepth->setGeometry( 320, 388, 153, 58 );
	sectiondepth->setMinimumSize( 0, 0 );
	sectiondepth->setMaximumSize( 32767, 32767 );
	sectiondepth->setFocusPolicy( QWidget::StrongFocus );
	sectiondepth->setBackgroundMode( QWidget::PaletteBackground );
	sectiondepth->setFontPropagation( QWidget::NoChildren );
	sectiondepth->setPalettePropagation( QWidget::NoChildren );
	sectiondepth->setFrameStyle( 51 );
	sectiondepth->setLineWidth( 2 );
	sectiondepth->setMidLineWidth( 0 );
	sectiondepth->QFrame::setMargin( 0 );
	sectiondepth->setRange( -2, 5 );
	sectiondepth->setSteps( 1, 0 );
	sectiondepth->setPrefix( "" );
	sectiondepth->setSuffix( "" );
	sectiondepth->setSpecialValueText( "" );
	sectiondepth->setWrapping( false );

	tocdepth = new QSpinBox( this, "tocdepth" );
	tocdepth->setGeometry( 320, 451, 153, 58 );
	tocdepth->setMinimumSize( 0, 0 );
	tocdepth->setMaximumSize( 32767, 32767 );
	tocdepth->setFocusPolicy( QWidget::StrongFocus );
	tocdepth->setBackgroundMode( QWidget::PaletteBackground );
	tocdepth->setFontPropagation( QWidget::NoChildren );
	tocdepth->setPalettePropagation( QWidget::NoChildren );
	tocdepth->setFrameStyle( 51 );
	tocdepth->setLineWidth( 2 );
	tocdepth->setMidLineWidth( 0 );
	tocdepth->QFrame::setMargin( 0 );
	tocdepth->setRange( -1, 5 );
	tocdepth->setSteps( 1, 0 );
	tocdepth->setPrefix( "" );
	tocdepth->setSuffix( "" );
	tocdepth->setSpecialValueText( "" );
	tocdepth->setWrapping( false );

	psdriver = new QComboBox( FALSE, this, "psdriver" );
	psdriver->setGeometry( 320, 514, 153, 58 );
	psdriver->setMinimumSize( 0, 0 );
	psdriver->setMaximumSize( 32767, 32767 );
	psdriver->setFocusPolicy( QWidget::StrongFocus );
	psdriver->setBackgroundMode( QWidget::PaletteBackground );
	psdriver->setFontPropagation( QWidget::AllChildren );
	psdriver->setPalettePropagation( QWidget::AllChildren );
	psdriver->setSizeLimit( 10 );
	psdriver->setAutoResize( true );
	psdriver->setMaxCount( 2147483647 );
	psdriver->setAutoCompletion( false );

	amsmath = new QCheckBox( this, "amsmath" );
	amsmath->setGeometry( 5, 577, 153, 58 );
	amsmath->setMinimumSize( 0, 0 );
	amsmath->setMaximumSize( 32767, 32767 );
	amsmath->setFocusPolicy( QWidget::TabFocus );
	amsmath->setBackgroundMode( QWidget::PaletteBackground );
	amsmath->setFontPropagation( QWidget::NoChildren );
	amsmath->setPalettePropagation( QWidget::NoChildren );
	amsmath->setText( _("Use AMS Math") );
	amsmath->setAutoRepeat( false );
	amsmath->setAutoResize( false );
	amsmath->setChecked( false );

	QLabel* qtarch_labelFirst;
	qtarch_labelFirst = new QLabel( qtarch_placementBox, "labelFirst" );
	qtarch_labelFirst->setGeometry( 5, 5, 150, 65 );
	qtarch_labelFirst->setMinimumSize( 0, 0 );
	qtarch_labelFirst->setMaximumSize( 32767, 32767 );
	qtarch_labelFirst->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelFirst->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelFirst->setFontPropagation( QWidget::NoChildren );
	qtarch_labelFirst->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelFirst->setFrameStyle( 0 );
	qtarch_labelFirst->setLineWidth( 1 );
	qtarch_labelFirst->setMidLineWidth( 0 );
	qtarch_labelFirst->QFrame::setMargin( 0 );
	qtarch_labelFirst->setText( _("First try :") );
	qtarch_labelFirst->setAlignment( 289 );
	qtarch_labelFirst->setMargin( -1 );

	QLabel* qtarch_labelSecond;
	qtarch_labelSecond = new QLabel( qtarch_placementBox, "labelSecond" );
	qtarch_labelSecond->setGeometry( 5, 75, 150, 66 );
	qtarch_labelSecond->setMinimumSize( 0, 0 );
	qtarch_labelSecond->setMaximumSize( 32767, 32767 );
	qtarch_labelSecond->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelSecond->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelSecond->setFontPropagation( QWidget::NoChildren );
	qtarch_labelSecond->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelSecond->setFrameStyle( 0 );
	qtarch_labelSecond->setLineWidth( 1 );
	qtarch_labelSecond->setMidLineWidth( 0 );
	qtarch_labelSecond->QFrame::setMargin( 0 );
	qtarch_labelSecond->setText( _("then :") );
	qtarch_labelSecond->setAlignment( 289 );
	qtarch_labelSecond->setMargin( -1 );

	QLabel* qtarch_labelThird;
	qtarch_labelThird = new QLabel( qtarch_placementBox, "labelThird" );
	qtarch_labelThird->setGeometry( 5, 146, 150, 65 );
	qtarch_labelThird->setMinimumSize( 0, 0 );
	qtarch_labelThird->setMaximumSize( 32767, 32767 );
	qtarch_labelThird->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelThird->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelThird->setFontPropagation( QWidget::NoChildren );
	qtarch_labelThird->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelThird->setFrameStyle( 0 );
	qtarch_labelThird->setLineWidth( 1 );
	qtarch_labelThird->setMidLineWidth( 0 );
	qtarch_labelThird->QFrame::setMargin( 0 );
	qtarch_labelThird->setText( _("then :") );
	qtarch_labelThird->setAlignment( 289 );
	qtarch_labelThird->setMargin( -1 );

	QLabel* qtarch_labelFourth;
	qtarch_labelFourth = new QLabel( qtarch_placementBox, "labelFourth" );
	qtarch_labelFourth->setGeometry( 5, 216, 150, 65 );
	qtarch_labelFourth->setMinimumSize( 0, 0 );
	qtarch_labelFourth->setMaximumSize( 32767, 32767 );
	qtarch_labelFourth->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelFourth->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelFourth->setFontPropagation( QWidget::NoChildren );
	qtarch_labelFourth->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelFourth->setFrameStyle( 0 );
	qtarch_labelFourth->setLineWidth( 1 );
	qtarch_labelFourth->setMidLineWidth( 0 );
	qtarch_labelFourth->QFrame::setMargin( 0 );
	qtarch_labelFourth->setText( _("then :") );
	qtarch_labelFourth->setAlignment( 289 );
	qtarch_labelFourth->setMargin( -1 );

	if (qtarch_placementBox->sizeHint().width()!=-1)
		qtarch_placementBox->setMinimumWidth(qtarch_placementBox->sizeHint().width());
	if (qtarch_placementBox->sizeHint().height()!=-1)
		qtarch_placementBox->setMinimumHeight(qtarch_placementBox->sizeHint().height());
	if (first->sizeHint().width()!=-1)
		first->setMinimumWidth(first->sizeHint().width());
	if (first->sizeHint().height()!=-1)
		first->setMinimumHeight(first->sizeHint().height());
	if (first->sizeHint().height()!=-1)
		first->setMaximumHeight(first->sizeHint().height());
	if (second->sizeHint().width()!=-1)
		second->setMinimumWidth(second->sizeHint().width());
	if (second->sizeHint().height()!=-1)
		second->setMinimumHeight(second->sizeHint().height());
	if (second->sizeHint().height()!=-1)
		second->setMaximumHeight(second->sizeHint().height());
	if (third->sizeHint().width()!=-1)
		third->setMinimumWidth(third->sizeHint().width());
	if (third->sizeHint().height()!=-1)
		third->setMinimumHeight(third->sizeHint().height());
	if (third->sizeHint().height()!=-1)
		third->setMaximumHeight(third->sizeHint().height());
	if (fourth->sizeHint().width()!=-1)
		fourth->setMinimumWidth(fourth->sizeHint().width());
	if (fourth->sizeHint().height()!=-1)
		fourth->setMinimumHeight(fourth->sizeHint().height());
	if (fourth->sizeHint().height()!=-1)
		fourth->setMaximumHeight(fourth->sizeHint().height());
	if (ignore->sizeHint().width()!=-1)
		ignore->setMinimumWidth(ignore->sizeHint().width());
	if (ignore->sizeHint().height()!=-1)
		ignore->setMinimumHeight(ignore->sizeHint().height());
	if (ignore->sizeHint().width()!=-1)
		ignore->setMaximumWidth(ignore->sizeHint().width());
	if (ignore->sizeHint().height()!=-1)
		ignore->setMaximumHeight(ignore->sizeHint().height());
	if (qtarch_labelsectiondepth->sizeHint().width()!=-1)
		qtarch_labelsectiondepth->setMinimumWidth(qtarch_labelsectiondepth->sizeHint().width());
	if (qtarch_labelsectiondepth->sizeHint().height()!=-1)
		qtarch_labelsectiondepth->setMinimumHeight(qtarch_labelsectiondepth->sizeHint().height());
	if (qtarch_labelsectiondepth->sizeHint().width()!=-1)
		qtarch_labelsectiondepth->setMaximumWidth(qtarch_labelsectiondepth->sizeHint().width());
	if (qtarch_labelsectiondepth->sizeHint().height()!=-1)
		qtarch_labelsectiondepth->setMaximumHeight(qtarch_labelsectiondepth->sizeHint().height());
	if (qtarch_labeltocdepth->sizeHint().width()!=-1)
		qtarch_labeltocdepth->setMinimumWidth(qtarch_labeltocdepth->sizeHint().width());
	if (qtarch_labeltocdepth->sizeHint().height()!=-1)
		qtarch_labeltocdepth->setMinimumHeight(qtarch_labeltocdepth->sizeHint().height());
	if (qtarch_labeltocdepth->sizeHint().width()!=-1)
		qtarch_labeltocdepth->setMaximumWidth(qtarch_labeltocdepth->sizeHint().width());
	if (qtarch_labeltocdepth->sizeHint().height()!=-1)
		qtarch_labeltocdepth->setMaximumHeight(qtarch_labeltocdepth->sizeHint().height());
	if (qtarch_labelPSDriver->sizeHint().width()!=-1)
		qtarch_labelPSDriver->setMinimumWidth(qtarch_labelPSDriver->sizeHint().width());
	if (qtarch_labelPSDriver->sizeHint().height()!=-1)
		qtarch_labelPSDriver->setMinimumHeight(qtarch_labelPSDriver->sizeHint().height());
	if (qtarch_labelPSDriver->sizeHint().width()!=-1)
		qtarch_labelPSDriver->setMaximumWidth(qtarch_labelPSDriver->sizeHint().width());
	if (qtarch_labelPSDriver->sizeHint().height()!=-1)
		qtarch_labelPSDriver->setMaximumHeight(qtarch_labelPSDriver->sizeHint().height());
	if (sectiondepth->sizeHint().width()!=-1)
		sectiondepth->setMinimumWidth(sectiondepth->sizeHint().width());
	if (sectiondepth->sizeHint().height()!=-1)
		sectiondepth->setMinimumHeight(sectiondepth->sizeHint().height());
	if (sectiondepth->sizeHint().height()!=-1)
		sectiondepth->setMaximumHeight(sectiondepth->sizeHint().height());
	if (tocdepth->sizeHint().width()!=-1)
		tocdepth->setMinimumWidth(tocdepth->sizeHint().width());
	if (tocdepth->sizeHint().height()!=-1)
		tocdepth->setMinimumHeight(tocdepth->sizeHint().height());
	if (tocdepth->sizeHint().height()!=-1)
		tocdepth->setMaximumHeight(tocdepth->sizeHint().height());
	if (psdriver->sizeHint().width()!=-1)
		psdriver->setMinimumWidth(psdriver->sizeHint().width());
	if (psdriver->sizeHint().height()!=-1)
		psdriver->setMinimumHeight(psdriver->sizeHint().height());
	if (psdriver->sizeHint().height()!=-1)
		psdriver->setMaximumHeight(psdriver->sizeHint().height());
	if (amsmath->sizeHint().width()!=-1)
		amsmath->setMinimumWidth(amsmath->sizeHint().width());
	if (amsmath->sizeHint().height()!=-1)
		amsmath->setMinimumHeight(amsmath->sizeHint().height());
	if (amsmath->sizeHint().width()!=-1)
		amsmath->setMaximumWidth(amsmath->sizeHint().width());
	if (amsmath->sizeHint().height()!=-1)
		amsmath->setMaximumHeight(amsmath->sizeHint().height());
	if (qtarch_labelFirst->sizeHint().width()!=-1)
		qtarch_labelFirst->setMinimumWidth(qtarch_labelFirst->sizeHint().width());
	if (qtarch_labelFirst->sizeHint().height()!=-1)
		qtarch_labelFirst->setMinimumHeight(qtarch_labelFirst->sizeHint().height());
	if (qtarch_labelFirst->sizeHint().width()!=-1)
		qtarch_labelFirst->setMaximumWidth(qtarch_labelFirst->sizeHint().width());
	if (qtarch_labelFirst->sizeHint().height()!=-1)
		qtarch_labelFirst->setMaximumHeight(qtarch_labelFirst->sizeHint().height());
	if (qtarch_labelSecond->sizeHint().width()!=-1)
		qtarch_labelSecond->setMinimumWidth(qtarch_labelSecond->sizeHint().width());
	if (qtarch_labelSecond->sizeHint().height()!=-1)
		qtarch_labelSecond->setMinimumHeight(qtarch_labelSecond->sizeHint().height());
	if (qtarch_labelSecond->sizeHint().width()!=-1)
		qtarch_labelSecond->setMaximumWidth(qtarch_labelSecond->sizeHint().width());
	if (qtarch_labelSecond->sizeHint().height()!=-1)
		qtarch_labelSecond->setMaximumHeight(qtarch_labelSecond->sizeHint().height());
	if (qtarch_labelThird->sizeHint().width()!=-1)
		qtarch_labelThird->setMinimumWidth(qtarch_labelThird->sizeHint().width());
	if (qtarch_labelThird->sizeHint().height()!=-1)
		qtarch_labelThird->setMinimumHeight(qtarch_labelThird->sizeHint().height());
	if (qtarch_labelThird->sizeHint().width()!=-1)
		qtarch_labelThird->setMaximumWidth(qtarch_labelThird->sizeHint().width());
	if (qtarch_labelThird->sizeHint().height()!=-1)
		qtarch_labelThird->setMaximumHeight(qtarch_labelThird->sizeHint().height());
	if (qtarch_labelFourth->sizeHint().width()!=-1)
		qtarch_labelFourth->setMinimumWidth(qtarch_labelFourth->sizeHint().width());
	if (qtarch_labelFourth->sizeHint().height()!=-1)
		qtarch_labelFourth->setMinimumHeight(qtarch_labelFourth->sizeHint().height());
	if (qtarch_labelFourth->sizeHint().width()!=-1)
		qtarch_labelFourth->setMaximumWidth(qtarch_labelFourth->sizeHint().width());
	if (qtarch_labelFourth->sizeHint().height()!=-1)
		qtarch_labelFourth->setMaximumHeight(qtarch_labelFourth->sizeHint().height());
	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	qtarch_layout_1->addWidget( qtarch_placementBox, 3, 36 );
	QBoxLayout* qtarch_layout_1_1 = new QBoxLayout( qtarch_placementBox, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1_1->addStrut( 0 );
	QGridLayout* qtarch_layout_1_1_1 = new QGridLayout( 4, 4, 5, NULL );
	qtarch_layout_1_1->addLayout( qtarch_layout_1_1_1, 3 );
	qtarch_layout_1_1_1->addColSpacing( 0, 5 );
	qtarch_layout_1_1_1->setColStretch( 0, 1 );
	qtarch_layout_1_1_1->addColSpacing( 1, 5 );
	qtarch_layout_1_1_1->setColStretch( 1, 1 );
	qtarch_layout_1_1_1->addColSpacing( 2, 5 );
	qtarch_layout_1_1_1->setColStretch( 2, 1 );
	qtarch_layout_1_1_1->addColSpacing( 3, 5 );
	qtarch_layout_1_1_1->setColStretch( 3, 1 );
	qtarch_layout_1_1_1->addRowSpacing( 0, 0 );
	qtarch_layout_1_1_1->setRowStretch( 0, 1 );
	qtarch_layout_1_1_1->addWidget( qtarch_labelFirst, 0, 0, 36 );
	qtarch_layout_1_1_1->addWidget( first, 0, 2, 36 );
	qtarch_layout_1_1_1->addRowSpacing( 1, 0 );
	qtarch_layout_1_1_1->setRowStretch( 1, 1 );
	qtarch_layout_1_1_1->addWidget( qtarch_labelSecond, 1, 0, 36 );
	qtarch_layout_1_1_1->addWidget( second, 1, 2, 36 );
	qtarch_layout_1_1_1->addRowSpacing( 2, 0 );
	qtarch_layout_1_1_1->setRowStretch( 2, 1 );
	qtarch_layout_1_1_1->addWidget( qtarch_labelThird, 2, 0, 36 );
	qtarch_layout_1_1_1->addWidget( third, 2, 2, 36 );
	qtarch_layout_1_1_1->addRowSpacing( 3, 0 );
	qtarch_layout_1_1_1->setRowStretch( 3, 1 );
	qtarch_layout_1_1_1->addWidget( qtarch_labelFourth, 3, 0, 36 );
	qtarch_layout_1_1_1->addWidget( fourth, 3, 2, 36 );
	QBoxLayout* qtarch_layout_1_1_2 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1_1->addLayout( qtarch_layout_1_1_2, 1 );
	qtarch_layout_1_1_2->addStrut( 0 );
	qtarch_layout_1_1_2->addWidget( ignore, 1, 36 );
	QGridLayout* qtarch_layout_1_2 = new QGridLayout( 4, 4, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2, 2 );
	qtarch_layout_1_2->addColSpacing( 0, 5 );
	qtarch_layout_1_2->setColStretch( 0, 1 );
	qtarch_layout_1_2->addColSpacing( 1, 5 );
	qtarch_layout_1_2->setColStretch( 1, 1 );
	qtarch_layout_1_2->addColSpacing( 2, 5 );
	qtarch_layout_1_2->setColStretch( 2, 1 );
	qtarch_layout_1_2->addColSpacing( 3, 5 );
	qtarch_layout_1_2->setColStretch( 3, 1 );
	qtarch_layout_1_2->addRowSpacing( 0, 0 );
	qtarch_layout_1_2->setRowStretch( 0, 1 );
	qtarch_layout_1_2->addWidget( qtarch_labelsectiondepth, 0, 0, 36 );
	qtarch_layout_1_2->addWidget( sectiondepth, 0, 2, 36 );
	qtarch_layout_1_2->addRowSpacing( 1, 0 );
	qtarch_layout_1_2->setRowStretch( 1, 1 );
	qtarch_layout_1_2->addWidget( qtarch_labeltocdepth, 1, 0, 36 );
	qtarch_layout_1_2->addWidget( tocdepth, 1, 2, 36 );
	qtarch_layout_1_2->addRowSpacing( 2, 0 );
	qtarch_layout_1_2->setRowStretch( 2, 1 );
	qtarch_layout_1_2->addWidget( qtarch_labelPSDriver, 2, 0, 36 );
	qtarch_layout_1_2->addWidget( psdriver, 2, 2, 36 );
	qtarch_layout_1_2->addRowSpacing( 3, 0 );
	qtarch_layout_1_2->setRowStretch( 3, 1 );
	qtarch_layout_1_2->addWidget( amsmath, 3, 0, 36 );
	resize( 635,640 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


DocExtraDialogData::~DocExtraDialogData()
{
}
