/**********************************************************************

	--- Qt Architect 1.4-6 generated file ---

	File: docextradlgdata.C
	Last generated: Wed Jan 24 06:43:31 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <gettext.h>

#include <qpixmap.h>
#include <qlayout.h>
#include "docextradlgdata.h"

#define Inherited QWidget

#include <qlabel.h>

DocExtraDialogData::DocExtraDialogData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QLabel* qtarch_labelFloatplacement;
	qtarch_labelFloatplacement = new QLabel( this, "labelFloatplacement" );
	qtarch_labelFloatplacement->setGeometry( 5, 5, 105, 86 );
	qtarch_labelFloatplacement->setMinimumSize( 0, 0 );
	qtarch_labelFloatplacement->setMaximumSize( 32767, 32767 );
	qtarch_labelFloatplacement->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelFloatplacement->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelFloatplacement->setFontPropagation( QWidget::NoChildren );
	qtarch_labelFloatplacement->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelFloatplacement->setFrameStyle( 0 );
	qtarch_labelFloatplacement->setLineWidth( 1 );
	qtarch_labelFloatplacement->setMidLineWidth( 0 );
	qtarch_labelFloatplacement->QFrame::setMargin( 0 );
	qtarch_labelFloatplacement->setText( _("Float placement : (FIXME)") );
	qtarch_labelFloatplacement->setAlignment( 289 );
	qtarch_labelFloatplacement->setMargin( -1 );

	floatplacement = new QLineEdit( this, "floatplacement" );
	floatplacement->setGeometry( 225, 5, 205, 86 );
	floatplacement->setMinimumSize( 0, 0 );
	floatplacement->setMaximumSize( 32767, 32767 );
	floatplacement->setFocusPolicy( QWidget::StrongFocus );
	floatplacement->setBackgroundMode( QWidget::PaletteBase );
	floatplacement->setFontPropagation( QWidget::NoChildren );
	floatplacement->setPalettePropagation( QWidget::NoChildren );
	floatplacement->setText( "" );
	floatplacement->setMaxLength( 32767 );
	floatplacement->setFrame( QLineEdit::Normal );
	floatplacement->setFrame( true );

	QLabel* qtarch_labelsectiondepth;
	qtarch_labelsectiondepth = new QLabel( this, "labelsectiondepth" );
	qtarch_labelsectiondepth->setGeometry( 5, 96, 105, 86 );
	qtarch_labelsectiondepth->setMinimumSize( 0, 0 );
	qtarch_labelsectiondepth->setMaximumSize( 32767, 32767 );
	qtarch_labelsectiondepth->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelsectiondepth->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelsectiondepth->setFontPropagation( QWidget::NoChildren );
	qtarch_labelsectiondepth->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelsectiondepth->setFrameStyle( 0 );
	qtarch_labelsectiondepth->setLineWidth( 1 );
	qtarch_labelsectiondepth->setMidLineWidth( 0 );
	qtarch_labelsectiondepth->QFrame::setMargin( 0 );
	qtarch_labelsectiondepth->setText( _("Section number depth :") );
	qtarch_labelsectiondepth->setAlignment( 289 );
	qtarch_labelsectiondepth->setMargin( -1 );

	QLabel* qtarch_labeltocdepth;
	qtarch_labeltocdepth = new QLabel( this, "labeltocdepth" );
	qtarch_labeltocdepth->setGeometry( 5, 187, 105, 86 );
	qtarch_labeltocdepth->setMinimumSize( 0, 0 );
	qtarch_labeltocdepth->setMaximumSize( 32767, 32767 );
	qtarch_labeltocdepth->setFocusPolicy( QWidget::NoFocus );
	qtarch_labeltocdepth->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labeltocdepth->setFontPropagation( QWidget::NoChildren );
	qtarch_labeltocdepth->setPalettePropagation( QWidget::NoChildren );
	qtarch_labeltocdepth->setFrameStyle( 0 );
	qtarch_labeltocdepth->setLineWidth( 1 );
	qtarch_labeltocdepth->setMidLineWidth( 0 );
	qtarch_labeltocdepth->QFrame::setMargin( 0 );
	qtarch_labeltocdepth->setText( _("Table of Contents depth :") );
	qtarch_labeltocdepth->setAlignment( 289 );
	qtarch_labeltocdepth->setMargin( -1 );

	QLabel* qtarch_labelPSDriver;
	qtarch_labelPSDriver = new QLabel( this, "labelPSDriver" );
	qtarch_labelPSDriver->setGeometry( 5, 278, 105, 86 );
	qtarch_labelPSDriver->setMinimumSize( 0, 0 );
	qtarch_labelPSDriver->setMaximumSize( 32767, 32767 );
	qtarch_labelPSDriver->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelPSDriver->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelPSDriver->setFontPropagation( QWidget::NoChildren );
	qtarch_labelPSDriver->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelPSDriver->setFrameStyle( 0 );
	qtarch_labelPSDriver->setLineWidth( 1 );
	qtarch_labelPSDriver->setMidLineWidth( 0 );
	qtarch_labelPSDriver->QFrame::setMargin( 0 );
	qtarch_labelPSDriver->setText( _("PostScript driver :") );
	qtarch_labelPSDriver->setAlignment( 289 );
	qtarch_labelPSDriver->setMargin( -1 );

	amsmath = new QCheckBox( this, "amsmath" );
	amsmath->setGeometry( 5, 369, 105, 86 );
	amsmath->setMinimumSize( 0, 0 );
	amsmath->setMaximumSize( 32767, 32767 );
	amsmath->setFocusPolicy( QWidget::TabFocus );
	amsmath->setBackgroundMode( QWidget::PaletteBackground );
	amsmath->setFontPropagation( QWidget::NoChildren );
	amsmath->setPalettePropagation( QWidget::NoChildren );
	amsmath->setText( _("Use AMS Math") );
	amsmath->setAutoRepeat( false );
	amsmath->setAutoResize( false );
	amsmath->setChecked( false );

	sectiondepth = new QSpinBox( this, "sectiondepth" );
	sectiondepth->setGeometry( 225, 96, 205, 86 );
	sectiondepth->setMinimumSize( 0, 0 );
	sectiondepth->setMaximumSize( 32767, 32767 );
	sectiondepth->setFocusPolicy( QWidget::StrongFocus );
	sectiondepth->setBackgroundMode( QWidget::PaletteBackground );
	sectiondepth->setFontPropagation( QWidget::NoChildren );
	sectiondepth->setPalettePropagation( QWidget::NoChildren );
	sectiondepth->setFrameStyle( 51 );
	sectiondepth->setLineWidth( 2 );
	sectiondepth->setMidLineWidth( 0 );
	sectiondepth->QFrame::setMargin( 0 );
	sectiondepth->setRange( -2, 5 );
	sectiondepth->setSteps( 1, 0 );
	sectiondepth->setPrefix( "" );
	sectiondepth->setSuffix( "" );
	sectiondepth->setSpecialValueText( "" );
	sectiondepth->setWrapping( false );

	tocdepth = new QSpinBox( this, "tocdepth" );
	tocdepth->setGeometry( 225, 187, 205, 86 );
	tocdepth->setMinimumSize( 0, 0 );
	tocdepth->setMaximumSize( 32767, 32767 );
	tocdepth->setFocusPolicy( QWidget::StrongFocus );
	tocdepth->setBackgroundMode( QWidget::PaletteBackground );
	tocdepth->setFontPropagation( QWidget::NoChildren );
	tocdepth->setPalettePropagation( QWidget::NoChildren );
	tocdepth->setFrameStyle( 51 );
	tocdepth->setLineWidth( 2 );
	tocdepth->setMidLineWidth( 0 );
	tocdepth->QFrame::setMargin( 0 );
	tocdepth->setRange( -1, 5 );
	tocdepth->setSteps( 1, 0 );
	tocdepth->setPrefix( "" );
	tocdepth->setSuffix( "" );
	tocdepth->setSpecialValueText( "" );
	tocdepth->setWrapping( false );

	psdriver = new QComboBox( FALSE, this, "psdriver" );
	psdriver->setGeometry( 225, 278, 205, 86 );
	psdriver->setMinimumSize( 0, 0 );
	psdriver->setMaximumSize( 32767, 32767 );
	psdriver->setFocusPolicy( QWidget::StrongFocus );
	psdriver->setBackgroundMode( QWidget::PaletteBackground );
	psdriver->setFontPropagation( QWidget::AllChildren );
	psdriver->setPalettePropagation( QWidget::AllChildren );
	psdriver->setSizeLimit( 10 );
	psdriver->setAutoResize( true );
	psdriver->setMaxCount( 2147483647 );
	psdriver->setAutoCompletion( false );

	if (qtarch_labelFloatplacement->sizeHint().width()!=-1)
		qtarch_labelFloatplacement->setMinimumWidth(qtarch_labelFloatplacement->sizeHint().width());
	if (qtarch_labelFloatplacement->sizeHint().height()!=-1)
		qtarch_labelFloatplacement->setMinimumHeight(qtarch_labelFloatplacement->sizeHint().height());
	if (qtarch_labelFloatplacement->sizeHint().width()!=-1)
		qtarch_labelFloatplacement->setMaximumWidth(qtarch_labelFloatplacement->sizeHint().width());
	if (qtarch_labelFloatplacement->sizeHint().height()!=-1)
		qtarch_labelFloatplacement->setMaximumHeight(qtarch_labelFloatplacement->sizeHint().height());
	if (floatplacement->sizeHint().width()!=-1)
		floatplacement->setMinimumWidth(floatplacement->sizeHint().width());
	if (floatplacement->sizeHint().height()!=-1)
		floatplacement->setMinimumHeight(floatplacement->sizeHint().height());
	if (floatplacement->sizeHint().height()!=-1)
		floatplacement->setMaximumHeight(floatplacement->sizeHint().height());
	if (qtarch_labelsectiondepth->sizeHint().width()!=-1)
		qtarch_labelsectiondepth->setMinimumWidth(qtarch_labelsectiondepth->sizeHint().width());
	if (qtarch_labelsectiondepth->sizeHint().height()!=-1)
		qtarch_labelsectiondepth->setMinimumHeight(qtarch_labelsectiondepth->sizeHint().height());
	if (qtarch_labelsectiondepth->sizeHint().width()!=-1)
		qtarch_labelsectiondepth->setMaximumWidth(qtarch_labelsectiondepth->sizeHint().width());
	if (qtarch_labelsectiondepth->sizeHint().height()!=-1)
		qtarch_labelsectiondepth->setMaximumHeight(qtarch_labelsectiondepth->sizeHint().height());
	if (qtarch_labeltocdepth->sizeHint().width()!=-1)
		qtarch_labeltocdepth->setMinimumWidth(qtarch_labeltocdepth->sizeHint().width());
	if (qtarch_labeltocdepth->sizeHint().height()!=-1)
		qtarch_labeltocdepth->setMinimumHeight(qtarch_labeltocdepth->sizeHint().height());
	if (qtarch_labeltocdepth->sizeHint().width()!=-1)
		qtarch_labeltocdepth->setMaximumWidth(qtarch_labeltocdepth->sizeHint().width());
	if (qtarch_labeltocdepth->sizeHint().height()!=-1)
		qtarch_labeltocdepth->setMaximumHeight(qtarch_labeltocdepth->sizeHint().height());
	if (qtarch_labelPSDriver->sizeHint().width()!=-1)
		qtarch_labelPSDriver->setMinimumWidth(qtarch_labelPSDriver->sizeHint().width());
	if (qtarch_labelPSDriver->sizeHint().height()!=-1)
		qtarch_labelPSDriver->setMinimumHeight(qtarch_labelPSDriver->sizeHint().height());
	if (qtarch_labelPSDriver->sizeHint().width()!=-1)
		qtarch_labelPSDriver->setMaximumWidth(qtarch_labelPSDriver->sizeHint().width());
	if (qtarch_labelPSDriver->sizeHint().height()!=-1)
		qtarch_labelPSDriver->setMaximumHeight(qtarch_labelPSDriver->sizeHint().height());
	if (amsmath->sizeHint().width()!=-1)
		amsmath->setMinimumWidth(amsmath->sizeHint().width());
	if (amsmath->sizeHint().height()!=-1)
		amsmath->setMinimumHeight(amsmath->sizeHint().height());
	if (amsmath->sizeHint().width()!=-1)
		amsmath->setMaximumWidth(amsmath->sizeHint().width());
	if (amsmath->sizeHint().height()!=-1)
		amsmath->setMaximumHeight(amsmath->sizeHint().height());
	if (sectiondepth->sizeHint().width()!=-1)
		sectiondepth->setMinimumWidth(sectiondepth->sizeHint().width());
	if (sectiondepth->sizeHint().height()!=-1)
		sectiondepth->setMinimumHeight(sectiondepth->sizeHint().height());
	if (sectiondepth->sizeHint().height()!=-1)
		sectiondepth->setMaximumHeight(sectiondepth->sizeHint().height());
	if (tocdepth->sizeHint().width()!=-1)
		tocdepth->setMinimumWidth(tocdepth->sizeHint().width());
	if (tocdepth->sizeHint().height()!=-1)
		tocdepth->setMinimumHeight(tocdepth->sizeHint().height());
	if (tocdepth->sizeHint().height()!=-1)
		tocdepth->setMaximumHeight(tocdepth->sizeHint().height());
	if (psdriver->sizeHint().width()!=-1)
		psdriver->setMinimumWidth(psdriver->sizeHint().width());
	if (psdriver->sizeHint().height()!=-1)
		psdriver->setMinimumHeight(psdriver->sizeHint().height());
	if (psdriver->sizeHint().height()!=-1)
		psdriver->setMaximumHeight(psdriver->sizeHint().height());
	QGridLayout* qtarch_layout_1 = new QGridLayout( this, 5, 4, 5, 5, NULL );
	qtarch_layout_1->addColSpacing( 0, 5 );
	qtarch_layout_1->setColStretch( 0, 1 );
	qtarch_layout_1->addColSpacing( 1, 5 );
	qtarch_layout_1->setColStretch( 1, 1 );
	qtarch_layout_1->addColSpacing( 2, 5 );
	qtarch_layout_1->setColStretch( 2, 2 );
	qtarch_layout_1->addColSpacing( 3, 5 );
	qtarch_layout_1->setColStretch( 3, 1 );
	qtarch_layout_1->addRowSpacing( 0, 0 );
	qtarch_layout_1->setRowStretch( 0, 1 );
	qtarch_layout_1->addWidget( qtarch_labelFloatplacement, 0, 0, 33 );
	qtarch_layout_1->addWidget( floatplacement, 0, 2, 33 );
	qtarch_layout_1->addRowSpacing( 1, 0 );
	qtarch_layout_1->setRowStretch( 1, 1 );
	qtarch_layout_1->addWidget( qtarch_labelsectiondepth, 1, 0, 33 );
	qtarch_layout_1->addWidget( sectiondepth, 1, 2, 33 );
	qtarch_layout_1->addRowSpacing( 2, 0 );
	qtarch_layout_1->setRowStretch( 2, 1 );
	qtarch_layout_1->addWidget( qtarch_labeltocdepth, 2, 0, 33 );
	qtarch_layout_1->addWidget( tocdepth, 2, 2, 33 );
	qtarch_layout_1->addRowSpacing( 3, 0 );
	qtarch_layout_1->setRowStretch( 3, 1 );
	qtarch_layout_1->addWidget( qtarch_labelPSDriver, 3, 0, 33 );
	qtarch_layout_1->addWidget( psdriver, 3, 2, 33 );
	qtarch_layout_1->addRowSpacing( 4, 0 );
	qtarch_layout_1->setRowStretch( 4, 1 );
	qtarch_layout_1->addWidget( amsmath, 4, 0, 33 );
	resize( 545,460 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


DocExtraDialogData::~DocExtraDialogData()
{
}
