/**********************************************************************

	--- Qt Architect 1.4-6 generated file ---

	File: doclanguagedlgdata.C
	Last generated: Wed Jan 24 06:43:17 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <gettext.h>

#include <qpixmap.h>
#include <qlayout.h>
#include "doclanguagedlgdata.h"

#define Inherited QWidget

#include <qlabel.h>

DocLanguageDialogData::DocLanguageDialogData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QLabel* qtarch_labelLanguage;
	qtarch_labelLanguage = new QLabel( this, "labelLanguage" );
	qtarch_labelLanguage->setGeometry( 5, 5, 130, 147 );
	qtarch_labelLanguage->setMinimumSize( 0, 0 );
	qtarch_labelLanguage->setMaximumSize( 32767, 32767 );
	qtarch_labelLanguage->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelLanguage->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelLanguage->setFontPropagation( QWidget::NoChildren );
	qtarch_labelLanguage->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelLanguage->setFrameStyle( 0 );
	qtarch_labelLanguage->setLineWidth( 1 );
	qtarch_labelLanguage->setMidLineWidth( 0 );
	qtarch_labelLanguage->QFrame::setMargin( 0 );
	qtarch_labelLanguage->setText( _("Language :") );
	qtarch_labelLanguage->setAlignment( 290 );
	qtarch_labelLanguage->setMargin( -1 );

	language = new QComboBox( FALSE, this, "language" );
	language->setGeometry( 275, 5, 130, 147 );
	language->setMinimumSize( 0, 0 );
	language->setMaximumSize( 32767, 32767 );
	language->setFocusPolicy( QWidget::StrongFocus );
	language->setBackgroundMode( QWidget::PaletteBackground );
	language->setFontPropagation( QWidget::AllChildren );
	language->setPalettePropagation( QWidget::AllChildren );
	language->setSizeLimit( 30 );
	language->setAutoResize( true );
	language->setMaxCount( 2147483647 );
	language->setAutoCompletion( false );

	QLabel* qtarch_labelEncoding;
	qtarch_labelEncoding = new QLabel( this, "labelEncoding" );
	qtarch_labelEncoding->setGeometry( 5, 157, 130, 146 );
	qtarch_labelEncoding->setMinimumSize( 0, 0 );
	qtarch_labelEncoding->setMaximumSize( 32767, 32767 );
	qtarch_labelEncoding->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelEncoding->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelEncoding->setFontPropagation( QWidget::NoChildren );
	qtarch_labelEncoding->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelEncoding->setFrameStyle( 0 );
	qtarch_labelEncoding->setLineWidth( 1 );
	qtarch_labelEncoding->setMidLineWidth( 0 );
	qtarch_labelEncoding->QFrame::setMargin( 0 );
	qtarch_labelEncoding->setText( _("Encoding :") );
	qtarch_labelEncoding->setAlignment( 290 );
	qtarch_labelEncoding->setMargin( -1 );

	encoding = new QComboBox( FALSE, this, "encoding" );
	encoding->setGeometry( 275, 157, 130, 146 );
	encoding->setMinimumSize( 0, 0 );
	encoding->setMaximumSize( 32767, 32767 );
	encoding->setFocusPolicy( QWidget::StrongFocus );
	encoding->setBackgroundMode( QWidget::PaletteBackground );
	encoding->setFontPropagation( QWidget::AllChildren );
	encoding->setPalettePropagation( QWidget::AllChildren );
	encoding->setSizeLimit( 30 );
	encoding->setAutoResize( true );
	encoding->setMaxCount( 2147483647 );
	encoding->setAutoCompletion( false );

	QLabel* qtarch_labelQuotes;
	qtarch_labelQuotes = new QLabel( this, "labelQuotes" );
	qtarch_labelQuotes->setGeometry( 5, 308, 130, 147 );
	qtarch_labelQuotes->setMinimumSize( 0, 0 );
	qtarch_labelQuotes->setMaximumSize( 32767, 32767 );
	qtarch_labelQuotes->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelQuotes->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelQuotes->setFontPropagation( QWidget::NoChildren );
	qtarch_labelQuotes->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelQuotes->setFrameStyle( 0 );
	qtarch_labelQuotes->setLineWidth( 1 );
	qtarch_labelQuotes->setMidLineWidth( 0 );
	qtarch_labelQuotes->QFrame::setMargin( 0 );
	qtarch_labelQuotes->setText( _("Quote style :") );
	qtarch_labelQuotes->setAlignment( 290 );
	qtarch_labelQuotes->setMargin( -1 );

	quotes = new QComboBox( FALSE, this, "quotes" );
	quotes->setGeometry( 275, 308, 130, 147 );
	quotes->setMinimumSize( 0, 0 );
	quotes->setMaximumSize( 32767, 32767 );
	quotes->setFocusPolicy( QWidget::StrongFocus );
	quotes->setBackgroundMode( QWidget::PaletteBackground );
	quotes->setFontPropagation( QWidget::AllChildren );
	quotes->setPalettePropagation( QWidget::AllChildren );
	quotes->setSizeLimit( 30 );
	quotes->setAutoResize( true );
	quotes->setMaxCount( 2147483647 );
	quotes->setAutoCompletion( false );

	if (qtarch_labelLanguage->sizeHint().width()!=-1)
		qtarch_labelLanguage->setMinimumWidth(qtarch_labelLanguage->sizeHint().width());
	if (qtarch_labelLanguage->sizeHint().height()!=-1)
		qtarch_labelLanguage->setMinimumHeight(qtarch_labelLanguage->sizeHint().height());
	if (qtarch_labelLanguage->sizeHint().width()!=-1)
		qtarch_labelLanguage->setMaximumWidth(qtarch_labelLanguage->sizeHint().width());
	if (qtarch_labelLanguage->sizeHint().height()!=-1)
		qtarch_labelLanguage->setMaximumHeight(qtarch_labelLanguage->sizeHint().height());
	if (language->sizeHint().width()!=-1)
		language->setMinimumWidth(language->sizeHint().width());
	if (language->sizeHint().height()!=-1)
		language->setMinimumHeight(language->sizeHint().height());
	if (language->sizeHint().height()!=-1)
		language->setMaximumHeight(language->sizeHint().height());
	if (qtarch_labelEncoding->sizeHint().width()!=-1)
		qtarch_labelEncoding->setMinimumWidth(qtarch_labelEncoding->sizeHint().width());
	if (qtarch_labelEncoding->sizeHint().height()!=-1)
		qtarch_labelEncoding->setMinimumHeight(qtarch_labelEncoding->sizeHint().height());
	if (qtarch_labelEncoding->sizeHint().width()!=-1)
		qtarch_labelEncoding->setMaximumWidth(qtarch_labelEncoding->sizeHint().width());
	if (qtarch_labelEncoding->sizeHint().height()!=-1)
		qtarch_labelEncoding->setMaximumHeight(qtarch_labelEncoding->sizeHint().height());
	if (encoding->sizeHint().width()!=-1)
		encoding->setMinimumWidth(encoding->sizeHint().width());
	if (encoding->sizeHint().height()!=-1)
		encoding->setMinimumHeight(encoding->sizeHint().height());
	if (encoding->sizeHint().height()!=-1)
		encoding->setMaximumHeight(encoding->sizeHint().height());
	if (qtarch_labelQuotes->sizeHint().width()!=-1)
		qtarch_labelQuotes->setMinimumWidth(qtarch_labelQuotes->sizeHint().width());
	if (qtarch_labelQuotes->sizeHint().height()!=-1)
		qtarch_labelQuotes->setMinimumHeight(qtarch_labelQuotes->sizeHint().height());
	if (qtarch_labelQuotes->sizeHint().width()!=-1)
		qtarch_labelQuotes->setMaximumWidth(qtarch_labelQuotes->sizeHint().width());
	if (qtarch_labelQuotes->sizeHint().height()!=-1)
		qtarch_labelQuotes->setMaximumHeight(qtarch_labelQuotes->sizeHint().height());
	if (quotes->sizeHint().width()!=-1)
		quotes->setMinimumWidth(quotes->sizeHint().width());
	if (quotes->sizeHint().height()!=-1)
		quotes->setMinimumHeight(quotes->sizeHint().height());
	if (quotes->sizeHint().height()!=-1)
		quotes->setMaximumHeight(quotes->sizeHint().height());
	QGridLayout* qtarch_layout_1 = new QGridLayout( this, 3, 4, 5, 5, NULL );
	qtarch_layout_1->addColSpacing( 0, 5 );
	qtarch_layout_1->setColStretch( 0, 1 );
	qtarch_layout_1->addColSpacing( 1, 5 );
	qtarch_layout_1->setColStretch( 1, 1 );
	qtarch_layout_1->addColSpacing( 2, 5 );
	qtarch_layout_1->setColStretch( 2, 1 );
	qtarch_layout_1->addColSpacing( 3, 5 );
	qtarch_layout_1->setColStretch( 3, 1 );
	qtarch_layout_1->addRowSpacing( 0, 0 );
	qtarch_layout_1->setRowStretch( 0, 1 );
	qtarch_layout_1->addWidget( qtarch_labelLanguage, 0, 0, 33 );
	qtarch_layout_1->addWidget( language, 0, 2, 33 );
	qtarch_layout_1->addRowSpacing( 1, 0 );
	qtarch_layout_1->setRowStretch( 1, 1 );
	qtarch_layout_1->addWidget( qtarch_labelEncoding, 1, 0, 33 );
	qtarch_layout_1->addWidget( encoding, 1, 2, 33 );
	qtarch_layout_1->addRowSpacing( 2, 0 );
	qtarch_layout_1->setRowStretch( 2, 1 );
	qtarch_layout_1->addWidget( qtarch_labelQuotes, 2, 0, 33 );
	qtarch_layout_1->addWidget( quotes, 2, 2, 33 );
	resize( 545,460 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


DocLanguageDialogData::~DocLanguageDialogData()
{
}
