/**********************************************************************

	--- Qt Architect 1.4-6 generated file ---

	File: doclanguagedlgdata.h
	Last generated: Sat Mar 31 16:48:33 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef DocLanguageDialogData_included
#define DocLanguageDialogData_included

#include <qwidget.h>
#include <qcombobox.h>

class DocLanguageDialogData : public QWidget
{
    Q_OBJECT

public:

    DocLanguageDialogData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~DocLanguageDialogData();

public slots:


protected slots:


public:
    QComboBox* combo_language;
    QComboBox* combo_encoding;
    QComboBox* combo_quotes;

};

#endif // DocLanguageDialogData_included
