/**********************************************************************

	--- Qt Architect 1.4-6 generated file ---

	File: docsettingsdlgdata.C
	Last generated: Sat Mar 31 16:48:38 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <gettext.h>

#include <qpixmap.h>
#include <qlayout.h>
#include "docsettingsdlgdata.h"

#define Inherited QWidget

#include <qlabel.h>
#include <qgroupbox.h>

DocSettingsDialogData::DocSettingsDialogData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QGroupBox* qtarch_paraspacingbox;
	qtarch_paraspacingbox = new QGroupBox( this, "paraspacingbox" );
	qtarch_paraspacingbox->setGeometry( 5, 180, 540, 220 );
	qtarch_paraspacingbox->setMinimumSize( 35, 69 );
	qtarch_paraspacingbox->setMaximumSize( 32767, 32767 );
	qtarch_paraspacingbox->setFocusPolicy( QWidget::NoFocus );
	qtarch_paraspacingbox->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_paraspacingbox->setFontPropagation( QWidget::NoChildren );
	qtarch_paraspacingbox->setPalettePropagation( QWidget::NoChildren );
	qtarch_paraspacingbox->setFrameStyle( 49 );
	qtarch_paraspacingbox->setLineWidth( 1 );
	qtarch_paraspacingbox->setMidLineWidth( 0 );
	qtarch_paraspacingbox->QFrame::setMargin( 17 );
	qtarch_paraspacingbox->setTitle( _("Paragraph spacing") );
	qtarch_paraspacingbox->setAlignment( 1 );

	QLabel* qtarch_labelFontSize;
	qtarch_labelFontSize = new QLabel( this, "labelFontSize" );
	qtarch_labelFontSize->setGeometry( 114, 95, 104, 25 );
	qtarch_labelFontSize->setMinimumSize( 0, 0 );
	qtarch_labelFontSize->setMaximumSize( 32767, 32767 );
	qtarch_labelFontSize->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelFontSize->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelFontSize->setFontPropagation( QWidget::NoChildren );
	qtarch_labelFontSize->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelFontSize->setFrameStyle( 0 );
	qtarch_labelFontSize->setLineWidth( 1 );
	qtarch_labelFontSize->setMidLineWidth( 0 );
	qtarch_labelFontSize->QFrame::setMargin( 0 );
	qtarch_labelFontSize->setText( _("Font size :") );
	qtarch_labelFontSize->setAlignment( 289 );
	qtarch_labelFontSize->setMargin( -1 );

	QLabel* qtarch_labelFont;
	qtarch_labelFont = new QLabel( this, "labelFont" );
	qtarch_labelFont->setGeometry( 114, 65, 104, 25 );
	qtarch_labelFont->setMinimumSize( 0, 0 );
	qtarch_labelFont->setMaximumSize( 32767, 32767 );
	qtarch_labelFont->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelFont->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelFont->setFontPropagation( QWidget::NoChildren );
	qtarch_labelFont->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelFont->setFrameStyle( 0 );
	qtarch_labelFont->setLineWidth( 1 );
	qtarch_labelFont->setMidLineWidth( 0 );
	qtarch_labelFont->QFrame::setMargin( 0 );
	qtarch_labelFont->setText( _("Font family :") );
	qtarch_labelFont->setAlignment( 289 );
	qtarch_labelFont->setMargin( -1 );

	QLabel* qtarch_labelPagestyle;
	qtarch_labelPagestyle = new QLabel( this, "labelPagestyle" );
	qtarch_labelPagestyle->setGeometry( 114, 35, 104, 25 );
	qtarch_labelPagestyle->setMinimumSize( 0, 0 );
	qtarch_labelPagestyle->setMaximumSize( 32767, 32767 );
	qtarch_labelPagestyle->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelPagestyle->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelPagestyle->setFontPropagation( QWidget::NoChildren );
	qtarch_labelPagestyle->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelPagestyle->setFrameStyle( 0 );
	qtarch_labelPagestyle->setLineWidth( 1 );
	qtarch_labelPagestyle->setMidLineWidth( 0 );
	qtarch_labelPagestyle->QFrame::setMargin( 0 );
	qtarch_labelPagestyle->setText( _("Page style :") );
	qtarch_labelPagestyle->setAlignment( 289 );
	qtarch_labelPagestyle->setMargin( -1 );

	QLabel* qtarch_labelClass;
	qtarch_labelClass = new QLabel( this, "labelClass" );
	qtarch_labelClass->setGeometry( 114, 5, 104, 25 );
	qtarch_labelClass->setMinimumSize( 0, 0 );
	qtarch_labelClass->setMaximumSize( 32767, 32767 );
	qtarch_labelClass->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelClass->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelClass->setFontPropagation( QWidget::NoChildren );
	qtarch_labelClass->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelClass->setFrameStyle( 0 );
	qtarch_labelClass->setLineWidth( 1 );
	qtarch_labelClass->setMidLineWidth( 0 );
	qtarch_labelClass->QFrame::setMargin( 0 );
	qtarch_labelClass->setText( _("Document class :") );
	qtarch_labelClass->setAlignment( 289 );
	qtarch_labelClass->setMargin( -1 );

	combo_docclass = new QComboBox( FALSE, this, "combo_docclass" );
	combo_docclass->setGeometry( 332, 5, 104, 25 );
	combo_docclass->setMinimumSize( 0, 0 );
	combo_docclass->setMaximumSize( 32767, 32767 );
	connect( combo_docclass, SIGNAL(highlighted(const char*)), SLOT(classChanged(const char*)) );
	combo_docclass->setFocusPolicy( QWidget::StrongFocus );
	combo_docclass->setBackgroundMode( QWidget::PaletteBackground );
	combo_docclass->setFontPropagation( QWidget::AllChildren );
	combo_docclass->setPalettePropagation( QWidget::AllChildren );
	combo_docclass->setSizeLimit( 30 );
	combo_docclass->setAutoResize( false );
	combo_docclass->setMaxCount( 2147483647 );
	combo_docclass->setAutoCompletion( false );

	combo_pagestyle = new QComboBox( FALSE, this, "combo_pagestyle" );
	combo_pagestyle->setGeometry( 332, 35, 104, 25 );
	combo_pagestyle->setMinimumSize( 0, 0 );
	combo_pagestyle->setMaximumSize( 32767, 32767 );
	combo_pagestyle->setFocusPolicy( QWidget::StrongFocus );
	combo_pagestyle->setBackgroundMode( QWidget::PaletteBackground );
	combo_pagestyle->setFontPropagation( QWidget::AllChildren );
	combo_pagestyle->setPalettePropagation( QWidget::AllChildren );
	combo_pagestyle->setSizeLimit( 30 );
	combo_pagestyle->setAutoResize( false );
	combo_pagestyle->setMaxCount( 2147483647 );
	combo_pagestyle->setAutoCompletion( false );

	combo_font = new QComboBox( FALSE, this, "combo_font" );
	combo_font->setGeometry( 332, 65, 104, 25 );
	combo_font->setMinimumSize( 0, 0 );
	combo_font->setMaximumSize( 32767, 32767 );
	combo_font->setFocusPolicy( QWidget::StrongFocus );
	combo_font->setBackgroundMode( QWidget::PaletteBackground );
	combo_font->setFontPropagation( QWidget::AllChildren );
	combo_font->setPalettePropagation( QWidget::AllChildren );
	combo_font->setSizeLimit( 30 );
	combo_font->setAutoResize( false );
	combo_font->setMaxCount( 2147483647 );
	combo_font->setAutoCompletion( false );

	combo_fontsize = new QComboBox( FALSE, this, "combo_fontsize" );
	combo_fontsize->setGeometry( 332, 95, 104, 25 );
	combo_fontsize->setMinimumSize( 0, 0 );
	combo_fontsize->setMaximumSize( 32767, 32767 );
	combo_fontsize->setFocusPolicy( QWidget::StrongFocus );
	combo_fontsize->setBackgroundMode( QWidget::PaletteBackground );
	combo_fontsize->setFontPropagation( QWidget::AllChildren );
	combo_fontsize->setPalettePropagation( QWidget::AllChildren );
	combo_fontsize->setSizeLimit( 30 );
	combo_fontsize->setAutoResize( false );
	combo_fontsize->setMaxCount( 2147483647 );
	combo_fontsize->setAutoCompletion( false );

	check_sides = new QCheckBox( this, "check_sides" );
	check_sides->setGeometry( 112, 125, 107, 50 );
	check_sides->setMinimumSize( 0, 0 );
	check_sides->setMaximumSize( 32767, 32767 );
	check_sides->setFocusPolicy( QWidget::TabFocus );
	check_sides->setBackgroundMode( QWidget::PaletteBackground );
	check_sides->setFontPropagation( QWidget::NoChildren );
	check_sides->setPalettePropagation( QWidget::NoChildren );
	check_sides->setText( _("Two-sided") );
	check_sides->setAutoRepeat( false );
	check_sides->setAutoResize( false );
	check_sides->setChecked( false );

	check_columns = new QCheckBox( this, "check_columns" );
	check_columns->setGeometry( 331, 125, 107, 50 );
	check_columns->setMinimumSize( 0, 0 );
	check_columns->setMaximumSize( 32767, 32767 );
	check_columns->setFocusPolicy( QWidget::TabFocus );
	check_columns->setBackgroundMode( QWidget::PaletteBackground );
	check_columns->setFontPropagation( QWidget::NoChildren );
	check_columns->setPalettePropagation( QWidget::NoChildren );
	check_columns->setText( _("Two column pages") );
	check_columns->setAutoRepeat( false );
	check_columns->setAutoResize( false );
	check_columns->setChecked( false );

	QLabel* qtarch_labelSpacing;
	qtarch_labelSpacing = new QLabel( this, "labelSpacing" );
	qtarch_labelSpacing->setGeometry( 5, 405, 177, 50 );
	qtarch_labelSpacing->setMinimumSize( 0, 0 );
	qtarch_labelSpacing->setMaximumSize( 32767, 32767 );
	qtarch_labelSpacing->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelSpacing->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelSpacing->setFontPropagation( QWidget::NoChildren );
	qtarch_labelSpacing->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelSpacing->setFrameStyle( 0 );
	qtarch_labelSpacing->setLineWidth( 1 );
	qtarch_labelSpacing->setMidLineWidth( 0 );
	qtarch_labelSpacing->QFrame::setMargin( 0 );
	qtarch_labelSpacing->setText( _("Inter-line spacing :") );
	qtarch_labelSpacing->setAlignment( 289 );
	qtarch_labelSpacing->setMargin( -1 );

	QLabel* qtarch_labelExtraoptions;
	qtarch_labelExtraoptions = new QLabel( this, "labelExtraoptions" );
	qtarch_labelExtraoptions->setGeometry( 5, 460, 268, 50 );
	qtarch_labelExtraoptions->setMinimumSize( 0, 0 );
	qtarch_labelExtraoptions->setMaximumSize( 32767, 32767 );
	qtarch_labelExtraoptions->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelExtraoptions->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelExtraoptions->setFontPropagation( QWidget::NoChildren );
	qtarch_labelExtraoptions->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelExtraoptions->setFrameStyle( 0 );
	qtarch_labelExtraoptions->setLineWidth( 1 );
	qtarch_labelExtraoptions->setMidLineWidth( 0 );
	qtarch_labelExtraoptions->QFrame::setMargin( 0 );
	qtarch_labelExtraoptions->setText( _("Extra options :") );
	qtarch_labelExtraoptions->setAlignment( 289 );
	qtarch_labelExtraoptions->setMargin( -1 );

	QLabel* qtarch_labelSkip;
	qtarch_labelSkip = new QLabel( qtarch_paraspacingbox, "labelSkip" );
	qtarch_labelSkip->setGeometry( 5, 67, 128, 30 );
	qtarch_labelSkip->setMinimumSize( 0, 0 );
	qtarch_labelSkip->setMaximumSize( 32767, 32767 );
	qtarch_labelSkip->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelSkip->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelSkip->setFontPropagation( QWidget::NoChildren );
	qtarch_labelSkip->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelSkip->setFrameStyle( 0 );
	qtarch_labelSkip->setLineWidth( 1 );
	qtarch_labelSkip->setMidLineWidth( 0 );
	qtarch_labelSkip->QFrame::setMargin( 0 );
	qtarch_labelSkip->setText( _("Default paragraph spacing :") );
	qtarch_labelSkip->setAlignment( 289 );
	qtarch_labelSkip->setMargin( -1 );

	QLabel* qtarch_labelparasize;
	qtarch_labelparasize = new QLabel( qtarch_paraspacingbox, "labelparasize" );
	qtarch_labelparasize->setGeometry( 5, 114, 173, 30 );
	qtarch_labelparasize->setMinimumSize( 0, 0 );
	qtarch_labelparasize->setMaximumSize( 32767, 32767 );
	qtarch_labelparasize->setFocusPolicy( QWidget::NoFocus );
	qtarch_labelparasize->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_labelparasize->setFontPropagation( QWidget::NoChildren );
	qtarch_labelparasize->setPalettePropagation( QWidget::NoChildren );
	qtarch_labelparasize->setFrameStyle( 0 );
	qtarch_labelparasize->setLineWidth( 1 );
	qtarch_labelparasize->setMidLineWidth( 0 );
	qtarch_labelparasize->QFrame::setMargin( 0 );
	qtarch_labelparasize->setText( _("Size :") );
	qtarch_labelparasize->setAlignment( 289 );
	qtarch_labelparasize->setMargin( -1 );

	QLabel* qtarch_paralabelShrink;
	qtarch_paralabelShrink = new QLabel( qtarch_paraspacingbox, "paralabelShrink" );
	qtarch_paralabelShrink->setGeometry( 5, 185, 173, 30 );
	qtarch_paralabelShrink->setMinimumSize( 0, 0 );
	qtarch_paralabelShrink->setMaximumSize( 32767, 32767 );
	qtarch_paralabelShrink->setFocusPolicy( QWidget::NoFocus );
	qtarch_paralabelShrink->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_paralabelShrink->setFontPropagation( QWidget::NoChildren );
	qtarch_paralabelShrink->setPalettePropagation( QWidget::NoChildren );
	qtarch_paralabelShrink->setFrameStyle( 0 );
	qtarch_paralabelShrink->setLineWidth( 1 );
	qtarch_paralabelShrink->setMidLineWidth( 0 );
	qtarch_paralabelShrink->QFrame::setMargin( 0 );
	qtarch_paralabelShrink->setText( _("Shrink :") );
	qtarch_paralabelShrink->setAlignment( 289 );
	qtarch_paralabelShrink->setMargin( -1 );

	QLabel* qtarch_paralabelStretch;
	qtarch_paralabelStretch = new QLabel( qtarch_paraspacingbox, "paralabelStretch" );
	qtarch_paralabelStretch->setGeometry( 5, 149, 173, 31 );
	qtarch_paralabelStretch->setMinimumSize( 0, 0 );
	qtarch_paralabelStretch->setMaximumSize( 32767, 32767 );
	qtarch_paralabelStretch->setFocusPolicy( QWidget::NoFocus );
	qtarch_paralabelStretch->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_paralabelStretch->setFontPropagation( QWidget::NoChildren );
	qtarch_paralabelStretch->setPalettePropagation( QWidget::NoChildren );
	qtarch_paralabelStretch->setFrameStyle( 0 );
	qtarch_paralabelStretch->setLineWidth( 1 );
	qtarch_paralabelStretch->setMidLineWidth( 0 );
	qtarch_paralabelStretch->QFrame::setMargin( 0 );
	qtarch_paralabelStretch->setText( _("Stretch :") );
	qtarch_paralabelStretch->setAlignment( 289 );
	qtarch_paralabelStretch->setMargin( -1 );

	combo_paraspacing = new QComboBox( FALSE, qtarch_paraspacingbox, "combo_paraspacing" );
	combo_paraspacing->setGeometry( 279, 67, 128, 30 );
	combo_paraspacing->setMinimumSize( 0, 0 );
	combo_paraspacing->setMaximumSize( 32767, 32767 );
	connect( combo_paraspacing, SIGNAL(highlighted(const char*)), SLOT(paraspacingChanged(const char*)) );
	combo_paraspacing->setFocusPolicy( QWidget::StrongFocus );
	combo_paraspacing->setBackgroundMode( QWidget::PaletteBackground );
	combo_paraspacing->setFontPropagation( QWidget::AllChildren );
	combo_paraspacing->setPalettePropagation( QWidget::AllChildren );
	combo_paraspacing->setSizeLimit( 30 );
	combo_paraspacing->setAutoResize( false );
	combo_paraspacing->setMaxCount( 2147483647 );
	combo_paraspacing->setAutoCompletion( false );

	length_paraspacing = new LengthEntry( qtarch_paraspacingbox, "length_paraspacing" );
	length_paraspacing->setGeometry( 183, 114, 174, 30 );
	length_paraspacing->setMinimumSize( 0, 0 );
	length_paraspacing->setMaximumSize( 32767, 32767 );
	length_paraspacing->setFocusPolicy( QWidget::NoFocus );
	length_paraspacing->setBackgroundMode( QWidget::PaletteBackground );
	length_paraspacing->setFontPropagation( QWidget::NoChildren );
	length_paraspacing->setPalettePropagation( QWidget::NoChildren );

	length_paraspacingstretch = new LengthEntry( qtarch_paraspacingbox, "length_paraspacingstretch" );
	length_paraspacingstretch->setGeometry( 183, 149, 174, 31 );
	length_paraspacingstretch->setMinimumSize( 0, 0 );
	length_paraspacingstretch->setMaximumSize( 32767, 32767 );
	length_paraspacingstretch->setFocusPolicy( QWidget::NoFocus );
	length_paraspacingstretch->setBackgroundMode( QWidget::PaletteBackground );
	length_paraspacingstretch->setFontPropagation( QWidget::NoChildren );
	length_paraspacingstretch->setPalettePropagation( QWidget::NoChildren );

	length_paraspacingshrink = new LengthEntry( qtarch_paraspacingbox, "length_paraspacingshrink" );
	length_paraspacingshrink->setGeometry( 183, 185, 174, 30 );
	length_paraspacingshrink->setMinimumSize( 0, 0 );
	length_paraspacingshrink->setMaximumSize( 32767, 32767 );
	length_paraspacingshrink->setFocusPolicy( QWidget::NoFocus );
	length_paraspacingshrink->setBackgroundMode( QWidget::PaletteBackground );
	length_paraspacingshrink->setFontPropagation( QWidget::NoChildren );
	length_paraspacingshrink->setPalettePropagation( QWidget::NoChildren );

	combo_linespacing = new QComboBox( FALSE, this, "combo_linespacing" );
	combo_linespacing->setGeometry( 187, 405, 176, 50 );
	combo_linespacing->setMinimumSize( 0, 0 );
	combo_linespacing->setMaximumSize( 32767, 32767 );
	combo_linespacing->setFocusPolicy( QWidget::StrongFocus );
	combo_linespacing->setBackgroundMode( QWidget::PaletteBackground );
	combo_linespacing->setFontPropagation( QWidget::AllChildren );
	combo_linespacing->setPalettePropagation( QWidget::AllChildren );
	combo_linespacing->setSizeLimit( 30 );
	combo_linespacing->setAutoResize( false );
	combo_linespacing->setMaxCount( 2147483647 );
	combo_linespacing->setAutoCompletion( false );

	line_linespacing = new KRestrictedLine( this, "line_linespacing" );
	line_linespacing->setGeometry( 368, 405, 177, 50 );
	line_linespacing->setMinimumSize( 0, 0 );
	line_linespacing->setMaximumSize( 32767, 32767 );
	line_linespacing->setFocusPolicy( QWidget::StrongFocus );
	line_linespacing->setBackgroundMode( QWidget::PaletteBase );
	line_linespacing->setFontPropagation( QWidget::NoChildren );
	line_linespacing->setPalettePropagation( QWidget::NoChildren );
	line_linespacing->setText( "" );
	line_linespacing->setMaxLength( 32767 );
	line_linespacing->setFrame( QLineEdit::Normal );
	line_linespacing->setFrame( true );
	line_linespacing->setValidChars( "0123456789.," );

	line_extraoptions = new QLineEdit( this, "line_extraoptions" );
	line_extraoptions->setGeometry( 278, 460, 267, 50 );
	line_extraoptions->setMinimumSize( 0, 0 );
	line_extraoptions->setMaximumSize( 32767, 32767 );
	line_extraoptions->setFocusPolicy( QWidget::StrongFocus );
	line_extraoptions->setBackgroundMode( QWidget::PaletteBase );
	line_extraoptions->setFontPropagation( QWidget::NoChildren );
	line_extraoptions->setPalettePropagation( QWidget::NoChildren );
	line_extraoptions->setText( "" );
	line_extraoptions->setMaxLength( 32767 );
	line_extraoptions->setFrame( QLineEdit::Normal );
	line_extraoptions->setFrame( true );

	check_addspace = new QCheckBox( this, "check_addspace" );
	check_addspace->setGeometry( 10, 200, 398, 30 );
	check_addspace->setMinimumSize( 0, 0 );
	check_addspace->setMaximumSize( 32767, 32767 );
	connect( check_addspace, SIGNAL(toggled(bool)), SLOT(addspaceChanged(bool)) );
	check_addspace->setFocusPolicy( QWidget::TabFocus );
	check_addspace->setBackgroundMode( QWidget::PaletteBackground );
	check_addspace->setFontPropagation( QWidget::NoChildren );
	check_addspace->setPalettePropagation( QWidget::NoChildren );
	check_addspace->setText( _("Add space") );
	check_addspace->setAutoRepeat( false );
	check_addspace->setAutoResize( false );
	check_addspace->setChecked( false );

	if (qtarch_paraspacingbox->sizeHint().width()!=-1)
		qtarch_paraspacingbox->setMinimumWidth(qtarch_paraspacingbox->sizeHint().width());
	if (qtarch_paraspacingbox->sizeHint().height()!=-1)
		qtarch_paraspacingbox->setMinimumHeight(qtarch_paraspacingbox->sizeHint().height());
	if (qtarch_labelFontSize->sizeHint().width()!=-1)
		qtarch_labelFontSize->setMinimumWidth(qtarch_labelFontSize->sizeHint().width());
	if (qtarch_labelFontSize->sizeHint().height()!=-1)
		qtarch_labelFontSize->setMinimumHeight(qtarch_labelFontSize->sizeHint().height());
	if (qtarch_labelFontSize->sizeHint().width()!=-1)
		qtarch_labelFontSize->setMaximumWidth(qtarch_labelFontSize->sizeHint().width());
	if (qtarch_labelFontSize->sizeHint().height()!=-1)
		qtarch_labelFontSize->setMaximumHeight(qtarch_labelFontSize->sizeHint().height());
	if (qtarch_labelFont->sizeHint().width()!=-1)
		qtarch_labelFont->setMinimumWidth(qtarch_labelFont->sizeHint().width());
	if (qtarch_labelFont->sizeHint().height()!=-1)
		qtarch_labelFont->setMinimumHeight(qtarch_labelFont->sizeHint().height());
	if (qtarch_labelFont->sizeHint().width()!=-1)
		qtarch_labelFont->setMaximumWidth(qtarch_labelFont->sizeHint().width());
	if (qtarch_labelFont->sizeHint().height()!=-1)
		qtarch_labelFont->setMaximumHeight(qtarch_labelFont->sizeHint().height());
	if (qtarch_labelPagestyle->sizeHint().width()!=-1)
		qtarch_labelPagestyle->setMinimumWidth(qtarch_labelPagestyle->sizeHint().width());
	if (qtarch_labelPagestyle->sizeHint().height()!=-1)
		qtarch_labelPagestyle->setMinimumHeight(qtarch_labelPagestyle->sizeHint().height());
	if (qtarch_labelPagestyle->sizeHint().width()!=-1)
		qtarch_labelPagestyle->setMaximumWidth(qtarch_labelPagestyle->sizeHint().width());
	if (qtarch_labelPagestyle->sizeHint().height()!=-1)
		qtarch_labelPagestyle->setMaximumHeight(qtarch_labelPagestyle->sizeHint().height());
	if (qtarch_labelClass->sizeHint().width()!=-1)
		qtarch_labelClass->setMinimumWidth(qtarch_labelClass->sizeHint().width());
	if (qtarch_labelClass->sizeHint().height()!=-1)
		qtarch_labelClass->setMinimumHeight(qtarch_labelClass->sizeHint().height());
	if (qtarch_labelClass->sizeHint().width()!=-1)
		qtarch_labelClass->setMaximumWidth(qtarch_labelClass->sizeHint().width());
	if (qtarch_labelClass->sizeHint().height()!=-1)
		qtarch_labelClass->setMaximumHeight(qtarch_labelClass->sizeHint().height());
	if (combo_docclass->sizeHint().width()!=-1)
		combo_docclass->setMinimumWidth(combo_docclass->sizeHint().width());
	if (combo_docclass->sizeHint().height()!=-1)
		combo_docclass->setMinimumHeight(combo_docclass->sizeHint().height());
	if (combo_docclass->sizeHint().height()!=-1)
		combo_docclass->setMaximumHeight(combo_docclass->sizeHint().height());
	if (combo_pagestyle->sizeHint().width()!=-1)
		combo_pagestyle->setMinimumWidth(combo_pagestyle->sizeHint().width());
	if (combo_pagestyle->sizeHint().height()!=-1)
		combo_pagestyle->setMinimumHeight(combo_pagestyle->sizeHint().height());
	if (combo_pagestyle->sizeHint().height()!=-1)
		combo_pagestyle->setMaximumHeight(combo_pagestyle->sizeHint().height());
	if (combo_font->sizeHint().width()!=-1)
		combo_font->setMinimumWidth(combo_font->sizeHint().width());
	if (combo_font->sizeHint().height()!=-1)
		combo_font->setMinimumHeight(combo_font->sizeHint().height());
	if (combo_font->sizeHint().height()!=-1)
		combo_font->setMaximumHeight(combo_font->sizeHint().height());
	if (combo_fontsize->sizeHint().width()!=-1)
		combo_fontsize->setMinimumWidth(combo_fontsize->sizeHint().width());
	if (combo_fontsize->sizeHint().height()!=-1)
		combo_fontsize->setMinimumHeight(combo_fontsize->sizeHint().height());
	if (combo_fontsize->sizeHint().height()!=-1)
		combo_fontsize->setMaximumHeight(combo_fontsize->sizeHint().height());
	if (check_sides->sizeHint().width()!=-1)
		check_sides->setMinimumWidth(check_sides->sizeHint().width());
	if (check_sides->sizeHint().height()!=-1)
		check_sides->setMinimumHeight(check_sides->sizeHint().height());
	if (check_sides->sizeHint().width()!=-1)
		check_sides->setMaximumWidth(check_sides->sizeHint().width());
	if (check_sides->sizeHint().height()!=-1)
		check_sides->setMaximumHeight(check_sides->sizeHint().height());
	if (check_columns->sizeHint().width()!=-1)
		check_columns->setMinimumWidth(check_columns->sizeHint().width());
	if (check_columns->sizeHint().height()!=-1)
		check_columns->setMinimumHeight(check_columns->sizeHint().height());
	if (check_columns->sizeHint().width()!=-1)
		check_columns->setMaximumWidth(check_columns->sizeHint().width());
	if (check_columns->sizeHint().height()!=-1)
		check_columns->setMaximumHeight(check_columns->sizeHint().height());
	if (qtarch_labelSpacing->sizeHint().width()!=-1)
		qtarch_labelSpacing->setMinimumWidth(qtarch_labelSpacing->sizeHint().width());
	if (qtarch_labelSpacing->sizeHint().height()!=-1)
		qtarch_labelSpacing->setMinimumHeight(qtarch_labelSpacing->sizeHint().height());
	if (qtarch_labelSpacing->sizeHint().width()!=-1)
		qtarch_labelSpacing->setMaximumWidth(qtarch_labelSpacing->sizeHint().width());
	if (qtarch_labelSpacing->sizeHint().height()!=-1)
		qtarch_labelSpacing->setMaximumHeight(qtarch_labelSpacing->sizeHint().height());
	if (qtarch_labelExtraoptions->sizeHint().width()!=-1)
		qtarch_labelExtraoptions->setMinimumWidth(qtarch_labelExtraoptions->sizeHint().width());
	if (qtarch_labelExtraoptions->sizeHint().height()!=-1)
		qtarch_labelExtraoptions->setMinimumHeight(qtarch_labelExtraoptions->sizeHint().height());
	if (qtarch_labelExtraoptions->sizeHint().width()!=-1)
		qtarch_labelExtraoptions->setMaximumWidth(qtarch_labelExtraoptions->sizeHint().width());
	if (qtarch_labelExtraoptions->sizeHint().height()!=-1)
		qtarch_labelExtraoptions->setMaximumHeight(qtarch_labelExtraoptions->sizeHint().height());
	if (qtarch_labelSkip->sizeHint().width()!=-1)
		qtarch_labelSkip->setMinimumWidth(qtarch_labelSkip->sizeHint().width());
	if (qtarch_labelSkip->sizeHint().height()!=-1)
		qtarch_labelSkip->setMinimumHeight(qtarch_labelSkip->sizeHint().height());
	if (qtarch_labelSkip->sizeHint().width()!=-1)
		qtarch_labelSkip->setMaximumWidth(qtarch_labelSkip->sizeHint().width());
	if (qtarch_labelSkip->sizeHint().height()!=-1)
		qtarch_labelSkip->setMaximumHeight(qtarch_labelSkip->sizeHint().height());
	if (qtarch_labelparasize->sizeHint().width()!=-1)
		qtarch_labelparasize->setMinimumWidth(qtarch_labelparasize->sizeHint().width());
	if (qtarch_labelparasize->sizeHint().height()!=-1)
		qtarch_labelparasize->setMinimumHeight(qtarch_labelparasize->sizeHint().height());
	if (qtarch_labelparasize->sizeHint().width()!=-1)
		qtarch_labelparasize->setMaximumWidth(qtarch_labelparasize->sizeHint().width());
	if (qtarch_labelparasize->sizeHint().height()!=-1)
		qtarch_labelparasize->setMaximumHeight(qtarch_labelparasize->sizeHint().height());
	if (qtarch_paralabelShrink->sizeHint().width()!=-1)
		qtarch_paralabelShrink->setMinimumWidth(qtarch_paralabelShrink->sizeHint().width());
	if (qtarch_paralabelShrink->sizeHint().height()!=-1)
		qtarch_paralabelShrink->setMinimumHeight(qtarch_paralabelShrink->sizeHint().height());
	if (qtarch_paralabelShrink->sizeHint().width()!=-1)
		qtarch_paralabelShrink->setMaximumWidth(qtarch_paralabelShrink->sizeHint().width());
	if (qtarch_paralabelShrink->sizeHint().height()!=-1)
		qtarch_paralabelShrink->setMaximumHeight(qtarch_paralabelShrink->sizeHint().height());
	if (qtarch_paralabelStretch->sizeHint().width()!=-1)
		qtarch_paralabelStretch->setMinimumWidth(qtarch_paralabelStretch->sizeHint().width());
	if (qtarch_paralabelStretch->sizeHint().height()!=-1)
		qtarch_paralabelStretch->setMinimumHeight(qtarch_paralabelStretch->sizeHint().height());
	if (qtarch_paralabelStretch->sizeHint().width()!=-1)
		qtarch_paralabelStretch->setMaximumWidth(qtarch_paralabelStretch->sizeHint().width());
	if (qtarch_paralabelStretch->sizeHint().height()!=-1)
		qtarch_paralabelStretch->setMaximumHeight(qtarch_paralabelStretch->sizeHint().height());
	if (combo_paraspacing->sizeHint().width()!=-1)
		combo_paraspacing->setMinimumWidth(combo_paraspacing->sizeHint().width());
	if (combo_paraspacing->sizeHint().height()!=-1)
		combo_paraspacing->setMinimumHeight(combo_paraspacing->sizeHint().height());
	if (combo_paraspacing->sizeHint().height()!=-1)
		combo_paraspacing->setMaximumHeight(combo_paraspacing->sizeHint().height());
	if (length_paraspacing->sizeHint().width()!=-1)
		length_paraspacing->setMinimumWidth(length_paraspacing->sizeHint().width());
	if (length_paraspacing->sizeHint().height()!=-1)
		length_paraspacing->setMinimumHeight(length_paraspacing->sizeHint().height());
	if (length_paraspacing->sizeHint().height()!=-1)
		length_paraspacing->setMaximumHeight(length_paraspacing->sizeHint().height());
	if (length_paraspacingstretch->sizeHint().width()!=-1)
		length_paraspacingstretch->setMinimumWidth(length_paraspacingstretch->sizeHint().width());
	if (length_paraspacingstretch->sizeHint().height()!=-1)
		length_paraspacingstretch->setMinimumHeight(length_paraspacingstretch->sizeHint().height());
	if (length_paraspacingstretch->sizeHint().height()!=-1)
		length_paraspacingstretch->setMaximumHeight(length_paraspacingstretch->sizeHint().height());
	if (length_paraspacingshrink->sizeHint().width()!=-1)
		length_paraspacingshrink->setMinimumWidth(length_paraspacingshrink->sizeHint().width());
	if (length_paraspacingshrink->sizeHint().height()!=-1)
		length_paraspacingshrink->setMinimumHeight(length_paraspacingshrink->sizeHint().height());
	if (length_paraspacingshrink->sizeHint().height()!=-1)
		length_paraspacingshrink->setMaximumHeight(length_paraspacingshrink->sizeHint().height());
	if (combo_linespacing->sizeHint().width()!=-1)
		combo_linespacing->setMinimumWidth(combo_linespacing->sizeHint().width());
	if (combo_linespacing->sizeHint().height()!=-1)
		combo_linespacing->setMinimumHeight(combo_linespacing->sizeHint().height());
	if (combo_linespacing->sizeHint().height()!=-1)
		combo_linespacing->setMaximumHeight(combo_linespacing->sizeHint().height());
	if (line_linespacing->sizeHint().width()!=-1)
		line_linespacing->setMinimumWidth(line_linespacing->sizeHint().width());
	if (line_linespacing->sizeHint().height()!=-1)
		line_linespacing->setMinimumHeight(line_linespacing->sizeHint().height());
	if (line_linespacing->sizeHint().height()!=-1)
		line_linespacing->setMaximumHeight(line_linespacing->sizeHint().height());
	if (line_extraoptions->sizeHint().width()!=-1)
		line_extraoptions->setMinimumWidth(line_extraoptions->sizeHint().width());
	if (line_extraoptions->sizeHint().height()!=-1)
		line_extraoptions->setMinimumHeight(line_extraoptions->sizeHint().height());
	if (line_extraoptions->sizeHint().height()!=-1)
		line_extraoptions->setMaximumHeight(line_extraoptions->sizeHint().height());
	if (check_addspace->sizeHint().width()!=-1)
		check_addspace->setMinimumWidth(check_addspace->sizeHint().width());
	if (check_addspace->sizeHint().height()!=-1)
		check_addspace->setMinimumHeight(check_addspace->sizeHint().height());
	if (check_addspace->sizeHint().width()!=-1)
		check_addspace->setMaximumWidth(check_addspace->sizeHint().width());
	if (check_addspace->sizeHint().height()!=-1)
		check_addspace->setMaximumHeight(check_addspace->sizeHint().height());
	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	QGridLayout* qtarch_layout_1_1 = new QGridLayout( 4, 5, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_1, 2 );
	qtarch_layout_1_1->addColSpacing( 0, 5 );
	qtarch_layout_1_1->setColStretch( 0, 1 );
	qtarch_layout_1_1->addColSpacing( 1, 5 );
	qtarch_layout_1_1->setColStretch( 1, 1 );
	qtarch_layout_1_1->addColSpacing( 2, 5 );
	qtarch_layout_1_1->setColStretch( 2, 1 );
	qtarch_layout_1_1->addColSpacing( 3, 5 );
	qtarch_layout_1_1->setColStretch( 3, 1 );
	qtarch_layout_1_1->addColSpacing( 4, 5 );
	qtarch_layout_1_1->setColStretch( 4, 1 );
	qtarch_layout_1_1->addRowSpacing( 0, 0 );
	qtarch_layout_1_1->setRowStretch( 0, 1 );
	qtarch_layout_1_1->addWidget( qtarch_labelClass, 0, 1, 33 );
	qtarch_layout_1_1->addWidget( combo_docclass, 0, 3, 33 );
	qtarch_layout_1_1->addRowSpacing( 1, 0 );
	qtarch_layout_1_1->setRowStretch( 1, 1 );
	qtarch_layout_1_1->addWidget( qtarch_labelPagestyle, 1, 1, 33 );
	qtarch_layout_1_1->addWidget( combo_pagestyle, 1, 3, 33 );
	qtarch_layout_1_1->addRowSpacing( 2, 0 );
	qtarch_layout_1_1->setRowStretch( 2, 1 );
	qtarch_layout_1_1->addWidget( qtarch_labelFont, 2, 1, 33 );
	qtarch_layout_1_1->addWidget( combo_font, 2, 3, 33 );
	qtarch_layout_1_1->addRowSpacing( 3, 0 );
	qtarch_layout_1_1->setRowStretch( 3, 1 );
	qtarch_layout_1_1->addWidget( qtarch_labelFontSize, 3, 1, 33 );
	qtarch_layout_1_1->addWidget( combo_fontsize, 3, 3, 33 );
	QBoxLayout* qtarch_layout_1_2 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2, 1 );
	qtarch_layout_1_2->addStrut( 0 );
	qtarch_layout_1_2->addStretch( 1 );
	qtarch_layout_1_2->addWidget( check_sides, 1, 33 );
	qtarch_layout_1_2->addStretch( 1 );
	qtarch_layout_1_2->addWidget( check_columns, 1, 33 );
	qtarch_layout_1_2->addStretch( 1 );
	qtarch_layout_1->addWidget( qtarch_paraspacingbox, 3, 33 );
	QBoxLayout* qtarch_layout_1_3 = new QBoxLayout( qtarch_paraspacingbox, QBoxLayout::TopToBottom, 5, 17, NULL );
	qtarch_layout_1_3->addStrut( 0 );
	qtarch_layout_1_3->addSpacing( 15 );
	QBoxLayout* qtarch_layout_1_3_2 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1_3->addLayout( qtarch_layout_1_3_2, 1 );
	qtarch_layout_1_3_2->addStrut( 0 );
	qtarch_layout_1_3_2->addStretch( 1 );
	QBoxLayout* qtarch_layout_1_3_3 = new QBoxLayout( QBoxLayout::LeftToRight, 17, NULL );
	qtarch_layout_1_3->addLayout( qtarch_layout_1_3_3, 1 );
	qtarch_layout_1_3_3->addStrut( 0 );
	qtarch_layout_1_3_3->addWidget( qtarch_labelSkip, 1, 36 );
	qtarch_layout_1_3_3->addStretch( 1 );
	qtarch_layout_1_3_3->addWidget( combo_paraspacing, 1, 36 );
	qtarch_layout_1_3_3->addStretch( 1 );
	QGridLayout* qtarch_layout_1_3_4 = new QGridLayout( 3, 3, 5, NULL );
	qtarch_layout_1_3->addLayout( qtarch_layout_1_3_4, 3 );
	qtarch_layout_1_3_4->addColSpacing( 0, 5 );
	qtarch_layout_1_3_4->setColStretch( 0, 1 );
	qtarch_layout_1_3_4->addColSpacing( 1, 5 );
	qtarch_layout_1_3_4->setColStretch( 1, 1 );
	qtarch_layout_1_3_4->addColSpacing( 2, 5 );
	qtarch_layout_1_3_4->setColStretch( 2, 1 );
	qtarch_layout_1_3_4->addRowSpacing( 0, 0 );
	qtarch_layout_1_3_4->setRowStretch( 0, 1 );
	qtarch_layout_1_3_4->addWidget( qtarch_labelparasize, 0, 0, 33 );
	qtarch_layout_1_3_4->addWidget( length_paraspacing, 0, 1, 33 );
	qtarch_layout_1_3_4->addRowSpacing( 1, 0 );
	qtarch_layout_1_3_4->setRowStretch( 1, 1 );
	qtarch_layout_1_3_4->addWidget( qtarch_paralabelStretch, 1, 0, 33 );
	qtarch_layout_1_3_4->addWidget( length_paraspacingstretch, 1, 1, 33 );
	qtarch_layout_1_3_4->addRowSpacing( 2, 0 );
	qtarch_layout_1_3_4->setRowStretch( 2, 1 );
	qtarch_layout_1_3_4->addWidget( qtarch_paralabelShrink, 2, 0, 33 );
	qtarch_layout_1_3_4->addWidget( length_paraspacingshrink, 2, 1, 33 );
	QBoxLayout* qtarch_layout_1_4 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_4, 1 );
	qtarch_layout_1_4->addStrut( 0 );
	qtarch_layout_1_4->addWidget( qtarch_labelSpacing, 1, 36 );
	qtarch_layout_1_4->addWidget( combo_linespacing, 1, 36 );
	qtarch_layout_1_4->addWidget( line_linespacing, 1, 36 );
	QBoxLayout* qtarch_layout_1_5 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_5, 1 );
	qtarch_layout_1_5->addStrut( 0 );
	qtarch_layout_1_5->addWidget( qtarch_labelExtraoptions, 1, 36 );
	qtarch_layout_1_5->addWidget( line_extraoptions, 1, 33 );
	setGeometry( 0,0, 550,515 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


DocSettingsDialogData::~DocSettingsDialogData()
{
}
void DocSettingsDialogData::classChanged(const char*)
{
}
void DocSettingsDialogData::paraspacingChanged(const char*)
{
}
void DocSettingsDialogData::addspaceChanged(bool)
{
}
