/**********************************************************************

	--- Qt Architect 1.4-6 generated file ---

	File: logdlgdata.h
	Last generated: Sat Mar 31 16:48:46 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef LogDialogData_included
#define LogDialogData_included

#include <qdialog.h>
#include <qpushbutton.h>
#include <qmultilinedit.h>

class LogDialogData : public QDialog
{
    Q_OBJECT

public:

    LogDialogData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~LogDialogData();

public slots:


protected slots:

    virtual void updatePressed();
    virtual void closePressed();

public:
    QPushButton* button_cancel;
    QPushButton* button_update;
    QMultiLineEdit* line_viewer;

};

#endif // LogDialogData_included
