/**********************************************************************

	--- Qt Architect 1.4-6 generated file ---

	File: parabelowdlgdata.C
	Last generated: Sat Mar 31 16:48:58 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <gettext.h>

#include <qpixmap.h>
#include <qlayout.h>
#include "parabelowdlgdata.h"

#define Inherited QWidget

#include <qlabel.h>

ParaBelowDialogData::ParaBelowDialogData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	check_pagebreakbelow = new QCheckBox( this, "check_pagebreakbelow" );
	check_pagebreakbelow->setGeometry( 5, 5, 228, 67 );
	check_pagebreakbelow->setMinimumSize( 0, 0 );
	check_pagebreakbelow->setMaximumSize( 32767, 32767 );
	check_pagebreakbelow->setFocusPolicy( QWidget::TabFocus );
	check_pagebreakbelow->setBackgroundMode( QWidget::PaletteBackground );
	check_pagebreakbelow->setFontPropagation( QWidget::NoChildren );
	check_pagebreakbelow->setPalettePropagation( QWidget::NoChildren );
	check_pagebreakbelow->setText( _("Page break") );
	check_pagebreakbelow->setAutoRepeat( false );
	check_pagebreakbelow->setAutoResize( false );
	check_pagebreakbelow->setChecked( false );

	check_keepbelow = new QCheckBox( this, "check_keepbelow" );
	check_keepbelow->setGeometry( 5, 77, 228, 66 );
	check_keepbelow->setMinimumSize( 0, 0 );
	check_keepbelow->setMaximumSize( 32767, 32767 );
	check_keepbelow->setFocusPolicy( QWidget::TabFocus );
	check_keepbelow->setBackgroundMode( QWidget::PaletteBackground );
	check_keepbelow->setFontPropagation( QWidget::NoChildren );
	check_keepbelow->setPalettePropagation( QWidget::NoChildren );
	check_keepbelow->setText( _("Keep space when at top of page") );
	check_keepbelow->setAutoRepeat( false );
	check_keepbelow->setAutoResize( false );
	check_keepbelow->setChecked( false );

	QLabel* qtarch_belowlabel;
	qtarch_belowlabel = new QLabel( this, "belowlabel" );
	qtarch_belowlabel->setGeometry( 5, 148, 113, 67 );
	qtarch_belowlabel->setMinimumSize( 0, 0 );
	qtarch_belowlabel->setMaximumSize( 32767, 32767 );
	qtarch_belowlabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_belowlabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_belowlabel->setFontPropagation( QWidget::NoChildren );
	qtarch_belowlabel->setPalettePropagation( QWidget::NoChildren );
	qtarch_belowlabel->setFrameStyle( 0 );
	qtarch_belowlabel->setLineWidth( 1 );
	qtarch_belowlabel->setMidLineWidth( 0 );
	qtarch_belowlabel->QFrame::setMargin( 0 );
	qtarch_belowlabel->setText( _("Extra Space") );
	qtarch_belowlabel->setAlignment( 289 );
	qtarch_belowlabel->setMargin( -1 );

	combo_spacebelow = new QComboBox( FALSE, this, "combo_spacebelow" );
	combo_spacebelow->setGeometry( 235, 148, 113, 67 );
	combo_spacebelow->setMinimumSize( 0, 0 );
	combo_spacebelow->setMaximumSize( 32767, 32767 );
	connect( combo_spacebelow, SIGNAL(highlighted(int)), SLOT(spacebelowHighlighted(int)) );
	combo_spacebelow->setFocusPolicy( QWidget::StrongFocus );
	combo_spacebelow->setBackgroundMode( QWidget::PaletteBackground );
	combo_spacebelow->setFontPropagation( QWidget::AllChildren );
	combo_spacebelow->setPalettePropagation( QWidget::AllChildren );
	combo_spacebelow->setSizeLimit( 10 );
	combo_spacebelow->setAutoResize( false );
	combo_spacebelow->setMaxCount( 2147483647 );
	combo_spacebelow->setAutoCompletion( false );

	QLabel* qtarch_ValueLabel;
	qtarch_ValueLabel = new QLabel( this, "ValueLabel" );
	qtarch_ValueLabel->setGeometry( 61, 220, 96, 67 );
	qtarch_ValueLabel->setMinimumSize( 0, 0 );
	qtarch_ValueLabel->setMaximumSize( 32767, 32767 );
	qtarch_ValueLabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_ValueLabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_ValueLabel->setFontPropagation( QWidget::NoChildren );
	qtarch_ValueLabel->setPalettePropagation( QWidget::NoChildren );
	qtarch_ValueLabel->setFrameStyle( 0 );
	qtarch_ValueLabel->setLineWidth( 1 );
	qtarch_ValueLabel->setMidLineWidth( 0 );
	qtarch_ValueLabel->QFrame::setMargin( 0 );
	qtarch_ValueLabel->setText( _("Size") );
	qtarch_ValueLabel->setAlignment( 289 );
	qtarch_ValueLabel->setMargin( -1 );

	QLabel* qtarch_Label_14;
	qtarch_Label_14 = new QLabel( this, "Label_14" );
	qtarch_Label_14->setGeometry( 61, 292, 96, 66 );
	qtarch_Label_14->setMinimumSize( 0, 0 );
	qtarch_Label_14->setMaximumSize( 32767, 32767 );
	qtarch_Label_14->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_14->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_14->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_14->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_14->setFrameStyle( 0 );
	qtarch_Label_14->setLineWidth( 1 );
	qtarch_Label_14->setMidLineWidth( 0 );
	qtarch_Label_14->QFrame::setMargin( 0 );
	qtarch_Label_14->setText( _("Stretch") );
	qtarch_Label_14->setAlignment( 289 );
	qtarch_Label_14->setMargin( -1 );

	QLabel* qtarch_belowminuslabel;
	qtarch_belowminuslabel = new QLabel( this, "belowminuslabel" );
	qtarch_belowminuslabel->setGeometry( 61, 363, 96, 67 );
	qtarch_belowminuslabel->setMinimumSize( 0, 0 );
	qtarch_belowminuslabel->setMaximumSize( 32767, 32767 );
	qtarch_belowminuslabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_belowminuslabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_belowminuslabel->setFontPropagation( QWidget::NoChildren );
	qtarch_belowminuslabel->setPalettePropagation( QWidget::NoChildren );
	qtarch_belowminuslabel->setFrameStyle( 0 );
	qtarch_belowminuslabel->setLineWidth( 1 );
	qtarch_belowminuslabel->setMidLineWidth( 0 );
	qtarch_belowminuslabel->QFrame::setMargin( 0 );
	qtarch_belowminuslabel->setText( _("Shrink") );
	qtarch_belowminuslabel->setAlignment( 289 );
	qtarch_belowminuslabel->setMargin( -1 );

	length_spacebelow = new LengthEntry( this, "length_spacebelow" );
	length_spacebelow->setGeometry( 217, 220, 187, 67 );
	length_spacebelow->setMinimumSize( 0, 0 );
	length_spacebelow->setMaximumSize( 32767, 32767 );
	length_spacebelow->setFocusPolicy( QWidget::NoFocus );
	length_spacebelow->setBackgroundMode( QWidget::PaletteBackground );
	length_spacebelow->setFontPropagation( QWidget::NoChildren );
	length_spacebelow->setPalettePropagation( QWidget::NoChildren );

	length_spacebelowplus = new LengthEntry( this, "length_spacebelowplus" );
	length_spacebelowplus->setGeometry( 217, 292, 187, 66 );
	length_spacebelowplus->setMinimumSize( 0, 0 );
	length_spacebelowplus->setMaximumSize( 32767, 32767 );
	length_spacebelowplus->setFocusPolicy( QWidget::NoFocus );
	length_spacebelowplus->setBackgroundMode( QWidget::PaletteBackground );
	length_spacebelowplus->setFontPropagation( QWidget::NoChildren );
	length_spacebelowplus->setPalettePropagation( QWidget::NoChildren );

	length_spacebelowminus = new LengthEntry( this, "length_spacebelowminus" );
	length_spacebelowminus->setGeometry( 217, 363, 187, 67 );
	length_spacebelowminus->setMinimumSize( 0, 0 );
	length_spacebelowminus->setMaximumSize( 32767, 32767 );
	length_spacebelowminus->setFocusPolicy( QWidget::NoFocus );
	length_spacebelowminus->setBackgroundMode( QWidget::PaletteBackground );
	length_spacebelowminus->setFontPropagation( QWidget::NoChildren );
	length_spacebelowminus->setPalettePropagation( QWidget::NoChildren );

	if (check_pagebreakbelow->sizeHint().width()!=-1)
		check_pagebreakbelow->setMinimumWidth(check_pagebreakbelow->sizeHint().width());
	if (check_pagebreakbelow->sizeHint().height()!=-1)
		check_pagebreakbelow->setMinimumHeight(check_pagebreakbelow->sizeHint().height());
	if (check_pagebreakbelow->sizeHint().width()!=-1)
		check_pagebreakbelow->setMaximumWidth(check_pagebreakbelow->sizeHint().width());
	if (check_pagebreakbelow->sizeHint().height()!=-1)
		check_pagebreakbelow->setMaximumHeight(check_pagebreakbelow->sizeHint().height());
	if (check_keepbelow->sizeHint().width()!=-1)
		check_keepbelow->setMinimumWidth(check_keepbelow->sizeHint().width());
	if (check_keepbelow->sizeHint().height()!=-1)
		check_keepbelow->setMinimumHeight(check_keepbelow->sizeHint().height());
	if (check_keepbelow->sizeHint().width()!=-1)
		check_keepbelow->setMaximumWidth(check_keepbelow->sizeHint().width());
	if (check_keepbelow->sizeHint().height()!=-1)
		check_keepbelow->setMaximumHeight(check_keepbelow->sizeHint().height());
	if (qtarch_belowlabel->sizeHint().width()!=-1)
		qtarch_belowlabel->setMinimumWidth(qtarch_belowlabel->sizeHint().width());
	if (qtarch_belowlabel->sizeHint().height()!=-1)
		qtarch_belowlabel->setMinimumHeight(qtarch_belowlabel->sizeHint().height());
	if (qtarch_belowlabel->sizeHint().width()!=-1)
		qtarch_belowlabel->setMaximumWidth(qtarch_belowlabel->sizeHint().width());
	if (qtarch_belowlabel->sizeHint().height()!=-1)
		qtarch_belowlabel->setMaximumHeight(qtarch_belowlabel->sizeHint().height());
	if (combo_spacebelow->sizeHint().width()!=-1)
		combo_spacebelow->setMinimumWidth(combo_spacebelow->sizeHint().width());
	if (combo_spacebelow->sizeHint().height()!=-1)
		combo_spacebelow->setMinimumHeight(combo_spacebelow->sizeHint().height());
	if (combo_spacebelow->sizeHint().height()!=-1)
		combo_spacebelow->setMaximumHeight(combo_spacebelow->sizeHint().height());
	if (qtarch_ValueLabel->sizeHint().width()!=-1)
		qtarch_ValueLabel->setMinimumWidth(qtarch_ValueLabel->sizeHint().width());
	if (qtarch_ValueLabel->sizeHint().height()!=-1)
		qtarch_ValueLabel->setMinimumHeight(qtarch_ValueLabel->sizeHint().height());
	if (qtarch_Label_14->sizeHint().width()!=-1)
		qtarch_Label_14->setMinimumWidth(qtarch_Label_14->sizeHint().width());
	if (qtarch_Label_14->sizeHint().height()!=-1)
		qtarch_Label_14->setMinimumHeight(qtarch_Label_14->sizeHint().height());
	if (qtarch_belowminuslabel->sizeHint().width()!=-1)
		qtarch_belowminuslabel->setMinimumWidth(qtarch_belowminuslabel->sizeHint().width());
	if (qtarch_belowminuslabel->sizeHint().height()!=-1)
		qtarch_belowminuslabel->setMinimumHeight(qtarch_belowminuslabel->sizeHint().height());
	if (length_spacebelow->sizeHint().width()!=-1)
		length_spacebelow->setMinimumWidth(length_spacebelow->sizeHint().width());
	if (length_spacebelow->sizeHint().height()!=-1)
		length_spacebelow->setMinimumHeight(length_spacebelow->sizeHint().height());
	if (length_spacebelowplus->sizeHint().width()!=-1)
		length_spacebelowplus->setMinimumWidth(length_spacebelowplus->sizeHint().width());
	if (length_spacebelowplus->sizeHint().height()!=-1)
		length_spacebelowplus->setMinimumHeight(length_spacebelowplus->sizeHint().height());
	if (length_spacebelowminus->sizeHint().width()!=-1)
		length_spacebelowminus->setMinimumWidth(length_spacebelowminus->sizeHint().width());
	if (length_spacebelowminus->sizeHint().height()!=-1)
		length_spacebelowminus->setMinimumHeight(length_spacebelowminus->sizeHint().height());
	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	QBoxLayout* qtarch_layout_1_1 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_1, 1 );
	qtarch_layout_1_1->addStrut( 0 );
	qtarch_layout_1_1->addWidget( check_pagebreakbelow, 1, 33 );
	qtarch_layout_1_1->addStretch( 1 );
	QBoxLayout* qtarch_layout_1_2 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2, 1 );
	qtarch_layout_1_2->addStrut( 0 );
	qtarch_layout_1_2->addWidget( check_keepbelow, 1, 33 );
	qtarch_layout_1_2->addStretch( 1 );
	QBoxLayout* qtarch_layout_1_3 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_3, 1 );
	qtarch_layout_1_3->addStrut( 0 );
	qtarch_layout_1_3->addWidget( qtarch_belowlabel, 1, 33 );
	qtarch_layout_1_3->addStretch( 1 );
	qtarch_layout_1_3->addWidget( combo_spacebelow, 1, 33 );
	qtarch_layout_1_3->addStretch( 1 );
	QGridLayout* qtarch_layout_1_4 = new QGridLayout( 3, 5, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_4, 3 );
	qtarch_layout_1_4->addColSpacing( 0, 5 );
	qtarch_layout_1_4->setColStretch( 0, 1 );
	qtarch_layout_1_4->addColSpacing( 1, 5 );
	qtarch_layout_1_4->setColStretch( 1, 2 );
	qtarch_layout_1_4->addColSpacing( 2, 5 );
	qtarch_layout_1_4->setColStretch( 2, 1 );
	qtarch_layout_1_4->addColSpacing( 3, 5 );
	qtarch_layout_1_4->setColStretch( 3, 4 );
	qtarch_layout_1_4->addColSpacing( 4, 5 );
	qtarch_layout_1_4->setColStretch( 4, 1 );
	qtarch_layout_1_4->addRowSpacing( 0, 0 );
	qtarch_layout_1_4->setRowStretch( 0, 1 );
	qtarch_layout_1_4->addWidget( qtarch_ValueLabel, 0, 1, 33 );
	qtarch_layout_1_4->addWidget( length_spacebelow, 0, 3, 33 );
	qtarch_layout_1_4->addRowSpacing( 1, 0 );
	qtarch_layout_1_4->setRowStretch( 1, 1 );
	qtarch_layout_1_4->addWidget( qtarch_Label_14, 1, 1, 33 );
	qtarch_layout_1_4->addWidget( length_spacebelowplus, 1, 3, 33 );
	qtarch_layout_1_4->addRowSpacing( 2, 0 );
	qtarch_layout_1_4->setRowStretch( 2, 1 );
	qtarch_layout_1_4->addWidget( qtarch_belowminuslabel, 2, 1, 33 );
	qtarch_layout_1_4->addWidget( length_spacebelowminus, 2, 3, 33 );
	resize( 465,435 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


ParaBelowDialogData::~ParaBelowDialogData()
{
}
void ParaBelowDialogData::spacebelowHighlighted(int)
{
}
