/**********************************************************************

	--- Qt Architect 1.4-6 generated file ---

	File: paraextradlgdata.h
	Last generated: Sat Mar 31 16:49:02 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef ParaExtraDialogData_included
#define ParaExtraDialogData_included

#include <qwidget.h>
#include <qradiobutton.h>
#include <qcheckbox.h>
#include <qcombobox.h>
#include <qbuttongroup.h>
#include <krestrictedline.h>

class ParaExtraDialogData : public QWidget
{
    Q_OBJECT

public:

    ParaExtraDialogData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~ParaExtraDialogData();

public slots:


protected slots:

    virtual void typeHighlighted(int);

protected:
    QComboBox* combo_type;
    KRestrictedLine* line_widthvalue;
    QComboBox* combo_widthvalueunits;
    QButtonGroup* specialalignment;
    QRadioButton* radio_top;
    QRadioButton* radio_middle;
    QRadioButton* radio_bottom;
    QCheckBox* check_hfillbetween;
    QCheckBox* check_startnewminipage;

};

#endif // ParaExtraDialogData_included
