/**********************************************************************

	--- Qt Architect 1.4-6 generated file ---

	File: printdlgdata.h
	Last generated: Sat Feb 10 21:08:55 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef PrintDialogData_included
#define PrintDialogData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qradiobutton.h>
#include <qcheckbox.h>
#include <qpushbutton.h>
#include <qgroupbox.h>
#include <keditcl.h>
#include <qlineedit.h>
#include <qbuttongroup.h>

class PrintDialogData : public QDialog
{
    Q_OBJECT

public:

    PrintDialogData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~PrintDialogData();

public slots:


protected slots:

    virtual void clickedCancel();
    virtual void clickedBrowse();
    virtual void changedCount(const char*);
    virtual void clickedPrint();

protected:
    QGroupBox* pagesGroupBox;
    QButtonGroup* pagesRadioGroup;
    QGroupBox* copies;
    QGroupBox* printToGroupBox;
    QButtonGroup* printToRadioGroup;
    QPushButton* print;
    QPushButton* cancel;
    QRadioButton* allpages;
    QRadioButton* oddpages;
    QRadioButton* evenpages;
    KIntLineEdit* from;
    KIntLineEdit* to;
    QCheckBox* reverse;
    KIntLineEdit* count;
    QCheckBox* sort;
    QLabel* fromLabel;
    QLabel* toLabel;
    QRadioButton* toprinter;
    QRadioButton* tofile;
    QLineEdit* printername;
    QLineEdit* filename;
    QPushButton* browse;
    QLabel* countLabel;

};

#endif // PrintDialogData_included
