# vi:filetype=python:expandtab:tabstop=2:shiftwidth=2

# file SConscript
#
# This file is part of LyX, the document processor.
# Licence details can be found in the file COPYING.
# 
# \author Bo Peng
# Full author contact details are available in file CREDITS.

Import('env')

print "Entering src/client"

lyxclient = env.Program(
  target = 'lyxclient',
  LIBS = [ 'boost_regex', 'boost_filesystem', 
    'supports' ] + env['socket_libs'],
  source = Split('''
    boost.C
    client.C
    debug.C
    gettext.C
    messages.C
  ''')
)

Return('lyxclient')
